-- Complete seed script to populate local database with ALL 530 global ingredients from production
-- This script will ensure exact parity between local and production databases

-- Clear all existing global ingredients
TRUNCATE global_ingredients RESTART IDENTITY CASCADE;

-- Insert all 530 global ingredients from production
INSERT INTO global_ingredients (name, normalized_name, category, synonyms, usage_count, is_verified, is_system, created_by) VALUES
-- Bakery & Grains (69 items)
('Active Dry Yeast', 'active dry yeast', 'bakery_grains', '{}', 5, true, true, null),
('All-Purpose Flour', 'all purpose flour', 'bakery_grains', '{}', 5, true, true, null),
('Almond Flour', 'almond flour', 'bakery_grains', '{}', 5, true, true, null),
('Angel Hair', 'angel hair', 'bakery_grains', '{}', 5, true, true, null),
('Arborio Rice', 'arborio rice', 'bakery_grains', '{}', 5, true, true, null),
('Arrowroot Powder', 'arrowroot powder', 'bakery_grains', '{}', 5, true, true, null),
('Bagels', 'bagels', 'bakery_grains', '{}', 5, true, true, null),
('Baking Powder', 'baking powder', 'bakery_grains', '{}', 5, true, true, null),
('Baking Soda', 'baking soda', 'bakery_grains', '{}', 5, true, true, null),
('Barley', 'barley', 'bakery_grains', '{}', 5, true, true, null),
('Basmati Rice', 'basmati rice', 'bakery_grains', '{}', 5, true, true, null),
('Bread', 'bread', 'bakery_grains', '{}', 5, true, true, null),
('Bread Flour', 'bread flour', 'bakery_grains', '{}', 5, true, true, null),
('Brioche', 'brioche', 'bakery_grains', '{}', 5, true, true, null),
('Brown Rice', 'brown rice', 'bakery_grains', '{}', 5, true, true, null),
('Bulgur', 'bulgur', 'bakery_grains', '{}', 5, true, true, null),
('Cake Flour', 'cake flour', 'bakery_grains', '{}', 5, true, true, null),
('Coconut Flour', 'coconut flour', 'bakery_grains', '{}', 5, true, true, null),
('Corn Tortillas', 'corn tortillas', 'bakery_grains', '{}', 5, true, true, null),
('Cornmeal', 'cornmeal', 'bakery_grains', '{}', 5, true, true, null),
('Cornstarch', 'cornstarch', 'bakery_grains', '{}', 5, true, true, null),
('Couscous', 'couscous', 'bakery_grains', '{}', 5, true, true, null),
('Croissants', 'croissants', 'bakery_grains', '{}', 5, true, true, null),
('Dinner Rolls', 'dinner rolls', 'bakery_grains', '{}', 5, true, true, null),
('Egg Noodles', 'egg noodles', 'bakery_grains', '{}', 5, true, true, null),
('English Muffins', 'english muffins', 'bakery_grains', '{}', 5, true, true, null),
('Farro', 'farro', 'bakery_grains', '{}', 5, true, true, null),
('Fettuccine', 'fettuccine', 'bakery_grains', '{}', 5, true, true, null),
('Flour Tortillas', 'flour tortillas', 'bakery_grains', '{}', 5, true, true, null),
('Fusilli', 'fusilli', 'bakery_grains', '{}', 5, true, true, null),
('Hamburger Buns', 'hamburger buns', 'bakery_grains', '{}', 5, true, true, null),
('Hot Dog Buns', 'hot dog buns', 'bakery_grains', '{}', 5, true, true, null),
('Instant Oats', 'instant oats', 'bakery_grains', '{}', 5, true, true, null),
('Instant Yeast', 'instant yeast', 'bakery_grains', '{}', 5, true, true, null),
('Jasmine Rice', 'jasmine rice', 'bakery_grains', '{}', 5, true, true, null),
('Lasagna Sheets', 'lasagna sheets', 'bakery_grains', '{}', 5, true, true, null),
('Linguine', 'linguine', 'bakery_grains', '{}', 5, true, true, null),
('Macaroni', 'macaroni', 'bakery_grains', '{}', 5, true, true, null),
('Naan', 'naan', 'bakery_grains', '{}', 5, true, true, null),
('Oats', 'oats', 'bakery_grains', '{}', 5, true, true, null),
('Orzo', 'orzo', 'bakery_grains', '{}', 5, true, true, null),
('Pasta', 'pasta', 'bakery_grains', '{}', 5, true, true, null),
('Penne', 'penne', 'bakery_grains', '{}', 5, true, true, null),
('Phyllo Dough', 'phyllo dough', 'bakery_grains', '{}', 5, true, true, null),
('Pie Crust', 'pie crust', 'bakery_grains', '{}', 5, true, true, null),
('Pita Bread', 'pita bread', 'bakery_grains', '{}', 5, true, true, null),
('Pizza Dough', 'pizza dough', 'bakery_grains', '{}', 5, true, true, null),
('Pumpernickel Bread', 'pumpernickel bread', 'bakery_grains', '{}', 5, true, true, null),
('Quinoa', 'quinoa', 'bakery_grains', '{}', 5, true, true, null),
('Ramen Noodles', 'ramen noodles', 'bakery_grains', '{}', 5, true, true, null),
('Ravioli', 'ravioli', 'bakery_grains', '{}', 5, true, true, null),
('Rice', 'rice', 'bakery_grains', '{}', 5, true, true, null),
('Rice Noodles', 'rice noodles', 'bakery_grains', '{}', 5, true, true, null),
('Rigatoni', 'rigatoni', 'bakery_grains', '{}', 5, true, true, null),
('Rolled Oats', 'rolled oats', 'bakery_grains', '{}', 5, true, true, null),
('Rye Bread', 'rye bread', 'bakery_grains', '{}', 5, true, true, null),
('Self-Rising Flour', 'self rising flour', 'bakery_grains', '{}', 5, true, true, null),
('Semolina', 'semolina', 'bakery_grains', '{}', 5, true, true, null),
('Soba Noodles', 'soba noodles', 'bakery_grains', '{}', 5, true, true, null),
('Sourdough Bread', 'sourdough bread', 'bakery_grains', '{}', 5, true, true, null),
('Spaghetti', 'spaghetti', 'bakery_grains', '{}', 5, true, true, null),
('Steel Cut Oats', 'steel cut oats', 'bakery_grains', '{}', 5, true, true, null),
('Tapioca Starch', 'tapioca starch', 'bakery_grains', '{}', 5, true, true, null),
('Tortellini', 'tortellini', 'bakery_grains', '{}', 5, true, true, null),
('Tortillas', 'tortillas', 'bakery_grains', '{}', 5, true, true, null),
('Udon Noodles', 'udon noodles', 'bakery_grains', '{}', 5, true, true, null),
('Vermicelli', 'vermicelli', 'bakery_grains', '{}', 5, true, true, null),
('White Bread', 'white bread', 'bakery_grains', '{}', 5, true, true, null),
('White Rice', 'white rice', 'bakery_grains', '{}', 5, true, true, null),
('Whole Wheat Bread', 'whole wheat bread', 'bakery_grains', '{}', 5, true, true, null),
('Whole Wheat Flour', 'whole wheat flour', 'bakery_grains', '{}', 5, true, true, null),
('Wild Rice', 'wild rice', 'bakery_grains', '{}', 5, true, true, null),

-- Cooking Essentials (41 items)
('Almond Extract', 'almond extract', 'cooking_essentials', '{}', 5, true, true, null),
('Apple Cider Vinegar', 'apple cider vinegar', 'cooking_essentials', '{}', 5, true, true, null),
('Avocado Oil', 'avocado oil', 'cooking_essentials', '{}', 5, true, true, null),
('Balsamic Vinegar', 'balsamic vinegar', 'cooking_essentials', '{}', 5, true, true, null),
('Beef Stock', 'beef stock', 'cooking_essentials', '{}', 5, true, true, null),
('Black Peppercorns', 'black peppercorns', 'cooking_essentials', '{}', 5, true, true, null),
('Bone Broth', 'bone broth', 'cooking_essentials', '{}', 5, true, true, null),
('Butter', 'butter', 'cooking_essentials', '{}', 5, true, true, null),
('Canola Oil', 'canola oil', 'cooking_essentials', '{}', 5, true, true, null),
('Champagne Vinegar', 'champagne vinegar', 'cooking_essentials', '{}', 5, true, true, null),
('Chicken Stock', 'chicken stock', 'cooking_essentials', '{}', 5, true, true, null),
('Coconut Oil', 'coconut oil', 'cooking_essentials', '{}', 5, true, true, null),
('Cooking Sherry', 'cooking sherry', 'cooking_essentials', '{}', 5, true, true, null),
('Cooking Wine', 'cooking wine', 'cooking_essentials', '{}', 5, true, true, null),
('Extra Virgin Olive Oil', 'extra virgin olive oil', 'cooking_essentials', '{}', 5, true, true, null),
('Fish Sauce', 'fish sauce', 'cooking_essentials', '{}', 5, true, true, null),
('Ghee', 'ghee', 'cooking_essentials', '{}', 5, true, true, null),
('Kosher Salt', 'kosher salt', 'cooking_essentials', '{}', 5, true, true, null),
('Lard', 'lard', 'cooking_essentials', '{}', 5, true, true, null),
('Lemon Juice', 'lemon juice', 'cooking_essentials', '{}', 5, true, true, null),
('Lime Juice', 'lime juice', 'cooking_essentials', '{}', 5, true, true, null),
('Liquid Smoke', 'liquid smoke', 'cooking_essentials', '{}', 5, true, true, null),
('Margarine', 'margarine', 'cooking_essentials', '{}', 5, true, true, null),
('Mirin', 'mirin', 'cooking_essentials', '{}', 5, true, true, null),
('Olive Oil', 'olive oil', 'cooking_essentials', '{"extra virgin olive oil", "evoo"}', 25, true, true, null),
('Orange Juice', 'orange juice', 'cooking_essentials', '{}', 5, true, true, null),
('Peanut Oil', 'peanut oil', 'cooking_essentials', '{}', 5, true, true, null),
('Red Wine', 'red wine', 'cooking_essentials', '{}', 5, true, true, null),
('Red Wine Vinegar', 'red wine vinegar', 'cooking_essentials', '{}', 5, true, true, null),
('Rice Vinegar', 'rice vinegar', 'cooking_essentials', '{}', 5, true, true, null),
('Rice Wine', 'rice wine', 'cooking_essentials', '{}', 5, true, true, null),
('Sake', 'sake', 'cooking_essentials', '{}', 5, true, true, null),
('Sea Salt', 'sea salt', 'cooking_essentials', '{}', 5, true, true, null),
('Sesame Oil', 'sesame oil', 'cooking_essentials', '{}', 5, true, true, null),
('Sherry', 'sherry', 'cooking_essentials', '{}', 5, true, true, null),
('Sherry Vinegar', 'sherry vinegar', 'cooking_essentials', '{}', 5, true, true, null),
('Shortening', 'shortening', 'cooking_essentials', '{}', 5, true, true, null),
('Sunflower Oil', 'sunflower oil', 'cooking_essentials', '{}', 5, true, true, null),
('Vegetable Oil', 'vegetable oil', 'cooking_essentials', '{}', 5, true, true, null),
('Vegetable Stock', 'vegetable stock', 'cooking_essentials', '{}', 5, true, true, null),
('White Wine', 'white wine', 'cooking_essentials', '{}', 5, true, true, null),
('White Wine Vinegar', 'white wine vinegar', 'cooking_essentials', '{}', 5, true, true, null),
('Worcestershire Sauce', 'worcestershire sauce', 'cooking_essentials', '{}', 5, true, true, null),

-- Dairy & Cold (62 items)
('1% Milk', '1 milk', 'dairy_cold', '{}', 5, true, true, null),
('2% Milk', '2 milk', 'dairy_cold', '{}', 5, true, true, null),
('Almond Milk', 'almond milk', 'dairy_cold', '{}', 5, true, true, null),
('Asiago', 'asiago', 'dairy_cold', '{}', 5, true, true, null),
('Blue Cheese', 'blue cheese', 'dairy_cold', '{}', 5, true, true, null),
('Brie', 'brie', 'dairy_cold', '{}', 5, true, true, null),
('Brie Cheese', 'brie cheese', 'dairy_cold', '{}', 5, true, true, null),
('Buttermilk', 'buttermilk', 'dairy_cold', '{}', 5, true, true, null),
('Camembert', 'camembert', 'dairy_cold', '{}', 5, true, true, null),
('Camembert Cheese', 'camembert cheese', 'dairy_cold', '{}', 5, true, true, null),
('Cashew Milk', 'cashew milk', 'dairy_cold', '{}', 5, true, true, null),
('Cheddar', 'cheddar', 'dairy_cold', '{}', 5, true, true, null),
('Cheddar Cheese', 'cheddar cheese', 'dairy_cold', '{}', 5, true, true, null),
('Cream Cheese', 'cream cheese', 'dairy_cold', '{}', 5, true, true, null),
('Crème Fraîche', 'cr me fra che', 'dairy_cold', '{}', 5, true, true, null),
('Egg Whites', 'egg whites', 'dairy_cold', '{}', 5, true, true, null),
('Egg Yolks', 'egg yolks', 'dairy_cold', '{}', 5, true, true, null),
('European Butter', 'european butter', 'dairy_cold', '{}', 5, true, true, null),
('Extra Large Eggs', 'extra large eggs', 'dairy_cold', '{}', 5, true, true, null),
('Feta', 'feta', 'dairy_cold', '{}', 5, true, true, null),
('Feta Cheese', 'feta cheese', 'dairy_cold', '{}', 5, true, true, null),
('Fresh Mozzarella', 'fresh mozzarella', 'dairy_cold', '{}', 5, true, true, null),
('Goat Cheese', 'goat cheese', 'dairy_cold', '{}', 5, true, true, null),
('Gorgonzola', 'gorgonzola', 'dairy_cold', '{}', 5, true, true, null),
('Gouda Cheese', 'gouda cheese', 'dairy_cold', '{}', 5, true, true, null),
('Greek Yogurt', 'greek yogurt', 'dairy_cold', '{}', 5, true, true, null),
('Gruyere', 'gruyere', 'dairy_cold', '{}', 5, true, true, null),
('Half and Half', 'half and half', 'dairy_cold', '{}', 5, true, true, null),
('Heavy Cream', 'heavy cream', 'dairy_cold', '{}', 5, true, true, null),
('Heavy Whipping Cream', 'heavy whipping cream', 'dairy_cold', '{}', 5, true, true, null),
('Kefir', 'kefir', 'dairy_cold', '{}', 5, true, true, null),
('Labneh', 'labneh', 'dairy_cold', '{}', 5, true, true, null),
('Large Eggs', 'large eggs', 'dairy_cold', '{}', 5, true, true, null),
('Light Cream', 'light cream', 'dairy_cold', '{}', 5, true, true, null),
('Low-Fat Milk', 'low fat milk', 'dairy_cold', '{}', 5, true, true, null),
('Mascarpone', 'mascarpone', 'dairy_cold', '{}', 5, true, true, null),
('Mild Cheddar', 'mild cheddar', 'dairy_cold', '{}', 5, true, true, null),
('Milk', 'milk', 'dairy_cold', '{}', 5, true, true, null),
('Monterey Jack', 'monterey jack', 'dairy_cold', '{}', 5, true, true, null),
('Monterey Jack Cheese', 'monterey jack cheese', 'dairy_cold', '{}', 5, true, true, null),
('Mozzarella', 'mozzarella', 'dairy_cold', '{}', 5, true, true, null),
('Mozzarella Cheese', 'mozzarella cheese', 'dairy_cold', '{}', 5, true, true, null),
('Oat Milk', 'oat milk', 'dairy_cold', '{}', 5, true, true, null),
('Parmesan', 'parmesan', 'dairy_cold', '{}', 5, true, true, null),
('Parmesan Cheese', 'parmesan cheese', 'dairy_cold', '{}', 5, true, true, null),
('Parmigiano-Reggiano', 'parmigiano reggiano', 'dairy_cold', '{}', 5, true, true, null),
('Pepper Jack', 'pepper jack', 'dairy_cold', '{}', 5, true, true, null),
('Pepper Jack Cheese', 'pepper jack cheese', 'dairy_cold', '{}', 5, true, true, null),
('Plain Yogurt', 'plain yogurt', 'dairy_cold', '{}', 5, true, true, null),
('Provolone', 'provolone', 'dairy_cold', '{}', 5, true, true, null),
('Provolone Cheese', 'provolone cheese', 'dairy_cold', '{}', 5, true, true, null),
('Regular Yogurt', 'regular yogurt', 'dairy_cold', '{}', 5, true, true, null),
('Rice Milk', 'rice milk', 'dairy_cold', '{}', 5, true, true, null),
('Ricotta', 'ricotta', 'dairy_cold', '{}', 5, true, true, null),
('Ricotta Cheese', 'ricotta cheese', 'dairy_cold', '{}', 5, true, true, null),
('Romano', 'romano', 'dairy_cold', '{}', 5, true, true, null),
('Salted Butter', 'salted butter', 'dairy_cold', '{}', 5, true, true, null),
('Sharp Cheddar', 'sharp cheddar', 'dairy_cold', '{}', 5, true, true, null),
('Shredded Cheese', 'shredded cheese', 'dairy_cold', '{}', 5, true, true, null),
('Skim Milk', 'skim milk', 'dairy_cold', '{}', 5, true, true, null),
('Sliced Cheese', 'sliced cheese', 'dairy_cold', '{}', 5, true, true, null),
('Sour Cream', 'sour cream', 'dairy_cold', '{}', 5, true, true, null),
('Soy Milk', 'soy milk', 'dairy_cold', '{}', 5, true, true, null),
('String Cheese', 'string cheese', 'dairy_cold', '{}', 5, true, true, null),
('Swiss', 'swiss', 'dairy_cold', '{}', 5, true, true, null),
('Swiss Cheese', 'swiss cheese', 'dairy_cold', '{}', 5, true, true, null),
('Unsalted Butter', 'unsalted butter', 'dairy_cold', '{}', 5, true, true, null),
('Vanilla Yogurt', 'vanilla yogurt', 'dairy_cold', '{}', 5, true, true, null),
('Whipped Cream', 'whipped cream', 'dairy_cold', '{}', 5, true, true, null),
('Whole Milk', 'whole milk', 'dairy_cold', '{}', 5, true, true, null),

-- Flavor Builders (59 items - includes 1 user ingredient)
('Allspice', 'allspice', 'flavor_builders', '{}', 5, true, true, null),
('Bay Leaves', 'bay leaves', 'flavor_builders', '{}', 5, true, true, null),
('Black Pepper', 'black pepper', 'flavor_builders', '{}', 5, true, true, null),
('Caraway Seeds', 'caraway seeds', 'flavor_builders', '{}', 5, true, true, null),
('Cardamom', 'cardamom', 'flavor_builders', '{}', 5, true, true, null),
('Cayenne Pepper', 'cayenne pepper', 'flavor_builders', '{}', 5, true, true, null),
('Celery Seeds', 'celery seeds', 'flavor_builders', '{}', 5, true, true, null),
('Chili Powder', 'chili powder', 'flavor_builders', '{}', 5, true, true, null),
('Chinese Five Spice', 'chinese five spice', 'flavor_builders', '{}', 5, true, true, null),
('Cinnamon', 'cinnamon', 'flavor_builders', '{}', 5, true, true, null),
('Cloves', 'cloves', 'flavor_builders', '{}', 5, true, true, null),
('Coriander', 'coriander', 'flavor_builders', '{}', 5, true, true, null),
('Cumin', 'cumin', 'flavor_builders', '{}', 5, true, true, null),
('Curry Powder', 'curry powder', 'flavor_builders', '{}', 5, true, true, null),
('Dried Basil', 'dried basil', 'flavor_builders', '{}', 5, true, true, null),
('Dried Oregano', 'dried oregano', 'flavor_builders', '{}', 5, true, true, null),
('Dried Rosemary', 'dried rosemary', 'flavor_builders', '{}', 5, true, true, null),
('Dried Sage', 'dried sage', 'flavor_builders', '{}', 5, true, true, null),
('Dried Thyme', 'dried thyme', 'flavor_builders', '{}', 5, true, true, null),
('Everything Bagel Seasoning', 'everything bagel seasoning', 'flavor_builders', '{}', 5, true, true, null),
('Fennel Seeds', 'fennel seeds', 'flavor_builders', '{}', 5, true, true, null),
('Fresh Ginger', 'fresh ginger', 'flavor_builders', '{}', 5, true, true, null),
('Garam Masala', 'garam masala', 'flavor_builders', '{}', 5, true, true, null),
('Garlic', 'garlic', 'flavor_builders', '{}', 5, true, true, null),
('Garlic Cloves', 'garlic cloves', 'flavor_builders', '{}', 5, true, true, null),
('Garlic Powder', 'garlic powder', 'flavor_builders', '{}', 5, true, true, null),
('Ginger Powder', 'ginger powder', 'flavor_builders', '{}', 5, true, true, null),
('Ground Cinnamon', 'ground cinnamon', 'flavor_builders', '{}', 5, true, true, null),
('Ground Cumin', 'ground cumin', 'flavor_builders', '{}', 5, true, true, null),
('Ground Ginger', 'ground ginger', 'flavor_builders', '{}', 5, true, true, null),
('Herbs de Provence', 'herbs de provence', 'flavor_builders', '{}', 5, true, true, null),
('Italian Seasoning', 'italian seasoning', 'flavor_builders', '{}', 5, true, true, null),
('jalapeño seeded and finely chopped', 'jalape o seeded and finely', 'flavor_builders', '{}', 1, false, false, null),
('Leeks', 'leeks', 'flavor_builders', '{}', 5, true, true, null),
('Lemon Extract', 'lemon extract', 'flavor_builders', '{}', 5, true, true, null),
('Lemongrass', 'lemongrass', 'flavor_builders', '{}', 5, true, true, null),
('Marjoram', 'marjoram', 'flavor_builders', '{}', 5, true, true, null),
('Minced Garlic', 'minced garlic', 'flavor_builders', '{}', 5, true, true, null),
('Mustard Seed', 'mustard seed', 'flavor_builders', '{}', 5, true, true, null),
('Mustard Seeds', 'mustard seeds', 'flavor_builders', '{}', 5, true, true, null),
('Nutmeg', 'nutmeg', 'flavor_builders', '{}', 5, true, true, null),
('Old Bay Seasoning', 'old bay seasoning', 'flavor_builders', '{}', 5, true, true, null),
('Onion Powder', 'onion powder', 'flavor_builders', '{}', 5, true, true, null),
('Oregano', 'oregano', 'flavor_builders', '{}', 5, true, true, null),
('Paprika', 'paprika', 'flavor_builders', '{}', 5, true, true, null),
('Peppercorns', 'peppercorns', 'flavor_builders', '{}', 5, true, true, null),
('Poppy Seeds', 'poppy seeds', 'flavor_builders', '{}', 5, true, true, null),
('Red Onions', 'red onions', 'flavor_builders', '{}', 5, true, true, null),
('Red Pepper Flakes', 'red pepper flakes', 'flavor_builders', '{}', 5, true, true, null),
('Rosemary', 'rosemary', 'flavor_builders', '{}', 5, true, true, null),
('Salt', 'salt', 'flavor_builders', '{}', 5, true, true, null),
('Sesame Seeds', 'sesame seeds', 'flavor_builders', '{}', 5, true, true, null),
('Shallots', 'shallots', 'flavor_builders', '{}', 5, true, true, null),
('Smoked Paprika', 'smoked paprika', 'flavor_builders', '{}', 5, true, true, null),
('Smoked Salt', 'smoked salt', 'flavor_builders', '{}', 5, true, true, null),
('Star Anise', 'star anise', 'flavor_builders', '{}', 5, true, true, null),
('Tabasco', 'tabasco', 'flavor_builders', '{}', 5, true, true, null),
('Taco Seasoning', 'taco seasoning', 'flavor_builders', '{}', 5, true, true, null),
('Tarragon', 'tarragon', 'flavor_builders', '{}', 5, true, true, null),
('Thyme', 'thyme', 'flavor_builders', '{}', 5, true, true, null),
('Turmeric', 'turmeric', 'flavor_builders', '{}', 5, true, true, null),
('White Onions', 'white onions', 'flavor_builders', '{}', 5, true, true, null),
('White Pepper', 'white pepper', 'flavor_builders', '{}', 5, true, true, null),
('Yellow Onions', 'yellow onions', 'flavor_builders', '{}', 5, true, true, null),

-- Fresh Produce (77 items)
('Acorn Squash', 'acorn squash', 'fresh_produce', '{}', 5, true, true, null),
('Apples', 'apples', 'fresh_produce', '{}', 5, true, true, null),
('Arugula', 'arugula', 'fresh_produce', '{}', 5, true, true, null),
('Asparagus', 'asparagus', 'fresh_produce', '{}', 5, true, true, null),
('Avocados', 'avocados', 'fresh_produce', '{}', 5, true, true, null),
('Bananas', 'bananas', 'fresh_produce', '{}', 5, true, true, null),
('Basil', 'basil', 'fresh_produce', '{}', 5, true, true, null),
('Beefsteak Tomatoes', 'beefsteak tomatoes', 'fresh_produce', '{}', 5, true, true, null),
('Beets', 'beets', 'fresh_produce', '{}', 5, true, true, null),
('Bell Peppers', 'bell peppers', 'fresh_produce', '{}', 5, true, true, null),
('Berries', 'berries', 'fresh_produce', '{}', 5, true, true, null),
('Blackberries', 'blackberries', 'fresh_produce', '{}', 5, true, true, null),
('Blueberries', 'blueberries', 'fresh_produce', '{}', 5, true, true, null),
('Broccoli', 'broccoli', 'fresh_produce', '{}', 5, true, true, null),
('Brussels Sprouts', 'brussels sprouts', 'fresh_produce', '{}', 5, true, true, null),
('Butternut Squash', 'butternut squash', 'fresh_produce', '{}', 5, true, true, null),
('Cabbage', 'cabbage', 'fresh_produce', '{}', 5, true, true, null),
('Carrots', 'carrots', 'fresh_produce', '{}', 5, true, true, null),
('Cauliflower', 'cauliflower', 'fresh_produce', '{}', 5, true, true, null),
('Celery', 'celery', 'fresh_produce', '{}', 5, true, true, null),
('Cherry Tomatoes', 'cherry tomatoes', 'fresh_produce', '{}', 5, true, true, null),
('Chives', 'chives', 'fresh_produce', '{}', 5, true, true, null),
('Cilantro', 'cilantro', 'fresh_produce', '{}', 5, true, true, null),
('Cucumbers', 'cucumbers', 'fresh_produce', '{}', 5, true, true, null),
('Dill', 'dill', 'fresh_produce', '{}', 5, true, true, null),
('Eggplant', 'eggplant', 'fresh_produce', '{}', 5, true, true, null),
('Fresh Dill', 'fresh dill', 'fresh_produce', '{}', 5, true, true, null),
('Fresh Ginger Root', 'fresh ginger root', 'fresh_produce', '{}', 5, true, true, null),
('Fresh Mint', 'fresh mint', 'fresh_produce', '{}', 5, true, true, null),
('Fresh Oregano', 'fresh oregano', 'fresh_produce', '{}', 5, true, true, null),
('Fresh Rosemary', 'fresh rosemary', 'fresh_produce', '{}', 5, true, true, null),
('Fresh Sage', 'fresh sage', 'fresh_produce', '{}', 5, true, true, null),
('Fresh Thyme', 'fresh thyme', 'fresh_produce', '{}', 5, true, true, null),
('Ginger', 'ginger', 'fresh_produce', '{}', 5, true, true, null),
('Grape Tomatoes', 'grape tomatoes', 'fresh_produce', '{}', 5, true, true, null),
('Grapes', 'grapes', 'fresh_produce', '{}', 5, true, true, null),
('Green Beans', 'green beans', 'fresh_produce', '{}', 5, true, true, null),
('Green Bell Peppers', 'green bell peppers', 'fresh_produce', '{}', 5, true, true, null),
('Green Onions', 'green onions', 'fresh_produce', '{}', 5, true, true, null),
('Habanero Peppers', 'habanero peppers', 'fresh_produce', '{}', 5, true, true, null),
('Habaneros', 'habaneros', 'fresh_produce', '{}', 5, true, true, null),
('Jalapeños', 'jalape os', 'fresh_produce', '{}', 5, true, true, null),
('Kale', 'kale', 'fresh_produce', '{}', 5, true, true, null),
('Lemons', 'lemons', 'fresh_produce', '{}', 5, true, true, null),
('Lettuce', 'lettuce', 'fresh_produce', '{}', 5, true, true, null),
('Limes', 'limes', 'fresh_produce', '{}', 5, true, true, null),
('Mint', 'mint', 'fresh_produce', '{}', 5, true, true, null),
('Mixed Greens', 'mixed greens', 'fresh_produce', '{}', 5, true, true, null),
('Mushrooms', 'mushrooms', 'fresh_produce', '{}', 5, true, true, null),
('Onions', 'onions', 'fresh_produce', '{}', 5, true, true, null),
('Oranges', 'oranges', 'fresh_produce', '{}', 5, true, true, null),
('Parsley', 'parsley', 'fresh_produce', '{}', 5, true, true, null),
('Parsnips', 'parsnips', 'fresh_produce', '{}', 5, true, true, null),
('Poblano Peppers', 'poblano peppers', 'fresh_produce', '{}', 5, true, true, null),
('Potatoes', 'potatoes', 'fresh_produce', '{}', 5, true, true, null),
('Radishes', 'radishes', 'fresh_produce', '{}', 5, true, true, null),
('Raspberries', 'raspberries', 'fresh_produce', '{}', 5, true, true, null),
('Red Bell Peppers', 'red bell peppers', 'fresh_produce', '{}', 5, true, true, null),
('Roma Tomatoes', 'roma tomatoes', 'fresh_produce', '{}', 5, true, true, null),
('Sage', 'sage', 'fresh_produce', '{}', 5, true, true, null),
('Scallions', 'scallions', 'fresh_produce', '{}', 5, true, true, null),
('Serrano Peppers', 'serrano peppers', 'fresh_produce', '{}', 5, true, true, null),
('Spinach', 'spinach', 'fresh_produce', '{}', 5, true, true, null),
('Strawberries', 'strawberries', 'fresh_produce', '{}', 5, true, true, null),
('Sweet Potatoes', 'sweet potatoes', 'fresh_produce', '{}', 5, true, true, null),
('Tomatoes', 'tomatoes', 'fresh_produce', '{}', 5, true, true, null),
('Turnips', 'turnips', 'fresh_produce', '{}', 5, true, true, null),
('Yellow Squash', 'yellow squash', 'fresh_produce', '{}', 5, true, true, null),
('Zucchini', 'zucchini', 'fresh_produce', '{}', 5, true, true, null),

-- Frozen (48 items)
('Chocolate Ice Cream', 'chocolate ice cream', 'frozen', '{}', 5, true, true, null),
('Frozen Berries', 'frozen berries', 'frozen', '{}', 5, true, true, null),
('Frozen Blueberries', 'frozen blueberries', 'frozen', '{}', 5, true, true, null),
('Frozen Broccoli', 'frozen broccoli', 'frozen', '{}', 5, true, true, null),
('Frozen Brussels Sprouts', 'frozen brussels sprouts', 'frozen', '{}', 5, true, true, null),
('Frozen Burritos', 'frozen burritos', 'frozen', '{}', 5, true, true, null),
('Frozen Carrots', 'frozen carrots', 'frozen', '{}', 5, true, true, null),
('Frozen Cauliflower', 'frozen cauliflower', 'frozen', '{}', 5, true, true, null),
('Frozen Cherries', 'frozen cherries', 'frozen', '{}', 5, true, true, null),
('Frozen Chicken', 'frozen chicken', 'frozen', '{}', 5, true, true, null),
('Frozen Chicken Nuggets', 'frozen chicken nuggets', 'frozen', '{}', 5, true, true, null),
('Frozen Corn', 'frozen corn', 'frozen', '{}', 5, true, true, null),
('Frozen Dumplings', 'frozen dumplings', 'frozen', '{}', 5, true, true, null),
('Frozen Edamame', 'frozen edamame', 'frozen', '{}', 5, true, true, null),
('Frozen Fish', 'frozen fish', 'frozen', '{}', 5, true, true, null),
('Frozen Fish Sticks', 'frozen fish sticks', 'frozen', '{}', 5, true, true, null),
('Frozen French Fries', 'frozen french fries', 'frozen', '{}', 5, true, true, null),
('Frozen French Toast', 'frozen french toast', 'frozen', '{}', 5, true, true, null),
('Frozen Fries', 'frozen fries', 'frozen', '{}', 5, true, true, null),
('Frozen Fruit Bars', 'frozen fruit bars', 'frozen', '{}', 5, true, true, null),
('Frozen Green Beans', 'frozen green beans', 'frozen', '{}', 5, true, true, null),
('Frozen Hash Browns', 'frozen hash browns', 'frozen', '{}', 5, true, true, null),
('Frozen Lasagna', 'frozen lasagna', 'frozen', '{}', 5, true, true, null),
('Frozen Mango', 'frozen mango', 'frozen', '{}', 5, true, true, null),
('Frozen Meatballs', 'frozen meatballs', 'frozen', '{}', 5, true, true, null),
('Frozen Mixed Vegetables', 'frozen mixed vegetables', 'frozen', '{}', 5, true, true, null),
('Frozen Onion Rings', 'frozen onion rings', 'frozen', '{}', 5, true, true, null),
('Frozen Pancakes', 'frozen pancakes', 'frozen', '{}', 5, true, true, null),
('Frozen Peaches', 'frozen peaches', 'frozen', '{}', 5, true, true, null),
('Frozen Peas', 'frozen peas', 'frozen', '{}', 5, true, true, null),
('Frozen Pierogies', 'frozen pierogies', 'frozen', '{}', 5, true, true, null),
('Frozen Pineapple', 'frozen pineapple', 'frozen', '{}', 5, true, true, null),
('Frozen Pizza', 'frozen pizza', 'frozen', '{}', 5, true, true, null),
('Frozen Pot Stickers', 'frozen pot stickers', 'frozen', '{}', 5, true, true, null),
('Frozen Raspberries', 'frozen raspberries', 'frozen', '{}', 5, true, true, null),
('Frozen Ravioli', 'frozen ravioli', 'frozen', '{}', 5, true, true, null),
('Frozen Shrimp', 'frozen shrimp', 'frozen', '{}', 5, true, true, null),
('Frozen Spinach', 'frozen spinach', 'frozen', '{}', 5, true, true, null),
('Frozen Stir Fry', 'frozen stir fry', 'frozen', '{}', 5, true, true, null),
('Frozen Strawberries', 'frozen strawberries', 'frozen', '{}', 5, true, true, null),
('Frozen Vegetables', 'frozen vegetables', 'frozen', '{}', 5, true, true, null),
('Frozen Waffles', 'frozen waffles', 'frozen', '{}', 5, true, true, null),
('Frozen Whipped Topping', 'frozen whipped topping', 'frozen', '{}', 5, true, true, null),
('Frozen Yogurt', 'frozen yogurt', 'frozen', '{}', 5, true, true, null),
('Ice Cream', 'ice cream', 'frozen', '{}', 5, true, true, null),
('Ice Cream Bars', 'ice cream bars', 'frozen', '{}', 5, true, true, null),
('Ice Cubes', 'ice cubes', 'frozen', '{}', 5, true, true, null),
('Popsicles', 'popsicles', 'frozen', '{}', 5, true, true, null),
('Sherbet', 'sherbet', 'frozen', '{}', 5, true, true, null),
('Sorbet', 'sorbet', 'frozen', '{}', 5, true, true, null),
('Vanilla Ice Cream', 'vanilla ice cream', 'frozen', '{}', 5, true, true, null),

-- Pantry Staples (132 items - includes 2 user ingredients)
('Agave Nectar', 'agave nectar', 'pantry_staples', '{}', 5, true, true, null),
('aji amarillo paste', 'aji amarillo paste', 'pantry_staples', '{}', 1, false, false, null),
('Alfredo Sauce', 'alfredo sauce', 'pantry_staples', '{}', 5, true, true, null),
('Almond Butter', 'almond butter', 'pantry_staples', '{}', 5, true, true, null),
('Almonds', 'almonds', 'pantry_staples', '{}', 5, true, true, null),
('BBQ Sauce', 'bbq sauce', 'pantry_staples', '{}', 5, true, true, null),
('Beef Broth', 'beef broth', 'pantry_staples', '{}', 5, true, true, null),
('Black Beans', 'black beans', 'pantry_staples', '{}', 5, true, true, null),
('Breadcrumbs', 'breadcrumbs', 'pantry_staples', '{}', 5, true, true, null),
('Brown Sugar', 'brown sugar', 'pantry_staples', '{}', 5, true, true, null),
('Canned Beans', 'canned beans', 'pantry_staples', '{}', 5, true, true, null),
('Canned Carrots', 'canned carrots', 'pantry_staples', '{}', 5, true, true, null),
('Canned Chicken', 'canned chicken', 'pantry_staples', '{}', 5, true, true, null),
('Canned Corn', 'canned corn', 'pantry_staples', '{}', 5, true, true, null),
('Canned Green Beans', 'canned green beans', 'pantry_staples', '{}', 5, true, true, null),
('Canned Peaches', 'canned peaches', 'pantry_staples', '{}', 5, true, true, null),
('Canned Pears', 'canned pears', 'pantry_staples', '{}', 5, true, true, null),
('Canned Peas', 'canned peas', 'pantry_staples', '{}', 5, true, true, null),
('Canned Pumpkin', 'canned pumpkin', 'pantry_staples', '{}', 5, true, true, null),
('Canned Salmon', 'canned salmon', 'pantry_staples', '{}', 5, true, true, null),
('Canned Sardines', 'canned sardines', 'pantry_staples', '{}', 5, true, true, null),
('Canned Sweet Potato', 'canned sweet potato', 'pantry_staples', '{}', 5, true, true, null),
('Canned Tomatoes', 'canned tomatoes', 'pantry_staples', '{}', 5, true, true, null),
('Canned Tuna', 'canned tuna', 'pantry_staples', '{}', 5, true, true, null),
('Capers', 'capers', 'pantry_staples', '{}', 5, true, true, null),
('Cereal', 'cereal', 'pantry_staples', '{}', 5, true, true, null),
('Chicken Broth', 'chicken broth', 'pantry_staples', '{}', 5, true, true, null),
('Chicken Noodle Soup', 'chicken noodle soup', 'pantry_staples', '{}', 5, true, true, null),
('Chickpeas', 'chickpeas', 'pantry_staples', '{}', 5, true, true, null),
('Chocolate Chips', 'chocolate chips', 'pantry_staples', '{}', 5, true, true, null),
('Cocoa Powder', 'cocoa powder', 'pantry_staples', '{}', 5, true, true, null),
('Coconut Extract', 'coconut extract', 'pantry_staples', '{}', 5, true, true, null),
('Coconut Milk', 'coconut milk', 'pantry_staples', '{}', 5, true, true, null),
('Condensed Milk', 'condensed milk', 'pantry_staples', '{}', 5, true, true, null),
('Crackers', 'crackers', 'pantry_staples', '{}', 5, true, true, null),
('Crushed Tomatoes', 'crushed tomatoes', 'pantry_staples', '{}', 5, true, true, null),
('Dark Chocolate', 'dark chocolate', 'pantry_staples', '{"bittersweet chocolate", "semisweet chocolate"}', 10, true, true, null),
('Dates', 'dates', 'pantry_staples', '{}', 5, true, true, null),
('Diced Tomatoes', 'diced tomatoes', 'pantry_staples', '{}', 5, true, true, null),
('Dijon Mustard', 'dijon mustard', 'pantry_staples', '{}', 5, true, true, null),
('Dried Cranberries', 'dried cranberries', 'pantry_staples', '{}', 5, true, true, null),
('Dried Fruit', 'dried fruit', 'pantry_staples', '{}', 5, true, true, null),
('Evaporated Milk', 'evaporated milk', 'pantry_staples', '{}', 5, true, true, null),
('Graham Crackers', 'graham crackers', 'pantry_staples', '{}', 5, true, true, null),
('Granola', 'granola', 'pantry_staples', '{}', 5, true, true, null),
('Grape Jelly', 'grape jelly', 'pantry_staples', '{}', 5, true, true, null),
('Green Olives', 'green olives', 'pantry_staples', '{}', 5, true, true, null),
('Guacamole', 'guacamole', 'pantry_staples', '{}', 5, true, true, null),
('Hoisin Sauce', 'hoisin sauce', 'pantry_staples', '{}', 5, true, true, null),
('Honey', 'honey', 'pantry_staples', '{}', 5, true, true, null),
('Hot Sauce', 'hot sauce', 'pantry_staples', '{}', 5, true, true, null),
('Instant Oatmeal', 'instant oatmeal', 'pantry_staples', '{}', 5, true, true, null),
('Jam', 'jam', 'pantry_staples', '{}', 5, true, true, null),
('Jelly', 'jelly', 'pantry_staples', '{}', 5, true, true, null),
('Kalamata Olives', 'kalamata olives', 'pantry_staples', '{}', 5, true, true, null),
('Ketchup', 'ketchup', 'pantry_staples', '{}', 5, true, true, null),
('Kidney Beans', 'kidney beans', 'pantry_staples', '{}', 5, true, true, null),
('Low Sodium Soy Sauce', 'low sodium soy sauce', 'pantry_staples', '{}', 5, true, true, null),
('Maple Syrup', 'maple syrup', 'pantry_staples', '{"pure maple syrup", "syrup"}', 10, true, true, null),
('Marinara Sauce', 'marinara sauce', 'pantry_staples', '{}', 5, true, true, null),
('Mayonnaise', 'mayonnaise', 'pantry_staples', '{}', 5, true, true, null),
('Milk Chocolate', 'milk chocolate', 'pantry_staples', '{}', 5, true, true, null),
('Mixed Nuts', 'mixed nuts', 'pantry_staples', '{}', 5, true, true, null),
('Mustard', 'mustard', 'pantry_staples', '{}', 5, true, true, null),
('Navy Beans', 'navy beans', 'pantry_staples', '{}', 5, true, true, null),
('Nutella', 'nutella', 'pantry_staples', '{}', 5, true, true, null),
('Nuts', 'nuts', 'pantry_staples', '{}', 5, true, true, null),
('Oatmeal', 'oatmeal', 'pantry_staples', '{}', 5, true, true, null),
('Olives', 'olives', 'pantry_staples', '{}', 5, true, true, null),
('Orange Marmalade', 'orange marmalade', 'pantry_staples', '{}', 5, true, true, null),
('Oyster Sauce', 'oyster sauce', 'pantry_staples', '{}', 5, true, true, null),
('Panko', 'panko', 'pantry_staples', '{}', 5, true, true, null),
('Pasta Sauce', 'pasta sauce', 'pantry_staples', '{}', 5, true, true, null),
('Peanut Butter', 'peanut butter', 'pantry_staples', '{}', 5, true, true, null),
('Peanuts', 'peanuts', 'pantry_staples', '{}', 5, true, true, null),
('Pecans', 'pecans', 'pantry_staples', '{}', 5, true, true, null),
('Pesto', 'pesto', 'pantry_staples', '{}', 5, true, true, null),
('Pickles', 'pickles', 'pantry_staples', '{}', 5, true, true, null),
('Pinto Beans', 'pinto beans', 'pantry_staples', '{}', 5, true, true, null),
('Pizza Sauce', 'pizza sauce', 'pantry_staples', '{}', 5, true, true, null),
('Popcorn', 'popcorn', 'pantry_staples', '{}', 5, true, true, null),
('Powdered Sugar', 'powdered sugar', 'pantry_staples', '{}', 5, true, true, null),
('Preserves', 'preserves', 'pantry_staples', '{}', 5, true, true, null),
('Raisins', 'raisins', 'pantry_staples', '{}', 5, true, true, null),
('Refried Beans', 'refried beans', 'pantry_staples', '{}', 5, true, true, null),
('Salsa', 'salsa', 'pantry_staples', '{}', 5, true, true, null),
('Saltines', 'saltines', 'pantry_staples', '{}', 5, true, true, null),
('Soup', 'soup', 'pantry_staples', '{}', 5, true, true, null),
('Soy Sauce', 'soy sauce', 'pantry_staples', '{}', 5, true, true, null),
('Sriracha', 'sriracha', 'pantry_staples', '{}', 5, true, true, null),
('Strawberry Jam', 'strawberry jam', 'pantry_staples', '{}', 5, true, true, null),
('Sugar', 'sugar', 'pantry_staples', '{}', 5, true, true, null),
('Sun-Dried Tomatoes', 'sun dried tomatoes', 'pantry_staples', '{}', 5, true, true, null),
('Sunflower Seed Butter', 'sunflower seed butter', 'pantry_staples', '{}', 5, true, true, null),
('Tahini', 'tahini', 'pantry_staples', '{}', 5, true, true, null),
('Tamari', 'tamari', 'pantry_staples', '{}', 5, true, true, null),
('Teriyaki Sauce', 'teriyaki sauce', 'pantry_staples', '{}', 5, true, true, null),
('Tomato Paste', 'tomato paste', 'pantry_staples', '{}', 5, true, true, null),
('Tomato Sauce', 'tomato sauce', 'pantry_staples', '{}', 5, true, true, null),
('Tomato Soup', 'tomato soup', 'pantry_staples', '{}', 5, true, true, null),
('Vanilla Extract', 'vanilla extract', 'pantry_staples', '{"vanilla"}', 20, true, true, null),
('Vegetable Broth', 'vegetable broth', 'pantry_staples', '{}', 5, true, true, null),
('Vegetable Soup', 'vegetable soup', 'pantry_staples', '{}', 5, true, true, null),
('Walnuts', 'walnuts', 'pantry_staples', '{}', 5, true, true, null),
('water', 'water', 'pantry_staples', '{}', 1, false, false, null),
('White Beans', 'white beans', 'pantry_staples', '{}', 5, true, true, null),
('White Chocolate', 'white chocolate', 'pantry_staples', '{}', 5, true, true, null),
('White Sugar', 'white sugar', 'pantry_staples', '{}', 5, true, true, null),
('Whole Grain Mustard', 'whole grain mustard', 'pantry_staples', '{}', 5, true, true, null),
('Whole Tomatoes', 'whole tomatoes', 'pantry_staples', '{}', 5, true, true, null),

-- Proteins (62 items - includes 1 user ingredient)
('Anchovies', 'anchovies', 'proteins', '{}', 5, true, true, null),
('Bacon', 'bacon', 'proteins', '{}', 5, true, true, null),
('Beef Chuck', 'beef chuck', 'proteins', '{}', 5, true, true, null),
('Beef Short Ribs', 'beef short ribs', 'proteins', '{}', 5, true, true, null),
('Beef Steak', 'beef steak', 'proteins', '{}', 5, true, true, null),
('Beef Stew Meat', 'beef stew meat', 'proteins', '{}', 5, true, true, null),
('Bison', 'bison', 'proteins', '{}', 5, true, true, null),
('Cashews', 'cashews', 'proteins', '{}', 5, true, true, null),
('Chia Seeds', 'chia seeds', 'proteins', '{}', 5, true, true, null),
('Chicken Breast', 'chicken breast', 'proteins', '{}', 5, true, true, null),
('Chicken Thighs', 'chicken thighs', 'proteins', '{}', 5, true, true, null),
('Chicken Wings', 'chicken wings', 'proteins', '{}', 5, true, true, null),
('Cod Fillets', 'cod fillets', 'proteins', '{}', 5, true, true, null),
('Cottage Cheese', 'cottage cheese', 'proteins', '{}', 5, true, true, null),
('Crab', 'crab', 'proteins', '{}', 5, true, true, null),
('Duck', 'duck', 'proteins', '{}', 5, true, true, null),
('Edamame', 'edamame', 'proteins', '{}', 5, true, true, null),
('Eggs', 'eggs', 'proteins', '{}', 5, true, true, null),
('Green Lentils', 'green lentils', 'proteins', '{}', 5, true, true, null),
('Ground Beef', 'ground beef', 'proteins', '{}', 5, true, true, null),
('Ground Lamb', 'ground lamb', 'proteins', '{}', 5, true, true, null),
('Ground Pork', 'ground pork', 'proteins', '{}', 5, true, true, null),
('Ground Turkey', 'ground turkey', 'proteins', '{}', 5, true, true, null),
('Ham', 'ham', 'proteins', '{}', 5, true, true, null),
('Hemp Seeds', 'hemp seeds', 'proteins', '{}', 5, true, true, null),
('Lamb Chops', 'lamb chops', 'proteins', '{}', 5, true, true, null),
('Lamb Shanks', 'lamb shanks', 'proteins', '{}', 5, true, true, null),
('Lentils', 'lentils', 'proteins', '{}', 5, true, true, null),
('Lobster', 'lobster', 'proteins', '{}', 5, true, true, null),
('Mussels', 'mussels', 'proteins', '{}', 5, true, true, null),
('Nutritional Yeast', 'nutritional yeast', 'proteins', '{}', 5, true, true, null),
('Pork Chops', 'pork chops', 'proteins', '{}', 5, true, true, null),
('Pork Ribs', 'pork ribs', 'proteins', '{}', 5, true, true, null),
('Pork Shoulder', 'pork shoulder', 'proteins', '{}', 1, false, true, null),
('Protein Powder', 'protein powder', 'proteins', '{}', 5, true, true, null),
('Red Lentils', 'red lentils', 'proteins', '{}', 5, true, true, null),
('Salmon Fillets', 'salmon fillets', 'proteins', '{}', 5, true, true, null),
('Sardines', 'sardines', 'proteins', '{}', 5, true, true, null),
('Sausage', 'sausage', 'proteins', '{}', 5, true, true, null),
('Scallops', 'scallops', 'proteins', '{}', 5, true, true, null),
('Seitan', 'seitan', 'proteins', '{}', 5, true, true, null),
('Shrimp', 'shrimp', 'proteins', '{}', 5, true, true, null),
('Smoked Salmon', 'smoked salmon', 'proteins', '{}', 5, true, true, null),
('Split Peas', 'split peas', 'proteins', '{}', 5, true, true, null),
('Sunflower Seeds', 'sunflower seeds', 'proteins', '{}', 5, true, true, null),
('Tempeh', 'tempeh', 'proteins', '{}', 5, true, true, null),
('Tofu', 'tofu', 'proteins', '{}', 5, true, true, null),
('Tuna Steaks', 'tuna steaks', 'proteins', '{}', 5, true, true, null),
('Turkey Breast', 'turkey breast', 'proteins', '{}', 5, true, true, null),
('Venison', 'venison', 'proteins', '{}', 5, true, true, null),
('Whole Chicken', 'whole chicken', 'proteins', '{}', 5, true, true, null);

-- Update the timestamps for system ingredients
UPDATE global_ingredients 
SET 
  created_at = now() - interval '30 days',
  updated_at = now() - interval '30 days',
  first_seen_at = now() - interval '30 days',
  last_seen_at = now() - interval '1 day'
WHERE is_system = true;

-- Update the timestamps for user ingredients to be more recent
UPDATE global_ingredients 
SET 
  created_at = now() - interval '7 days',
  updated_at = now() - interval '7 days',
  first_seen_at = now() - interval '7 days',
  last_seen_at = now() - interval '1 hour'
WHERE is_system = false;
