-- Seed script to populate local database with global ingredients from production
-- This script will insert all system global ingredients into the local database

-- Clear existing system ingredients (keep user-created ones)
DELETE FROM global_ingredients WHERE is_system = true;

-- Insert all system global ingredients
-- Note: These are the core ingredients that should be available in all environments

-- Bakery & Grains
INSERT INTO global_ingredients (name, normalized_name, category, synonyms, usage_count, is_verified, is_system, created_by) VALUES
('Active Dry Yeast', 'active dry yeast', 'bakery_grains', '{}', 5, true, true, null),
('All-Purpose Flour', 'all purpose flour', 'bakery_grains', '{}', 5, true, true, null),
('Almond Flour', 'almond flour', 'bakery_grains', '{}', 5, true, true, null),
('Angel Hair', 'angel hair', 'bakery_grains', '{}', 5, true, true, null),
('Arborio Rice', 'arborio rice', 'bakery_grains', '{}', 5, true, true, null),
('Arrowroot Powder', 'arrowroot powder', 'bakery_grains', '{}', 5, true, true, null),
('Bagels', 'bagels', 'bakery_grains', '{}', 5, true, true, null),
('Baking Powder', 'baking powder', 'bakery_grains', '{}', 5, true, true, null),
('Baking Soda', 'baking soda', 'bakery_grains', '{}', 5, true, true, null),
('Barley', 'barley', 'bakery_grains', '{}', 5, true, true, null),
('Basmati Rice', 'basmati rice', 'bakery_grains', '{}', 5, true, true, null),
('Bread Crumbs', 'bread crumbs', 'bakery_grains', '{}', 5, true, true, null),
('Brown Rice', 'brown rice', 'bakery_grains', '{}', 5, true, true, null),
('Buckwheat Flour', 'buckwheat flour', 'bakery_grains', '{}', 5, true, true, null),
('Bulgur', 'bulgur', 'bakery_grains', '{}', 5, true, true, null),
('Cake Flour', 'cake flour', 'bakery_grains', '{}', 5, true, true, null),
('Coconut Flour', 'coconut flour', 'bakery_grains', '{}', 5, true, true, null),
('Cornmeal', 'cornmeal', 'bakery_grains', '{}', 5, true, true, null),
('Cornstarch', 'cornstarch', 'bakery_grains', '{}', 5, true, true, null),
('Couscous', 'couscous', 'bakery_grains', '{}', 5, true, true, null),
('Farfalle', 'farfalle', 'bakery_grains', '{}', 5, true, true, null),
('Fettuccine', 'fettuccine', 'bakery_grains', '{}', 5, true, true, null),
('Focaccia', 'focaccia', 'bakery_grains', '{}', 5, true, true, null),
('French Bread', 'french bread', 'bakery_grains', '{}', 5, true, true, null),
('Fusilli', 'fusilli', 'bakery_grains', '{}', 5, true, true, null),
('Jasmine Rice', 'jasmine rice', 'bakery_grains', '{}', 5, true, true, null),
('Lasagna Noodles', 'lasagna noodles', 'bakery_grains', '{}', 5, true, true, null),
('Linguine', 'linguine', 'bakery_grains', '{}', 5, true, true, null),
('Macaroni', 'macaroni', 'bakery_grains', '{}', 5, true, true, null),
('Oats', 'oats', 'bakery_grains', '{}', 5, true, true, null),
('Orzo', 'orzo', 'bakery_grains', '{}', 5, true, true, null),
('Penne', 'penne', 'bakery_grains', '{}', 5, true, true, null),
('Quinoa', 'quinoa', 'bakery_grains', '{}', 5, true, true, null),
('Rigatoni', 'rigatoni', 'bakery_grains', '{}', 5, true, true, null),
('Rotini', 'rotini', 'bakery_grains', '{}', 5, true, true, null),
('Rye Flour', 'rye flour', 'bakery_grains', '{}', 5, true, true, null),
('Self-Rising Flour', 'self rising flour', 'bakery_grains', '{}', 5, true, true, null),
('Semolina', 'semolina', 'bakery_grains', '{}', 5, true, true, null),
('Sourdough', 'sourdough', 'bakery_grains', '{}', 5, true, true, null),
('Spaghetti', 'spaghetti', 'bakery_grains', '{}', 5, true, true, null),
('Tapioca Starch', 'tapioca starch', 'bakery_grains', '{}', 5, true, true, null),
('Tortillas', 'tortillas', 'bakery_grains', '{}', 5, true, true, null),
('Whole Wheat Flour', 'whole wheat flour', 'bakery_grains', '{}', 5, true, true, null),
('Wild Rice', 'wild rice', 'bakery_grains', '{}', 5, true, true, null);

-- Cooking Essentials
INSERT INTO global_ingredients (name, normalized_name, category, synonyms, usage_count, is_verified, is_system, created_by) VALUES
('Apple Cider Vinegar', 'apple cider vinegar', 'cooking_essentials', '{}', 5, true, true, null),
('Avocado Oil', 'avocado oil', 'cooking_essentials', '{}', 5, true, true, null),
('Balsamic Vinegar', 'balsamic vinegar', 'cooking_essentials', '{}', 5, true, true, null),
('Beef Stock', 'beef stock', 'cooking_essentials', '{}', 5, true, true, null),
('Canola Oil', 'canola oil', 'cooking_essentials', '{}', 5, true, true, null),
('Chicken Stock', 'chicken stock', 'cooking_essentials', '{}', 5, true, true, null),
('Coconut Oil', 'coconut oil', 'cooking_essentials', '{}', 5, true, true, null),
('Dry White Wine', 'dry white wine', 'cooking_essentials', '{}', 5, true, true, null),
('Extra Virgin Olive Oil', 'extra virgin olive oil', 'cooking_essentials', '{}', 5, true, true, null),
('Fish Stock', 'fish stock', 'cooking_essentials', '{}', 5, true, true, null),
('Grapeseed Oil', 'grapeseed oil', 'cooking_essentials', '{}', 5, true, true, null),
('Kosher Salt', 'kosher salt', 'cooking_essentials', '{}', 5, true, true, null),
('Lemon Juice', 'lemon juice', 'cooking_essentials', '{}', 5, true, true, null),
('Lime Juice', 'lime juice', 'cooking_essentials', '{}', 5, true, true, null),
('Olive Oil', 'olive oil', 'cooking_essentials', '{"extra virgin olive oil", "evoo"}', 25, true, true, null),
('Peanut Oil', 'peanut oil', 'cooking_essentials', '{}', 5, true, true, null),
('Red Wine', 'red wine', 'cooking_essentials', '{}', 5, true, true, null),
('Red Wine Vinegar', 'red wine vinegar', 'cooking_essentials', '{}', 5, true, true, null),
('Rice Vinegar', 'rice vinegar', 'cooking_essentials', '{}', 5, true, true, null),
('Sea Salt', 'sea salt', 'cooking_essentials', '{}', 5, true, true, null),
('Sesame Oil', 'sesame oil', 'cooking_essentials', '{}', 5, true, true, null),
('Sunflower Oil', 'sunflower oil', 'cooking_essentials', '{}', 5, true, true, null),
('Vegetable Oil', 'vegetable oil', 'cooking_essentials', '{}', 5, true, true, null),
('Vegetable Stock', 'vegetable stock', 'cooking_essentials', '{}', 5, true, true, null),
('White Wine', 'white wine', 'cooking_essentials', '{}', 5, true, true, null),
('White Wine Vinegar', 'white wine vinegar', 'cooking_essentials', '{}', 5, true, true, null);

-- Dairy & Cold
INSERT INTO global_ingredients (name, normalized_name, category, synonyms, usage_count, is_verified, is_system, created_by) VALUES
('Brie', 'brie', 'dairy_cold', '{}', 5, true, true, null),
('Buttermilk', 'buttermilk', 'dairy_cold', '{}', 5, true, true, null),
('Cheddar Cheese', 'cheddar cheese', 'dairy_cold', '{}', 5, true, true, null),
('Cream Cheese', 'cream cheese', 'dairy_cold', '{}', 5, true, true, null),
('Eggs', 'eggs', 'dairy_cold', '{}', 5, true, true, null),
('Feta Cheese', 'feta cheese', 'dairy_cold', '{}', 5, true, true, null),
('Goat Cheese', 'goat cheese', 'dairy_cold', '{}', 5, true, true, null),
('Greek Yogurt', 'greek yogurt', 'dairy_cold', '{}', 5, true, true, null),
('Gruyere', 'gruyere', 'dairy_cold', '{}', 5, true, true, null),
('Half and Half', 'half and half', 'dairy_cold', '{}', 5, true, true, null),
('Heavy Cream', 'heavy cream', 'dairy_cold', '{}', 5, true, true, null),
('Milk', 'milk', 'dairy_cold', '{}', 5, true, true, null),
('Mozzarella', 'mozzarella', 'dairy_cold', '{}', 5, true, true, null),
('Parmesan', 'parmesan', 'dairy_cold', '{}', 5, true, true, null),
('Ricotta', 'ricotta', 'dairy_cold', '{}', 5, true, true, null),
('Salted Butter', 'salted butter', 'dairy_cold', '{}', 5, true, true, null),
('Sour Cream', 'sour cream', 'dairy_cold', '{}', 5, true, true, null),
('Swiss Cheese', 'swiss cheese', 'dairy_cold', '{}', 5, true, true, null),
('Unsalted Butter', 'unsalted butter', 'dairy_cold', '{}', 5, true, true, null),
('Whole Milk', 'whole milk', 'dairy_cold', '{}', 5, true, true, null),
('Yogurt', 'yogurt', 'dairy_cold', '{}', 5, true, true, null);

-- Flavor Builders (Spices & Seasonings)
INSERT INTO global_ingredients (name, normalized_name, category, synonyms, usage_count, is_verified, is_system, created_by) VALUES
('Allspice', 'allspice', 'flavor_builders', '{}', 5, true, true, null),
('Basil', 'basil', 'flavor_builders', '{}', 5, true, true, null),
('Bay Leaves', 'bay leaves', 'flavor_builders', '{}', 5, true, true, null),
('Black Pepper', 'black pepper', 'flavor_builders', '{}', 5, true, true, null),
('Cardamom', 'cardamom', 'flavor_builders', '{}', 5, true, true, null),
('Cayenne Pepper', 'cayenne pepper', 'flavor_builders', '{}', 5, true, true, null),
('Chili Powder', 'chili powder', 'flavor_builders', '{}', 5, true, true, null),
('Cinnamon', 'cinnamon', 'flavor_builders', '{}', 5, true, true, null),
('Cloves', 'cloves', 'flavor_builders', '{}', 5, true, true, null),
('Coriander', 'coriander', 'flavor_builders', '{}', 5, true, true, null),
('Cumin', 'cumin', 'flavor_builders', '{}', 5, true, true, null),
('Curry Powder', 'curry powder', 'flavor_builders', '{}', 5, true, true, null),
('Dill', 'dill', 'flavor_builders', '{}', 5, true, true, null),
('Garlic Powder', 'garlic powder', 'flavor_builders', '{}', 5, true, true, null),
('Ginger', 'ginger', 'flavor_builders', '{}', 5, true, true, null),
('Italian Seasoning', 'italian seasoning', 'flavor_builders', '{}', 5, true, true, null),
('Nutmeg', 'nutmeg', 'flavor_builders', '{}', 5, true, true, null),
('Onion Powder', 'onion powder', 'flavor_builders', '{}', 5, true, true, null),
('Oregano', 'oregano', 'flavor_builders', '{}', 5, true, true, null),
('Paprika', 'paprika', 'flavor_builders', '{}', 5, true, true, null),
('Red Pepper Flakes', 'red pepper flakes', 'flavor_builders', '{}', 5, true, true, null),
('Rosemary', 'rosemary', 'flavor_builders', '{}', 5, true, true, null),
('Sage', 'sage', 'flavor_builders', '{}', 5, true, true, null),
('Salt', 'salt', 'flavor_builders', '{}', 5, true, true, null),
('Smoked Salt', 'smoked salt', 'flavor_builders', '{}', 5, true, true, null),
('Thyme', 'thyme', 'flavor_builders', '{}', 5, true, true, null),
('Turmeric', 'turmeric', 'flavor_builders', '{}', 5, true, true, null),
('White Pepper', 'white pepper', 'flavor_builders', '{}', 5, true, true, null);

-- Fresh Produce
INSERT INTO global_ingredients (name, normalized_name, category, synonyms, usage_count, is_verified, is_system, created_by) VALUES
('Apples', 'apples', 'fresh_produce', '{}', 5, true, true, null),
('Arugula', 'arugula', 'fresh_produce', '{}', 5, true, true, null),
('Asparagus', 'asparagus', 'fresh_produce', '{}', 5, true, true, null),
('Avocado', 'avocado', 'fresh_produce', '{}', 5, true, true, null),
('Bananas', 'bananas', 'fresh_produce', '{}', 5, true, true, null),
('Bell Peppers', 'bell peppers', 'fresh_produce', '{}', 5, true, true, null),
('Broccoli', 'broccoli', 'fresh_produce', '{}', 5, true, true, null),
('Brussels Sprouts', 'brussels sprouts', 'fresh_produce', '{}', 5, true, true, null),
('Cabbage', 'cabbage', 'fresh_produce', '{}', 5, true, true, null),
('Carrots', 'carrots', 'fresh_produce', '{}', 5, true, true, null),
('Cauliflower', 'cauliflower', 'fresh_produce', '{}', 5, true, true, null),
('Celery', 'celery', 'fresh_produce', '{}', 5, true, true, null),
('Cherry Tomatoes', 'cherry tomatoes', 'fresh_produce', '{}', 5, true, true, null),
('Cilantro', 'cilantro', 'fresh_produce', '{}', 5, true, true, null),
('Cucumber', 'cucumber', 'fresh_produce', '{}', 5, true, true, null),
('Eggplant', 'eggplant', 'fresh_produce', '{}', 5, true, true, null),
('Fresh Basil', 'fresh basil', 'fresh_produce', '{}', 5, true, true, null),
('Garlic', 'garlic', 'fresh_produce', '{}', 5, true, true, null),
('Green Beans', 'green beans', 'fresh_produce', '{}', 5, true, true, null),
('Green Onions', 'green onions', 'fresh_produce', '{}', 5, true, true, null),
('Jalapeño', 'jalapeno', 'fresh_produce', '{}', 5, true, true, null),
('Kale', 'kale', 'fresh_produce', '{}', 5, true, true, null),
('Lemons', 'lemons', 'fresh_produce', '{}', 5, true, true, null),
('Lettuce', 'lettuce', 'fresh_produce', '{}', 5, true, true, null),
('Limes', 'limes', 'fresh_produce', '{}', 5, true, true, null),
('Mushrooms', 'mushrooms', 'fresh_produce', '{}', 5, true, true, null),
('Onions', 'onions', 'fresh_produce', '{}', 5, true, true, null),
('Oranges', 'oranges', 'fresh_produce', '{}', 5, true, true, null),
('Parsley', 'parsley', 'fresh_produce', '{}', 5, true, true, null),
('Potatoes', 'potatoes', 'fresh_produce', '{}', 5, true, true, null),
('Red Onions', 'red onions', 'fresh_produce', '{}', 5, true, true, null),
('Spinach', 'spinach', 'fresh_produce', '{}', 5, true, true, null),
('Sweet Potatoes', 'sweet potatoes', 'fresh_produce', '{}', 5, true, true, null),
('Tomatoes', 'tomatoes', 'fresh_produce', '{}', 5, true, true, null),
('Yellow Onions', 'yellow onions', 'fresh_produce', '{}', 5, true, true, null),
('Zucchini', 'zucchini', 'fresh_produce', '{}', 5, true, true, null);

-- Pantry Staples
INSERT INTO global_ingredients (name, normalized_name, category, synonyms, usage_count, is_verified, is_system, created_by) VALUES
('Barbecue Sauce', 'barbecue sauce', 'pantry_staples', '{}', 5, true, true, null),
('Black Beans', 'black beans', 'pantry_staples', '{}', 5, true, true, null),
('Brown Sugar', 'brown sugar', 'pantry_staples', '{}', 5, true, true, null),
('Canned Tomatoes', 'canned tomatoes', 'pantry_staples', '{}', 5, true, true, null),
('Chickpeas', 'chickpeas', 'pantry_staples', '{}', 5, true, true, null),
('Coconut Milk', 'coconut milk', 'pantry_staples', '{}', 5, true, true, null),
('Dark Chocolate', 'dark chocolate', 'pantry_staples', '{"bittersweet chocolate", "semisweet chocolate"}', 10, true, true, null),
('Dijon Mustard', 'dijon mustard', 'pantry_staples', '{}', 5, true, true, null),
('Honey', 'honey', 'pantry_staples', '{}', 5, true, true, null),
('Hot Sauce', 'hot sauce', 'pantry_staples', '{}', 5, true, true, null),
('Ketchup', 'ketchup', 'pantry_staples', '{}', 5, true, true, null),
('Kidney Beans', 'kidney beans', 'pantry_staples', '{}', 5, true, true, null),
('Maple Syrup', 'maple syrup', 'pantry_staples', '{"pure maple syrup", "syrup"}', 10, true, true, null),
('Mayonnaise', 'mayonnaise', 'pantry_staples', '{}', 5, true, true, null),
('Mustard', 'mustard', 'pantry_staples', '{}', 5, true, true, null),
('Peanut Butter', 'peanut butter', 'pantry_staples', '{}', 5, true, true, null),
('Saltines', 'saltines', 'pantry_staples', '{}', 5, true, true, null),
('Soy Sauce', 'soy sauce', 'pantry_staples', '{}', 5, true, true, null),
('Sugar', 'sugar', 'pantry_staples', '{}', 5, true, true, null),
('Tomato Paste', 'tomato paste', 'pantry_staples', '{}', 5, true, true, null),
('Tomato Sauce', 'tomato sauce', 'pantry_staples', '{}', 5, true, true, null),
('Vanilla Extract', 'vanilla extract', 'pantry_staples', '{"vanilla"}', 20, true, true, null),
('White Sugar', 'white sugar', 'pantry_staples', '{}', 5, true, true, null),
('Worcestershire Sauce', 'worcestershire sauce', 'pantry_staples', '{}', 5, true, true, null);

-- Proteins
INSERT INTO global_ingredients (name, normalized_name, category, synonyms, usage_count, is_verified, is_system, created_by) VALUES
('Bacon', 'bacon', 'proteins', '{}', 5, true, true, null),
('Beef Brisket', 'beef brisket', 'proteins', '{}', 5, true, true, null),
('Chicken Breast', 'chicken breast', 'proteins', '{}', 5, true, true, null),
('Chicken Thighs', 'chicken thighs', 'proteins', '{}', 5, true, true, null),
('Ground Beef', 'ground beef', 'proteins', '{}', 5, true, true, null),
('Ground Chicken', 'ground chicken', 'proteins', '{}', 5, true, true, null),
('Ground Pork', 'ground pork', 'proteins', '{}', 5, true, true, null),
('Ground Turkey', 'ground turkey', 'proteins', '{}', 5, true, true, null),
('Ham', 'ham', 'proteins', '{}', 5, true, true, null),
('Lamb Chops', 'lamb chops', 'proteins', '{}', 5, true, true, null),
('Pork Chops', 'pork chops', 'proteins', '{}', 5, true, true, null),
('Pork Tenderloin', 'pork tenderloin', 'proteins', '{}', 5, true, true, null),
('Salmon Fillets', 'salmon fillets', 'proteins', '{}', 5, true, true, null),
('Shrimp', 'shrimp', 'proteins', '{}', 5, true, true, null),
('Sirloin Steak', 'sirloin steak', 'proteins', '{}', 5, true, true, null),
('Tofu', 'tofu', 'proteins', '{}', 5, true, true, null),
('Tuna Steaks', 'tuna steaks', 'proteins', '{}', 5, true, true, null),
('Turkey Breast', 'turkey breast', 'proteins', '{}', 5, true, true, null),
('Whole Chicken', 'whole chicken', 'proteins', '{}', 5, true, true, null);

-- Frozen Items
INSERT INTO global_ingredients (name, normalized_name, category, synonyms, usage_count, is_verified, is_system, created_by) VALUES
('Frozen Berries', 'frozen berries', 'frozen', '{}', 5, true, true, null),
('Frozen Broccoli', 'frozen broccoli', 'frozen', '{}', 5, true, true, null),
('Frozen Corn', 'frozen corn', 'frozen', '{}', 5, true, true, null),
('Frozen Peas', 'frozen peas', 'frozen', '{}', 5, true, true, null),
('Frozen Spinach', 'frozen spinach', 'frozen', '{}', 5, true, true, null),
('Ice Cream', 'ice cream', 'frozen', '{}', 5, true, true, null);

-- Update the timestamps
UPDATE global_ingredients 
SET 
  created_at = now() - interval '30 days',
  updated_at = now() - interval '30 days',
  first_seen_at = now() - interval '30 days',
  last_seen_at = now() - interval '1 day'
WHERE is_system = true;
