import type { GroceryCategories } from '@/lib/types';

export const GROCERY_CATEGORIES: GroceryCategories = {
  proteins: {
    name: 'Proteins',
    icon: '🥩',
    items: [
      'chicken breast',
      'chicken thighs',
      'ground beef',
      'salmon',
      'tuna',
      'eggs',
      'tofu',
      'tempeh',
      'shrimp',
      'pork chops',
      'turkey',
      'beans',
      'lentils',
      'chickpeas',
      'quinoa',
      'nuts',
      'greek yogurt',
      'cottage cheese',
    ],
  },
  vegetables: {
    name: 'Vegetables',
    icon: '🥕',
    items: [
      'onions',
      'garlic',
      'carrots',
      'celery',
      'bell peppers',
      'tomatoes',
      'spinach',
      'broccoli',
      'cauliflower',
      'zucchini',
      'mushrooms',
      'potatoes',
      'sweet potatoes',
      'lettuce',
      'cucumbers',
      'avocados',
      'corn',
      'peas',
    ],
  },
  spices: {
    name: 'Spices & Seasonings',
    icon: '🌶️',
    items: [
      'salt',
      'black pepper',
      'garlic powder',
      'onion powder',
      'paprika',
      'cumin',
      'oregano',
      'basil',
      'thyme',
      'rosemary',
      'bay leaves',
      'chili powder',
      'curry powder',
      'turmeric',
      'ginger',
      'cinnamon',
    ],
  },
  pantry: {
    name: 'Pantry Staples',
    icon: '🏺',
    items: [
      'olive oil',
      'vegetable oil',
      'butter',
      'flour',
      'sugar',
      'brown sugar',
      'rice',
      'pasta',
      'bread',
      'canned tomatoes',
      'chicken stock',
      'vegetable stock',
      'soy sauce',
      'vinegar',
      'honey',
      'vanilla extract',
      'baking powder',
      'baking soda',
    ],
  },
  dairy: {
    name: 'Dairy & Refrigerated',
    icon: '🥛',
    items: [
      'milk',
      'heavy cream',
      'sour cream',
      'cheese',
      'parmesan',
      'mozzarella',
      'cheddar',
      'butter',
      'cream cheese',
      'yogurt',
      'eggs',
    ],
  },
  fruits: {
    name: 'Fruits',
    icon: '🍎',
    items: [
      'lemons',
      'limes',
      'oranges',
      'apples',
      'bananas',
      'berries',
      'grapes',
      'strawberries',
      'blueberries',
      'raspberries',
      'pineapple',
      'mango',
      'peaches',
    ],
  },
} as const;

export const GROCERY_CATEGORY_KEYS = Object.keys(GROCERY_CATEGORIES) as Array<
  keyof typeof GROCERY_CATEGORIES
>;
