/*
 * Chef Isabella's "Kitchen Reality" System Catalog
 *
 * "Group by BEHAVIOR, not biology" - Chef Isabella
 *
 * Comprehensive ingredient catalog organized by where ingredients live in the kitchen
 * and how they are actually used in cooking, not by scientific classification.
 *
 * This catalog serves as the source of truth for system ingredients that get
 * synced to the global_ingredients table with is_system=true.
 */

// Chef Isabella's comprehensive ingredient catalog
export const CHEF_ISABELLA_SYSTEM_CATALOG: Record<string, string[]> = {
  proteins: [
    // ⚡ Quick proteins (15-min cooking)
    'Chicken Breast',
    'Chicken Thighs',
    'Ground Beef',
    'Ground Turkey',
    'Salmon Fillets',
    'Tuna Steaks',
    'Cod Fillets',
    'Shrimp',
    'Scallops',
    'Eggs',
    'Egg Whites',
    'Greek Yogurt',
    'Cottage Cheese',

    // 🔥 Slow-cooking proteins
    'Chicken Wings',
    'Pork Shoulder',
    'Beef Chuck',
    'Lamb Shanks',
    'Whole Chicken',
    'Pork Ribs',
    'Beef Short Ribs',
    'Duck',
    'Beef Stew Meat',
    'Pork Chops',
    'Lamb Chops',
    'Turkey Breast',

    // 🌱 Plant proteins
    'Tofu',
    'Tempeh',
    'Seitan',
    'Black Beans',
    'Kidney Beans',
    'Navy Beans',
    'Pinto Beans',
    'Chickpeas',
    'Lentils',
    'Red Lentils',
    'Green Lentils',
    'Split Peas',
    'Quinoa',
    'Edamame',
    'Almonds',
    'Walnuts',
    'Cashews',
    'Peanuts',
    'Sunflower Seeds',
    'Protein Powder',
    'Nutritional Yeast',
  ],

  fresh_produce: [
    // 📅 Use this week (delicate - high priority)
    'Spinach',
    'Arugula',
    'Lettuce',
    'Mixed Greens',
    'Basil',
    'Cilantro',
    'Parsley',
    'Berries',
    'Strawberries',
    'Raspberries',
    'Blackberries',
    'Blueberries',
    'Avocados',
    'Bananas',
    'Mushrooms',
    'Asparagus',
    'Green Beans',
    'Zucchini',
    'Yellow Squash',
    'Eggplant',

    // 💪 Keeps longer (hardy vegetables & fruits)
    'Onions',
    'Yellow Onions',
    'Red Onions',
    'White Onions',
    'Garlic',
    'Carrots',
    'Celery',
    'Bell Peppers',
    'Red Bell Peppers',
    'Green Bell Peppers',
    'Potatoes',
    'Sweet Potatoes',
    'Broccoli',
    'Cauliflower',
    'Cabbage',
    'Kale',
    'Brussels Sprouts',
    'Cucumbers',
    'Tomatoes',
    'Cherry Tomatoes',
    'Apples',
    'Oranges',
    'Lemons',
    'Limes',
    'Ginger',
    'Beets',
    'Radishes',
    'Turnips',
    'Parsnips',
    'Butternut Squash',
    'Acorn Squash',

    // 🌿 Fresh herbs & aromatics
    'Fresh Rosemary',
    'Fresh Thyme',
    'Fresh Oregano',
    'Fresh Sage',
    'Fresh Mint',
    'Fresh Dill',
    'Chives',
    'Green Onions',
    'Scallions',
    'Jalapeños',
    'Serrano Peppers',
    'Habanero Peppers',
    'Poblano Peppers',
    'Lemongrass',
    'Fresh Ginger Root',
  ],

  flavor_builders: [
    // 👃 Aromatics (the holy trinity + more)
    'Yellow Onions',
    'White Onions',
    'Red Onions',
    'Shallots',
    'Leeks',
    'Garlic',
    'Garlic Cloves',
    'Minced Garlic',
    'Garlic Powder',
    'Fresh Ginger',
    'Ground Ginger',
    'Lemongrass',

    // 🌶️ Essential spices (the flavor makers)
    'Salt',
    'Kosher Salt',
    'Sea Salt',
    'Black Pepper',
    'White Pepper',
    'Peppercorns',
    'Paprika',
    'Smoked Paprika',
    'Cumin',
    'Ground Cumin',
    'Coriander',
    'Turmeric',
    'Garam Masala',
    'Curry Powder',
    'Chili Powder',
    'Cayenne Pepper',
    'Red Pepper Flakes',
    'Cinnamon',
    'Ground Cinnamon',
    'Nutmeg',
    'Cardamom',
    'Star Anise',
    'Fennel Seeds',
    'Mustard Seeds',
    'Celery Seeds',
    'Caraway Seeds',
    'Sesame Seeds',

    // 🍃 Dried herbs
    'Dried Oregano',
    'Dried Basil',
    'Dried Thyme',
    'Dried Rosemary',
    'Dried Sage',
    'Bay Leaves',
    'Marjoram',
    'Tarragon',
    'Herbs de Provence',
    'Italian Seasoning',
    'Everything Bagel Seasoning',
    'Onion Powder',
    'Garlic Powder',
    'Smoked Salt',
    'Old Bay Seasoning',
  ],

  cooking_essentials: [
    // 🫒 Oils & fats (the cooking mediums)
    'Extra Virgin Olive Oil',
    'Olive Oil',
    'Vegetable Oil',
    'Canola Oil',
    'Coconut Oil',
    'Sesame Oil',
    'Avocado Oil',
    'Peanut Oil',
    'Sunflower Oil',
    'Butter',
    'Unsalted Butter',
    'Salted Butter',
    'Ghee',
    'Lard',
    'Shortening',

    // 🍶 Acids & vinegars (the brighteners)
    'Balsamic Vinegar',
    'Apple Cider Vinegar',
    'White Wine Vinegar',
    'Red Wine Vinegar',
    'Rice Vinegar',
    'Champagne Vinegar',
    'Sherry Vinegar',
    'Lemon Juice',
    'Lime Juice',
    'Orange Juice',

    // 🧂 Essential seasonings & liquids
    'Kosher Salt',
    'Sea Salt',
    'Black Peppercorns',
    'Vanilla Extract',
    'Almond Extract',
    'Chicken Stock',
    'Chicken Broth',
    'Vegetable Stock',
    'Vegetable Broth',
    'Beef Stock',
    'Beef Broth',
    'Bone Broth',
    'White Wine',
    'Red Wine',
    'Cooking Sherry',
    'Mirin',
    'Rice Wine',
    'Fish Sauce',
    'Worcestershire Sauce',
    'Liquid Smoke',
  ],

  bakery_grains: [
    // 🍞 Fresh breads & baked goods
    'Sourdough Bread',
    'Whole Wheat Bread',
    'White Bread',
    'Rye Bread',
    'Pumpernickel Bread',
    'Bagels',
    'English Muffins',
    'Croissants',
    'Brioche',
    'Pita Bread',
    'Naan',
    'Tortillas',
    'Corn Tortillas',
    'Flour Tortillas',
    'Dinner Rolls',
    'Hamburger Buns',
    'Hot Dog Buns',
    'Pizza Dough',
    'Pie Crust',
    'Phyllo Dough',

    // 🍝 Pasta & noodles
    'Spaghetti',
    'Penne',
    'Rigatoni',
    'Fettuccine',
    'Linguine',
    'Angel Hair',
    'Lasagna Sheets',
    'Ravioli',
    'Tortellini',
    'Orzo',
    'Macaroni',
    'Egg Noodles',
    'Rice Noodles',
    'Ramen Noodles',
    'Soba Noodles',
    'Udon Noodles',
    'Vermicelli',

    // 🌾 Grains & cereals
    'White Rice',
    'Brown Rice',
    'Jasmine Rice',
    'Basmati Rice',
    'Wild Rice',
    'Arborio Rice',
    'Quinoa',
    'Barley',
    'Farro',
    'Bulgur',
    'Couscous',
    'Oats',
    'Steel Cut Oats',
    'Rolled Oats',
    'Instant Oats',

    // 🥖 Baking essentials
    'All-Purpose Flour',
    'Bread Flour',
    'Whole Wheat Flour',
    'Cake Flour',
    'Almond Flour',
    'Coconut Flour',
    'Cornmeal',
    'Semolina',
    'Baking Powder',
    'Baking Soda',
    'Active Dry Yeast',
    'Instant Yeast',
    'Cornstarch',
    'Arrowroot Powder',
    'Tapioca Starch',
  ],

  dairy_cold: [
    // 🥛 Milk & liquid dairy
    'Whole Milk',
    'Low-Fat Milk',
    '2% Milk',
    'Skim Milk',
    'Buttermilk',
    'Heavy Cream',
    'Heavy Whipping Cream',
    'Half and Half',
    'Light Cream',
    'Whipped Cream',
    'Almond Milk',
    'Oat Milk',
    'Soy Milk',
    'Coconut Milk',
    'Rice Milk',
    'Cashew Milk',

    // 🧀 Cheeses (the flavor enhancers)
    'Parmesan',
    'Parmigiano-Reggiano',
    'Mozzarella',
    'Fresh Mozzarella',
    'Cheddar',
    'Sharp Cheddar',
    'Mild Cheddar',
    'Swiss',
    'Gruyere',
    'Goat Cheese',
    'Feta',
    'Ricotta',
    'Cream Cheese',
    'Mascarpone',
    'Blue Cheese',
    'Gorgonzola',
    'Brie',
    'Camembert',
    'Monterey Jack',
    'Pepper Jack',
    'Provolone',
    'Romano',
    'Asiago',

    // 🥚 Eggs & spreads
    'Large Eggs',
    'Extra Large Eggs',
    'Egg Whites',
    'Egg Yolks',
    'Unsalted Butter',
    'Salted Butter',
    'European Butter',
    'Greek Yogurt',
    'Plain Yogurt',
    'Vanilla Yogurt',
    'Sour Cream',
    'Crème Fraîche',
    'Labneh',
    'Kefir',
  ],

  pantry_staples: [
    // 🥫 Canned goods (the reliable backups)
    'Canned Tomatoes',
    'Crushed Tomatoes',
    'Diced Tomatoes',
    'Whole Tomatoes',
    'Tomato Paste',
    'Tomato Sauce',
    'Marinara Sauce',
    'Pizza Sauce',
    'Canned Beans',
    'Black Beans',
    'Kidney Beans',
    'Pinto Beans',
    'Chickpeas',
    'White Beans',
    'Navy Beans',
    'Refried Beans',
    'Canned Corn',
    'Canned Peas',
    'Canned Carrots',
    'Canned Green Beans',
    'Canned Tuna',
    'Canned Salmon',
    'Canned Sardines',
    'Canned Chicken',
    'Chicken Broth',
    'Vegetable Broth',
    'Beef Broth',
    'Coconut Milk',
    'Canned Pumpkin',
    'Canned Sweet Potato',
    'Canned Peaches',
    'Canned Pears',

    // 🍯 Condiments & flavor enhancers
    'Ketchup',
    'Mustard',
    'Dijon Mustard',
    'Whole Grain Mustard',
    'Mayonnaise',
    'Soy Sauce',
    'Low Sodium Soy Sauce',
    'Tamari',
    'Sriracha',
    'Hot Sauce',
    'BBQ Sauce',
    'Teriyaki Sauce',
    'Hoisin Sauce',
    'Oyster Sauce',
    'Peanut Butter',
    'Almond Butter',
    'Sunflower Seed Butter',
    'Tahini',
    'Jam',
    'Strawberry Jam',
    'Grape Jelly',
    'Orange Marmalade',
    'Nutella',
    'Honey',
    'Maple Syrup',
    'Agave Nectar',
    'Brown Sugar',
    'White Sugar',
    'Powdered Sugar',
    'Vanilla Extract',

    // 📦 Dry goods & snacks
    'Crackers',
    'Saltines',
    'Graham Crackers',
    'Breadcrumbs',
    'Panko',
    'Cereal',
    'Granola',
    'Oatmeal',
    'Instant Oatmeal',
    'Popcorn',
    'Nuts',
    'Mixed Nuts',
    'Peanuts',
    'Almonds',
    'Walnuts',
    'Pecans',
    'Raisins',
    'Dried Cranberries',
    'Dates',
    'Dried Fruit',
    'Soup',
    'Chicken Noodle Soup',
    'Tomato Soup',
    'Vegetable Soup',
    'Pasta Sauce',
    'Alfredo Sauce',
    'Pesto',
    'Salsa',
    'Guacamole',
    'Olives',
    'Kalamata Olives',
    'Green Olives',
    'Pickles',
    'Capers',
  ],

  frozen: [
    // 🥦 Frozen produce (the time savers)
    'Frozen Broccoli',
    'Frozen Spinach',
    'Frozen Peas',
    'Frozen Corn',
    'Frozen Green Beans',
    'Frozen Carrots',
    'Frozen Mixed Vegetables',
    'Frozen Cauliflower',
    'Frozen Brussels Sprouts',
    'Frozen Edamame',
    'Frozen Berries',
    'Frozen Strawberries',
    'Frozen Blueberries',
    'Frozen Raspberries',
    'Frozen Mango',
    'Frozen Pineapple',
    'Frozen Peaches',
    'Frozen Cherries',

    // 🍕 Frozen meals & convenience foods
    'Frozen Pizza',
    'Frozen Burritos',
    'Frozen Dumplings',
    'Frozen Pot Stickers',
    'Frozen Ravioli',
    'Frozen Lasagna',
    'Frozen Stir Fry',
    'Frozen Waffles',
    'Frozen Pancakes',
    'Frozen French Toast',
    'Frozen Hash Browns',
    'Frozen French Fries',
    'Frozen Onion Rings',
    'Frozen Chicken Nuggets',
    'Frozen Fish Sticks',
    'Frozen Meatballs',
    'Frozen Pierogies',

    // 🍦 Frozen treats & desserts
    'Ice Cream',
    'Vanilla Ice Cream',
    'Chocolate Ice Cream',
    'Frozen Yogurt',
    'Sorbet',
    'Sherbet',
    'Popsicles',
    'Ice Cream Bars',
    'Frozen Fruit Bars',
    'Ice Cubes',
    'Frozen Whipped Topping',
  ],
};

// Helper function for sync script
export function getAllSystemIngredients(): Array<{
  name: string;
  category: string;
}> {
  const result: Array<{ name: string; category: string }> = [];

  Object.entries(CHEF_ISABELLA_SYSTEM_CATALOG).forEach(([category, items]) => {
    items.forEach((item) => {
      result.push({ name: item, category });
    });
  });

  return result;
}

// Category metadata for UI components
export const CATEGORY_METADATA = {
  proteins: {
    name: 'Proteins',
    subtitle: 'The Main Event',
    icon: '🥩',
    color: '#8B4513',
    description:
      'Meat, fish, eggs, beans, nuts - what determines your cooking method',
    subcues: {
      quick: '⚡ Quick (15-min)',
      slow: '🔥 Slow-cooking',
      plant: '🌱 Plant-based',
    },
  },
  fresh_produce: {
    name: 'Fresh Produce',
    subtitle: 'The Perishables',
    icon: '🥬',
    color: '#228B22',
    description: 'Fresh vegetables, fruits, herbs - use first, shop weekly',
    subcues: {
      delicate: '📅 Use this week',
      hardy: '💪 Keeps longer',
      herbs: '🌿 Fresh herbs',
    },
  },
  flavor_builders: {
    name: 'Flavor Builders',
    subtitle: 'The Magic Makers',
    icon: '🧄',
    color: '#FF8C00',
    description: 'Aromatics, spices, herbs - your recipe foundations',
    subcues: {
      aromatics: '👃 Aromatics',
      spices: '🌶️ Spices',
      herbs: '🍃 Dried herbs',
    },
  },
  cooking_essentials: {
    name: 'Cooking Essentials',
    subtitle: 'The Workhorses',
    icon: '🫒',
    color: '#4682B4',
    description: 'Oils, vinegars, stocks - tools you use in every recipe',
    subcues: {
      oils: '🫒 Oils & fats',
      acids: '🍶 Acids & vinegars',
      seasonings: '🧂 Seasonings',
    },
  },
  bakery_grains: {
    name: 'Bakery & Grains',
    subtitle: 'The Carb Corner',
    icon: '🍞',
    color: '#D2691E',
    description: 'Breads, pasta, rice, flour - your satisfying foundations',
    subcues: {
      breads: '🍞 Fresh breads',
      pasta: '🍝 Pasta & grains',
      baking: '🌾 Baking supplies',
    },
  },
  dairy_cold: {
    name: 'Dairy & Cold',
    subtitle: 'The Refrigerated',
    icon: '🥛',
    color: '#87CEEB',
    description: 'Milk, cheese, eggs, butter - everything from the fridge',
    subcues: {
      liquids: '🥛 Liquids',
      cheeses: '🧀 Cheeses',
      eggs: '🥚 Eggs & butter',
    },
  },
  pantry_staples: {
    name: 'Pantry Staples',
    subtitle: 'The Reliable Backups',
    icon: '🏺',
    color: '#9370DB',
    description: 'Canned, jarred, dry goods - your emergency cooking supplies',
    subcues: {
      canned: '🥫 Canned goods',
      condiments: '🍯 Condiments',
      dry: '📦 Dry goods',
    },
  },
  frozen: {
    name: 'Frozen',
    subtitle: 'The Time Savers',
    icon: '❄️',
    color: '#F0F8FF',
    description: 'Everything from the freezer - convenience and preservation',
    subcues: {
      produce: '🥦 Frozen produce',
      meals: '🍕 Frozen meals',
      treats: '🍦 Frozen treats',
    },
  },
};

// Decision tree for intuitive navigation
export const COOKING_DECISION_TREE = {
  "What's my main protein?": 'proteins',
  'What fresh things do I have?': 'fresh_produce',
  'How do I make this taste good?': 'flavor_builders',
  'What do I cook it with?': 'cooking_essentials',
  'What goes alongside?': ['bakery_grains', 'dairy_cold'],
  'What backup do I have?': ['pantry_staples', 'frozen'],
};

// Get ingredient count by category for reporting
export function getCategoryStats() {
  const stats: Record<string, number> = {};
  let total = 0;

  Object.entries(CHEF_ISABELLA_SYSTEM_CATALOG).forEach(([category, items]) => {
    stats[category] = items.length;
    total += items.length;
  });

  return { stats, total };
}
