import { CuisineStaplesData } from '../cuisine-staples/types';

export const africanCuisines: Record<string, CuisineStaplesData> = {
  nigerian: {
    cuisine: 'Nigerian',
    description:
      'Essential ingredients for authentic Nigerian cooking with jollof rice and egusi soup',
    subStyles: [
      'Lagos',
      'Abuja',
      'Kano',
      'Traditional Nigerian',
      'Modern Nigerian',
    ],
    staples: [
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Nigerian meals',
        usage: 'Jollof rice, main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of Nigerian meals',
      },
      {
        ingredient: 'palm oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential cooking oil for Nigerian cuisine',
        usage: 'Jollof rice, egusi soup, cooking, marinades, finishing',
        culturalContext: 'Palm oil is the soul of Nigerian cuisine',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Nigerian cooking',
        usage: 'Jollof rice, egusi soup, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Nigerian flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Nigerian cooking',
        usage: 'Jollof rice, egusi soup, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Nigerian flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Nigerian dishes',
        usage: 'Jollof rice, egusi soup, stews, main dishes, sauces',
        culturalContext: 'Essential for authentic Nigerian dishes',
      },
      {
        ingredient: 'pepper',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential heat for Nigerian cuisine',
        usage: 'Jollof rice, egusi soup, stews, marinades, sauces',
        culturalContext: 'Nigerian cuisine is known for its heat',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Nigerian cooking',
        usage: 'Jollof rice, egusi soup, marinades, teas, health benefits',
        culturalContext:
          'Medicinal and culinary importance in Nigerian culture',
      },
      {
        ingredient: 'crayfish',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential umami for Nigerian cuisine',
        usage: 'Jollof rice, egusi soup, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Nigerian umami flavor',
      },
      {
        ingredient: 'stock cubes',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasoning for Nigerian cuisine',
        usage: 'Jollof rice, egusi soup, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Nigerian flavor',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Nigerian cuisine',
        usage:
          'Jollof rice, egusi soup, stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Essential for authentic Nigerian dishes',
      },
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Nigerian cuisine',
        usage:
          'Jollof rice, egusi soup, main dishes, stews, soups, side dishes',
        culturalContext: 'Essential for Nigerian main dishes',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Nigerian cuisine',
        usage:
          'Jollof rice, egusi soup, main dishes, soups, side dishes, traditional',
        culturalContext: 'Essential for Nigerian main dishes',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Nigerian ingredients',
        usage:
          'Jollof rice, egusi soup, garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Important in Nigerian cuisine',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Nigerian ingredients',
        usage:
          'Jollof rice, egusi soup, marinades, stews, main dishes, everything',
        culturalContext: 'Important in Nigerian cuisine',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Nigerian ingredients',
        usage:
          'Jollof rice, egusi soup, desserts, main dishes, snacks, side dishes',
        culturalContext: 'Important in Nigerian cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Nigerian ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Nigerian wine is important in the cuisine',
      },
    ],
  },
  south_african: {
    cuisine: 'South African',
    description:
      'Essential ingredients for authentic South African cooking with braai and bobotie',
    subStyles: [
      'Cape Town',
      'Johannesburg',
      'Durban',
      'Traditional South African',
      'Modern South African',
    ],
    staples: [
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for South African cuisine',
        usage: 'Braai, bobotie, main dishes, stews, soups, side dishes',
        culturalContext: 'Meat is the soul of South African cuisine',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for South African cooking',
        usage: 'Braai, bobotie, stews, main dishes, aromatics',
        culturalContext: 'Foundation of South African flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for South African cooking',
        usage: 'Braai, bobotie, marinades, sauces, main dishes',
        culturalContext: 'Foundation of South African flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for South African dishes',
        usage: 'Braai, bobotie, stews, main dishes, sauces',
        culturalContext: 'Essential for authentic South African dishes',
      },
      {
        ingredient: 'potatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for South African cuisine',
        usage: 'Braai, bobotie, main dishes, side dishes, soups',
        culturalContext: 'Potatoes are essential for South African braai',
      },
      {
        ingredient: 'curry powder',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for South African cuisine',
        usage: 'Bobotie, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic South African bobotie',
      },
      {
        ingredient: 'turmeric',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for South African cuisine',
        usage: 'Bobotie, stews, marinades, main dishes',
        culturalContext:
          'Essential for authentic South African color and flavor',
      },
      {
        ingredient: 'eggs',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for South African cuisine',
        usage: 'Bobotie, baking, main dishes, desserts, side dishes',
        culturalContext: 'Essential for South African bobotie and baking',
      },
      {
        ingredient: 'milk',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for South African cuisine',
        usage: 'Bobotie, desserts, beverages, main dishes',
        culturalContext: 'Essential for South African bobotie and desserts',
      },
      {
        ingredient: 'bread',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential staple for South African cuisine',
        usage: 'Braai, bobotie, main dishes, side dishes, snacks',
        culturalContext: 'Essential for South African braai and main dishes',
      },
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for South African meals',
        usage: 'Bobotie, main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of South African meals',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for South African cuisine',
        usage: 'Braai, bobotie, stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Essential for authentic South African dishes',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular South African ingredients',
        usage: 'Braai, bobotie, garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Important in South African cuisine',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular South African ingredients',
        usage: 'Braai, bobotie, marinades, stews, main dishes, everything',
        culturalContext: 'Important in South African cuisine',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular South African ingredients',
        usage: 'Bobotie, desserts, main dishes, snacks, side dishes',
        culturalContext: 'Important in South African cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular South African ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'South African wine is world-famous',
      },
    ],
  },
  egyptian: {
    cuisine: 'Egyptian',
    description:
      'Essential ingredients for authentic Egyptian cooking with koshari and ful medames',
    subStyles: [
      'Cairo',
      'Alexandria',
      'Luxor',
      'Traditional Egyptian',
      'Modern Egyptian',
    ],
    staples: [
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Egyptian meals',
        usage: 'Koshari, main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of Egyptian meals',
      },
      {
        ingredient: 'lentils',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential legume for Egyptian cuisine',
        usage: 'Koshari, ful medames, stews, main dishes, side dishes',
        culturalContext: 'Lentils are the soul of Egyptian cuisine',
      },
      {
        ingredient: 'chickpeas',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential legume for Egyptian cuisine',
        usage: 'Koshari, ful medames, stews, main dishes, side dishes',
        culturalContext: 'Chickpeas are essential for Egyptian koshari',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Egyptian cooking',
        usage: 'Koshari, ful medames, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Egyptian flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Egyptian cooking',
        usage: 'Koshari, ful medames, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Egyptian flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Egyptian dishes',
        usage: 'Koshari, ful medames, stews, main dishes, sauces',
        culturalContext: 'Essential for authentic Egyptian dishes',
      },
      {
        ingredient: 'lemon',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for Egyptian cuisine',
        usage: 'Koshari, ful medames, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Egyptian brightness',
      },
      {
        ingredient: 'olive oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential cooking oil for Egyptian cuisine',
        usage: 'Koshari, ful medames, cooking, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Egyptian cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Egyptian cuisine',
        usage:
          'Koshari, ful medames, garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Cannot make authentic Egyptian food without herbs',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Egyptian cuisine',
        usage:
          'Koshari, ful medames, marinades, stews, main dishes, everything',
        culturalContext: 'Essential for authentic Egyptian flavor',
      },
      {
        ingredient: 'bread',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential staple for Egyptian cuisine',
        usage: 'Koshari, ful medames, main dishes, side dishes, snacks',
        culturalContext: 'Essential for Egyptian koshari and ful medames',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Egyptian cuisine',
        usage:
          'Koshari, ful medames, stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Essential for authentic Egyptian dishes',
      },
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Egyptian protein',
        usage: 'Koshari, ful medames, main dishes, stews, soups, side dishes',
        culturalContext: 'Important in Egyptian cuisine',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Egyptian protein',
        usage:
          'Koshari, ful medames, main dishes, soups, side dishes, traditional',
        culturalContext: 'Important in Egyptian cuisine',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Egyptian ingredients',
        usage:
          'Koshari, ful medames, desserts, main dishes, snacks, side dishes',
        culturalContext: 'Important in Egyptian cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Egyptian ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Egyptian wine is important in the cuisine',
      },
    ],
  },
  ethiopian: {
    cuisine: 'Ethiopian',
    description:
      'Essential ingredients for authentic Ethiopian cooking with berbere spice and injera bread',
    subStyles: [
      'Addis Ababa',
      'Gondar',
      'Harar',
      'Traditional Ethiopian',
      'Modern Ethiopian',
    ],
    staples: [
      {
        ingredient: 'berbere',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice blend for Ethiopian cuisine',
        usage: 'Wat, stews, marinades, main dishes',
        culturalContext: 'Berbere is the soul of Ethiopian cuisine',
      },
      {
        ingredient: 'teff flour',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential grain for Ethiopian injera',
        usage: 'Injera bread, main dishes, side dishes',
        culturalContext: 'Teff flour is essential for Ethiopian injera',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Ethiopian cooking',
        usage: 'Wat, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Ethiopian flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Ethiopian cooking',
        usage: 'Wat, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Ethiopian flavor building',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Ethiopian cooking',
        usage: 'Wat, marinades, sauces, main dishes',
        culturalContext: 'Essential for authentic Ethiopian flavor',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Ethiopian dishes',
        usage: 'Wat, stews, main dishes, sauces',
        culturalContext: 'Essential for authentic Ethiopian dishes',
      },
      {
        ingredient: 'red lentils',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential legume for Ethiopian cuisine',
        usage: 'Wat, stews, main dishes, side dishes',
        culturalContext: 'Red lentils are the soul of Ethiopian wat',
      },
      {
        ingredient: 'chickpeas',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential legume for Ethiopian cuisine',
        usage: 'Wat, stews, main dishes, side dishes',
        culturalContext: 'Chickpeas are essential for Ethiopian wat',
      },
      {
        ingredient: 'lamb',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Ethiopian cuisine',
        usage: 'Wat, stews, main dishes, side dishes',
        culturalContext: 'Lamb is the soul of Ethiopian wat',
      },
      {
        ingredient: 'chicken',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Ethiopian cuisine',
        usage: 'Wat, stews, main dishes, side dishes',
        culturalContext: 'Chicken is essential for Ethiopian wat',
      },
      {
        ingredient: 'cardamom',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Ethiopian cuisine',
        usage: 'Berbere, wat, stews, main dishes',
        culturalContext: 'Cardamom is essential for Ethiopian berbere',
      },
      {
        ingredient: 'cinnamon',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Ethiopian cuisine',
        usage: 'Berbere, wat, stews, main dishes',
        culturalContext: 'Cinnamon is essential for Ethiopian berbere',
      },
      {
        ingredient: 'cloves',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Ethiopian cuisine',
        usage: 'Berbere, wat, stews, main dishes',
        culturalContext: 'Cloves are essential for Ethiopian berbere',
      },
      {
        ingredient: 'cumin',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Ethiopian cuisine',
        usage: 'Berbere, wat, stews, main dishes',
        culturalContext: 'Cumin is essential for Ethiopian berbere',
      },
      {
        ingredient: 'paprika',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Ethiopian cuisine',
        usage: 'Berbere, wat, stews, main dishes',
        culturalContext: 'Paprika is essential for Ethiopian berbere',
      },
      {
        ingredient: 'salt',
        category: 'seasonings',
        priority: 'essential',
        reason: 'Basic seasoning',
        usage: 'All cooking',
        culturalContext: 'Essential for all Ethiopian cooking',
      },
    ],
  },
  moroccan: {
    cuisine: 'Moroccan',
    description:
      'Essential ingredients for authentic Moroccan cooking with couscous and tagines',
    subStyles: [
      'Casablanca',
      'Marrakech',
      'Fez',
      'Traditional Moroccan',
      'Modern Moroccan',
    ],
    staples: [
      {
        ingredient: 'couscous',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential grain for Moroccan cuisine',
        usage: 'Couscous, main dishes, side dishes, everyday meals',
        culturalContext: 'Couscous is the soul of Moroccan cuisine',
      },
      {
        ingredient: 'olive oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential cooking oil for Moroccan cuisine',
        usage: 'Tagine, cooking, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Moroccan cooking',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Moroccan cooking',
        usage: 'Tagine, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Moroccan flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Moroccan cooking',
        usage: 'Tagine, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Moroccan flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Moroccan dishes',
        usage: 'Tagine, stews, main dishes, sauces',
        culturalContext: 'Essential for authentic Moroccan dishes',
      },
      {
        ingredient: 'bell peppers',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Moroccan cuisine',
        usage: 'Tagine, stews, main dishes, side dishes',
        culturalContext: 'Bell peppers are essential for Moroccan flavor',
      },
      {
        ingredient: 'carrots',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Moroccan cuisine',
        usage: 'Tagine, stews, main dishes, side dishes',
        culturalContext: 'Carrots are essential for Moroccan tagine',
      },
      {
        ingredient: 'potatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Moroccan cuisine',
        usage: 'Tagine, stews, main dishes, side dishes',
        culturalContext: 'Potatoes are essential for Moroccan tagine',
      },
      {
        ingredient: 'lamb',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Moroccan cuisine',
        usage: 'Tagine, stews, main dishes, side dishes',
        culturalContext: 'Lamb is the soul of Moroccan tagine',
      },
      {
        ingredient: 'chicken',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Moroccan cuisine',
        usage: 'Tagine, stews, main dishes, side dishes',
        culturalContext: 'Chicken is essential for Moroccan tagine',
      },
      {
        ingredient: 'chickpeas',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential legume for Moroccan cuisine',
        usage: 'Tagine, stews, main dishes, side dishes',
        culturalContext: 'Chickpeas are essential for Moroccan tagine',
      },
      {
        ingredient: 'apricots',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential fruit for Moroccan cuisine',
        usage: 'Tagine, stews, main dishes, side dishes',
        culturalContext: 'Apricots are essential for Moroccan tagine',
      },
      {
        ingredient: 'prunes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential fruit for Moroccan cuisine',
        usage: 'Tagine, stews, main dishes, side dishes',
        culturalContext: 'Prunes are essential for Moroccan tagine',
      },
      {
        ingredient: 'cinnamon',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Moroccan cuisine',
        usage: 'Tagine, stews, main dishes, desserts',
        culturalContext: 'Cinnamon is essential for Moroccan flavor',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Moroccan cooking',
        usage: 'Tagine, marinades, sauces, main dishes',
        culturalContext: 'Essential for authentic Moroccan flavor',
      },
      {
        ingredient: 'saffron',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Moroccan cuisine',
        usage: 'Tagine, couscous, main dishes, side dishes',
        culturalContext: 'Saffron is essential for Moroccan flavor',
      },
    ],
  },
};
