import { CuisineStaplesData } from '../cuisine-staples';

export const americanCuisines: Record<string, CuisineStaplesData> = {
  canadian: {
    cuisine: 'Canadian',
    description:
      'Essential ingredients for authentic Canadian cooking with poutine and maple syrup',
    subStyles: [
      'Toronto',
      'Vancouver',
      'Montreal',
      'Traditional Canadian',
      'Modern Canadian',
    ],
    staples: [
      {
        ingredient: 'potatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Canadian cuisine',
        usage: 'Poutine, main dishes, side dishes, soups',
        culturalContext: 'Potatoes are the soul of Canadian cuisine',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Canadian cuisine',
        usage: 'Poutine, main dishes, snacks, side dishes',
        culturalContext: 'Essential for authentic Canadian poutine',
      },
      {
        ingredient: 'maple syrup',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential sweetener for Canadian cuisine',
        usage: 'Desserts, marinades, main dishes, beverages',
        culturalContext: 'Maple syrup is the soul of Canadian cuisine',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Canadian cooking',
        usage: 'Poutine, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Canadian flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Canadian cooking',
        usage: 'Poutine, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Canadian flavor building',
      },
      {
        ingredient: 'butter',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential cooking fat for Canadian cuisine',
        usage: 'Cooking, baking, sauces, finishing',
        culturalContext: 'Essential for authentic Canadian richness',
      },
      {
        ingredient: 'flour',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for Canadian baking and cooking',
        usage: 'Bread, pastries, dumplings, thickening',
        culturalContext: 'Canadian flour is essential for authentic baking',
      },
      {
        ingredient: 'eggs',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Canadian cuisine',
        usage: 'Baking, main dishes, desserts, side dishes',
        culturalContext: 'Essential for Canadian baking and main dishes',
      },
      {
        ingredient: 'milk',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Canadian cuisine',
        usage: 'Poutine, desserts, beverages, main dishes',
        culturalContext: 'Essential for Canadian poutine and desserts',
      },
      {
        ingredient: 'sugar',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential sweetener for Canadian cuisine',
        usage: 'Desserts, baking, main dishes, beverages',
        culturalContext: 'Essential for Canadian desserts and baking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Canadian cuisine',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Cannot make authentic Canadian food without herbs',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Canadian cuisine',
        usage: 'Marinades, stews, main dishes, everything',
        culturalContext: 'Essential for authentic Canadian flavor',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Canadian ingredients',
        usage: 'Stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Important in Canadian cuisine',
      },
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Canadian protein',
        usage: 'Main dishes, stews, soups, side dishes',
        culturalContext: 'Important in Canadian cuisine',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Canadian protein',
        usage: 'Main dishes, soups, side dishes, traditional',
        culturalContext: 'Important in Canadian cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Canadian ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Canadian wine is important in the cuisine',
      },
    ],
  },
  argentinian: {
    cuisine: 'Argentinian',
    description:
      'Essential ingredients for authentic Argentinian cooking with asado and empanadas',
    subStyles: [
      'Buenos Aires',
      'Córdoba',
      'Mendoza',
      'Traditional Argentinian',
      'Modern Argentinian',
    ],
    staples: [
      {
        ingredient: 'beef',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Argentinian cuisine',
        usage: 'Asado, main dishes, stews, side dishes',
        culturalContext: 'Beef is the soul of Argentinian cuisine',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Argentinian cooking',
        usage: 'Asado, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Argentinian flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Argentinian cooking',
        usage: 'Asado, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Argentinian flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Argentinian dishes',
        usage: 'Asado, stews, main dishes, sauces',
        culturalContext: 'Essential for authentic Argentinian dishes',
      },
      {
        ingredient: 'potatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Argentinian cuisine',
        usage: 'Asado, main dishes, side dishes, soups',
        culturalContext: 'Potatoes are essential for Argentinian asado',
      },
      {
        ingredient: 'flour',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for Argentinian baking and cooking',
        usage: 'Empanadas, bread, pastries, dumplings',
        culturalContext: 'Argentinian flour is essential for authentic baking',
      },
      {
        ingredient: 'eggs',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Argentinian cuisine',
        usage: 'Empanadas, baking, main dishes, desserts',
        culturalContext: 'Essential for Argentinian empanadas and baking',
      },
      {
        ingredient: 'butter',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential cooking fat for Argentinian cuisine',
        usage: 'Cooking, baking, sauces, finishing',
        culturalContext: 'Essential for authentic Argentinian richness',
      },
      {
        ingredient: 'olive oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential cooking oil for Argentinian cuisine',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Argentinian cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Argentinian cuisine',
        usage: 'Asado, garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Cannot make authentic Argentinian food without herbs',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Argentinian cuisine',
        usage: 'Asado, marinades, stews, main dishes, everything',
        culturalContext: 'Essential for authentic Argentinian flavor',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential beverage for Argentinian cuisine',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Argentinian wine is world-famous',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Argentinian ingredients',
        usage: 'Stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Important in Argentinian cuisine',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'recommended',
        reason: 'Popular Argentinian ingredient',
        usage: 'Empanadas, main dishes, snacks, side dishes',
        culturalContext: 'Important in Argentinian cuisine',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Argentinian protein',
        usage: 'Main dishes, soups, side dishes, traditional',
        culturalContext: 'Important in Argentinian cuisine',
      },
      {
        ingredient: 'chicken',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Argentinian protein',
        usage: 'Main dishes, stews, soups, side dishes',
        culturalContext: 'Important in Argentinian cuisine',
      },
    ],
  },
  chilean: {
    cuisine: 'Chilean',
    description:
      'Essential ingredients for authentic Chilean cooking with ceviche and Chilean wine',
    subStyles: [
      'Santiago',
      'Valparaíso',
      'Concepción',
      'Traditional Chilean',
      'Modern Chilean',
    ],
    staples: [
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Chilean cuisine',
        usage: 'Ceviche, main dishes, soups, side dishes',
        culturalContext: 'Fish is the soul of Chilean cuisine',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Chilean cooking',
        usage: 'Ceviche, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Chilean flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Chilean cooking',
        usage: 'Ceviche, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Chilean flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Chilean dishes',
        usage: 'Ceviche, stews, main dishes, sauces',
        culturalContext: 'Essential for authentic Chilean dishes',
      },
      {
        ingredient: 'lemon',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for Chilean cuisine',
        usage: 'Ceviche, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Chilean ceviche',
      },
      {
        ingredient: 'lime',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for Chilean cuisine',
        usage: 'Ceviche, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Chilean ceviche',
      },
      {
        ingredient: 'olive oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential cooking oil for Chilean cuisine',
        usage: 'Ceviche, cooking, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Chilean cooking',
      },
      {
        ingredient: 'potatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Chilean cuisine',
        usage: 'Ceviche, main dishes, side dishes, soups',
        culturalContext: 'Potatoes are essential for Chilean ceviche',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Chilean cuisine',
        usage: 'Ceviche, garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Cannot make authentic Chilean food without herbs',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Chilean cuisine',
        usage: 'Ceviche, marinades, stews, main dishes, everything',
        culturalContext: 'Essential for authentic Chilean flavor',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential beverage for Chilean cuisine',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Chilean wine is world-famous',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Chilean cuisine',
        usage: 'Ceviche, stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Essential for authentic Chilean dishes',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'recommended',
        reason: 'Popular Chilean ingredient',
        usage: 'Main dishes, snacks, side dishes, traditional',
        culturalContext: 'Important in Chilean cuisine',
      },
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Chilean protein',
        usage: 'Main dishes, stews, soups, side dishes',
        culturalContext: 'Important in Chilean cuisine',
      },
      {
        ingredient: 'chicken',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Chilean protein',
        usage: 'Main dishes, stews, soups, side dishes',
        culturalContext: 'Important in Chilean cuisine',
      },
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Chilean grain',
        usage: 'Main dishes, side dishes, everyday meals',
        culturalContext: 'Important in Chilean cuisine',
      },
    ],
  },
};
