import { CuisineStaplesData } from '../cuisine-staples/types';
import { thai } from './asian/thai';
import { korean } from './asian/korean';
import { japanese } from './asian/japanese';
import { indian } from './asian/indian';
import { chinese } from './asian/chinese';
import { vietnamese } from './asian/vietnamese';
import { indonesian } from './asian/indonesian';
import { malaysian } from './asian/malaysian';
import { singaporean } from './asian/singaporean';
import { filipino } from './asian/filipino';
import {
  thaiCentral,
  thaiNorthern,
  thaiSouthern,
  thaiIsaan,
} from './asian/thai-subregions';

export const asianCuisines: Record<string, CuisineStaplesData> = {
  asian: {
    cuisine: 'Asian',
    description:
      'General Asian cuisine staples covering common ingredients across Asian cooking traditions',
    staples: [
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Asian meals',
        usage: 'Main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of Asian meals',
      },
      {
        ingredient: 'soy sauce',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential umami for Asian cuisine',
        usage: 'Marinades, sauces, main dishes, seasoning',
        culturalContext: 'Essential for authentic Asian umami',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Asian cooking',
        usage: 'Marinades, sauces, main dishes, aromatics',
        culturalContext: 'Foundation of Asian flavor building',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Asian cooking',
        usage: 'Marinades, sauces, main dishes, aromatics',
        culturalContext: 'Essential for authentic Asian flavor',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Asian cooking',
        usage: 'Stir-fries, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Asian flavor building',
      },
      {
        ingredient: 'sesame oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential oil for Asian cuisine',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Asian flavor',
      },
      {
        ingredient: 'chili peppers',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential heat for Asian cuisine',
        usage: 'Stir-fries, marinades, sauces, main dishes',
        culturalContext: 'Essential for authentic Asian heat',
      },
      {
        ingredient: 'cilantro',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Asian cuisine',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Essential for authentic Asian freshness',
      },
      {
        ingredient: 'lime',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for Asian cuisine',
        usage: 'Marinades, dressings, finishing, drinks',
        culturalContext: 'Essential for authentic Asian brightness',
      },
      {
        ingredient: 'coconut milk',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential creaminess for Asian cuisine',
        usage: 'Curries, stews, rice dishes, main dishes',
        culturalContext: 'Essential for authentic Asian curries',
      },
      {
        ingredient: 'fish sauce',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential umami for Asian cuisine',
        usage: 'Marinades, sauces, main dishes, seasoning',
        culturalContext: 'Essential for authentic Asian umami',
      },
      {
        ingredient: 'oyster sauce',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential umami for Asian cuisine',
        usage: 'Stir-fries, marinades, sauces, main dishes',
        culturalContext: 'Essential for authentic Asian umami',
      },
      {
        ingredient: 'rice vinegar',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential acid for Asian cuisine',
        usage: 'Dressings, marinades, sauces, finishing',
        culturalContext: 'Essential for authentic Asian acidity',
      },
      {
        ingredient: 'star anise',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Asian cuisine',
        usage: 'Stews, marinades, main dishes, aromatics',
        culturalContext: 'Essential for authentic Asian aromatics',
      },
      {
        ingredient: 'cinnamon',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Asian cuisine',
        usage: 'Stews, marinades, main dishes, desserts',
        culturalContext: 'Essential for authentic Asian warmth',
      },
      {
        ingredient: 'cloves',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Asian cuisine',
        usage: 'Stews, marinades, main dishes, aromatics',
        culturalContext: 'Essential for authentic Asian aromatics',
      },
    ],
  },
  indonesian,
  /* moved to asian/indonesian.ts */
  /* indonesian_legacy: {
    cuisine: 'Indonesian',
    description:
      'Essential ingredients for authentic Indonesian cooking with nasi goreng and rendang',
    subStyles: [
      'Jakarta',
      'Bali',
      'Surabaya',
      'Traditional Indonesian',
      'Modern Indonesian',
    ],
    staples: [
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Indonesian meals',
        usage: 'Nasi goreng, main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of Indonesian meals',
      },
      {
        ingredient: 'coconut milk',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for Indonesian curries and stews',
        usage: 'Curries, stews, desserts, beverages',
        culturalContext: 'Essential for authentic Indonesian creaminess',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Indonesian cooking',
        usage: 'Nasi goreng, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Indonesian flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Indonesian cooking',
        usage: 'Nasi goreng, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Indonesian flavor building',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Indonesian dishes',
        usage: 'Nasi goreng, marinades, teas, health benefits',
        culturalContext:
          'Medicinal and culinary importance in Indonesian culture',
      },
      {
        ingredient: 'chili peppers',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential heat for Indonesian cuisine',
        usage: 'Nasi goreng, stews, marinades, sauces',
        culturalContext: 'Indonesian cuisine is known for its heat',
      },
      {
        ingredient: 'lemongrass',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Indonesian cuisine',
        usage: 'Curries, stews, marinades, aromatics',
        culturalContext:
          'Cannot make authentic Indonesian food without lemongrass',
      },
      {
        ingredient: 'galangal',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential root for Indonesian cuisine',
        usage: 'Curries, stews, marinades, aromatics',
        culturalContext: 'Essential for authentic Indonesian flavor',
      },
      {
        ingredient: 'turmeric',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Indonesian cuisine',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Indonesian color and flavor',
      },
      {
        ingredient: 'coriander',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Indonesian cuisine',
        usage: 'Garnishes, marinades, main dishes, salads',
        culturalContext:
          'Cannot make authentic Indonesian food without coriander',
      },
      {
        ingredient: 'cumin',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Indonesian cuisine',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Indonesian flavor',
      },
      {
        ingredient: 'candlenuts',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential nut for Indonesian cuisine',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Indonesian richness',
      },
      {
        ingredient: 'palm sugar',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential sweetener for Indonesian cuisine',
        usage: 'Curries, desserts, marinades, main dishes',
        culturalContext: 'Essential for authentic Indonesian sweetness',
      },
      {
        ingredient: 'tamarind',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Indonesian ingredient',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Important in Indonesian cuisine',
      },
      {
        ingredient: 'shrimp paste',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Indonesian ingredient',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Important in Indonesian cuisine',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Indonesian protein',
        usage: 'Main dishes, soups, side dishes, traditional',
        culturalContext: 'Important in Indonesian cuisine',
      },
    ],
  }, */
  thai,

  korean,

  japanese,
  vietnamese,
  filipino,
  // Thai sub-regions (optional granular entries)
  // Note: these complement the parent 'thai' entry
  thai_central: thaiCentral,
  thai_northern: thaiNorthern,
  thai_southern: thaiSouthern,
  thai_isaan: thaiIsaan,
  /* moved to asian/thai.ts */
  /* thai_legacy: {
    cuisine: 'Thai',
    description:
      'Essential ingredients for authentic Thai cooking with balanced flavors',
    subStyles: [
      'Central Thai',
      'Northern Thai',
      'Southern Thai',
      'Isaan',
      'Royal Thai',
    ],
    staples: [
      {
        ingredient: 'fish sauce',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Fundamental umami flavor in Thai cuisine',
        usage: 'Curries, stir-fries, dipping sauces, marinades',
        culturalContext: 'The salt of Thai cooking - cannot be substituted',
      },
      {
        ingredient: 'lime',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for Thai flavor balance',
        usage: 'Curries, stir-fries, salads, finishing',
        culturalContext: 'Essential for authentic Thai sour flavor',
      },
      {
        ingredient: 'lemongrass',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Distinctive Thai herb and flavor',
        usage: 'Curries, soups, marinades, tea',
        culturalContext: 'Signature Thai flavor that cannot be replicated',
      },
      {
        ingredient: 'galangal',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential Thai root for authentic flavor',
        usage: 'Curries, soups, marinades',
        culturalContext: 'Cannot make authentic Thai curry without galangal',
      },
      {
        ingredient: 'kaffir lime leaves',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Distinctive Thai citrus flavor',
        usage: 'Curries, soups, stir-fries, garnishes',
        culturalContext: 'Essential for authentic Thai aroma',
      },
      {
        ingredient: 'Thai basil',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Thai cooking',
        usage: 'Curries, stir-fries, garnishes',
        culturalContext:
          'Different from regular basil - essential for Thai dishes',
      },
      {
        ingredient: 'cilantro',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Thai cuisine',
        usage: 'Garnishes, curries, salads',
        culturalContext: 'Essential for authentic Thai flavor profile',
      },
      {
        ingredient: 'chili peppers',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential heat for Thai cuisine',
        usage: 'Curries, stir-fries, salads, pastes',
        culturalContext: 'Thai cuisine is known for its heat',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Thai cooking',
        usage: 'Curries, stir-fries, pastes, marinades',
        culturalContext: 'Foundation of Thai flavor building',
      },
      {
        ingredient: 'shallots',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Thai dishes',
        usage: 'Curries, stir-fries, pastes, garnishes',
        culturalContext: 'More important than onions in Thai cooking',
      },
      {
        ingredient: 'palm sugar',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Authentic sweetener for Thai cuisine',
        usage: 'Curries, stir-fries, desserts, balance',
        culturalContext: 'Essential for authentic Thai sweetness',
      },
      {
        ingredient: 'tamarind',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential sour flavor for Thai cuisine',
        usage: 'Curries, stir-fries, soups, balance',
        culturalContext: 'Essential for authentic Thai sour flavor',
      },
      {
        ingredient: 'coconut milk',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Creamy base for Thai curries',
        usage: 'Curries, soups, desserts, beverages',
        culturalContext: 'Essential for authentic Thai curry texture',
      },
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Thai meals',
        usage: 'Steamed rice, fried rice, sticky rice',
        culturalContext: 'Foundation of Thai meals',
      },
      {
        ingredient: 'rice noodles',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for Thai noodle dishes',
        usage: 'Pad Thai, noodle soups, stir-fries',
        culturalContext: 'Essential for authentic Thai noodle dishes',
      },
      {
        ingredient: 'shrimp paste',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Essential umami for Thai cooking',
        usage: 'Curries, stir-fries, pastes, marinades',
        culturalContext: 'Essential for authentic Thai umami flavor',
      },
      {
        ingredient: 'mushrooms',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular protein in Thai cuisine',
        usage: 'Stir-fries, curries, soups, salads',
        culturalContext: 'Important protein source in Thai cooking',
      },
    ],
  }, */
  chinese,
  /* moved to asian/chinese.ts */
  /* chinese_legacy: {
    cuisine: 'Chinese',
    description: 'Essential ingredients for authentic Chinese cooking',
    subStyles: ['Cantonese', 'Sichuan', 'Hunan', 'Shanghai', 'Beijing'],
    staples: [
      {
        ingredient: 'soy sauce',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Fundamental seasoning for Chinese cuisine',
        usage: 'Marinades, stir-fries, dipping sauces',
        culturalContext: 'The backbone of Chinese flavor profile',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Chinese cooking',
        usage: 'Stir-fries, marinades, sauces',
        culturalContext: 'Used in almost every Chinese dish',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Core aromatic and medicinal ingredient',
        usage: 'Stir-fries, marinades, tea, soups',
        culturalContext: 'Balances flavors and aids digestion',
      },
      {
        ingredient: 'green onions',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential garnish and flavor enhancer',
        usage: 'Garnish, stir-fries, dumplings',
        culturalContext:
          'Cannot make authentic Chinese food without scallions',
      },
      {
        ingredient: 'sesame oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Distinctive Chinese flavor and aroma',
        usage: 'Finishing oil, marinades, dressings',
        culturalContext: 'Adds authentic Chinese aroma',
      },
      {
        ingredient: 'rice vinegar',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential acid for Chinese cooking',
        usage: 'Stir-fries, dipping sauces, pickling',
        culturalContext:
          'Milder than other vinegars, perfect for Chinese dishes',
      },
      {
        ingredient: 'oyster sauce',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Rich umami flavor for Chinese dishes',
        usage: 'Stir-fries, marinades, glazes',
        culturalContext: 'Essential for authentic Chinese stir-fries',
      },
      {
        ingredient: 'hoisin sauce',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Sweet and savory Chinese condiment',
        usage: 'Marinades, dipping sauces, glazes',
        culturalContext: 'Key ingredient in Peking duck and many dishes',
      },
      {
        ingredient: 'chili oil',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Adds heat and flavor to Chinese dishes',
        usage: 'Dipping sauces, stir-fries, noodles',
        culturalContext: 'Essential for Sichuan and Hunan cuisine',
      },
      {
        ingredient: 'star anise',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Distinctive Chinese spice for braising',
        usage: 'Braised dishes, five-spice powder, soups',
        culturalContext: 'Key spice in Chinese five-spice blend',
      },
      {
        ingredient: 'Sichuan peppercorns',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Unique numbing spice for Sichuan cuisine',
        usage: 'Sichuan dishes, marinades, spice blends',
        culturalContext: 'Essential for authentic Sichuan cooking',
      },
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Chinese meals',
        usage: 'Steamed rice, fried rice, congee',
        culturalContext: 'Foundation of Chinese meals',
      },
      {
        ingredient: 'noodles',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for Chinese noodle dishes',
        usage: 'Lo mein, chow mein, soup noodles',
        culturalContext: 'Noodles represent longevity in Chinese culture',
      },
      {
        ingredient: 'tofu',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Versatile protein for Chinese cooking',
        usage: 'Stir-fries, soups, braised dishes',
        culturalContext: 'Important protein source in Chinese cuisine',
      },
      {
        ingredient: 'bok choy',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Chinese leafy green',
        usage: 'Stir-fries, soups, steamed dishes',
        culturalContext: 'Most common Chinese vegetable',
      },
    ],
  }, */
  indian,
  /* moved to asian/indian.ts */
  /* indian_legacy: {
    cuisine: 'Indian',
    description:
      'Essential spices and ingredients for authentic Indian cooking',
    subStyles: [
      'North Indian',
      'South Indian',
      'Gujarati',
      'Bengali',
      'Punjabi',
    ],
    staples: [
      {
        ingredient: 'turmeric',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Golden spice that defines Indian cuisine',
        usage: 'Curries, rice, marinades, health benefits',
        culturalContext: 'Sacred spice with medicinal properties',
      },
      {
        ingredient: 'cumin',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Fundamental spice in Indian cooking',
        usage: 'Tempering, curries, rice dishes',
        culturalContext: 'Most important spice in Indian cuisine',
      },
      {
        ingredient: 'coriander',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice and herb combination',
        usage: 'Curries, chutneys, garnishes',
        culturalContext: 'Both seeds and leaves are essential',
      },
      {
        ingredient: 'garam masala',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Signature Indian spice blend',
        usage: 'Curries, rice, finishing spice',
        culturalContext: 'The heart of Indian flavor profile',
      },
      {
        ingredient: 'cardamom',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Aromatic spice for Indian dishes',
        usage: 'Curries, rice, desserts, tea',
        culturalContext: 'Queen of spices in Indian cuisine',
      },
      {
        ingredient: 'cinnamon',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Warm spice for Indian cooking',
        usage: 'Curries, rice, desserts, tea',
        culturalContext: 'Essential for authentic Indian flavor',
      },
      {
        ingredient: 'cloves',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Aromatic spice for Indian dishes',
        usage: 'Curries, rice, pickles, tea',
        culturalContext: 'Adds depth to Indian spice blends',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Indian cooking',
        usage: 'Curries, marinades, tea, health benefits',
        culturalContext: 'Medicinal and culinary importance',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Fundamental aromatic for Indian dishes',
        usage: 'Curries, marinades, tempering',
        culturalContext: 'Essential base for most Indian dishes',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Indian cooking',
        usage: 'Curries, rice, tempering, garnishes',
        culturalContext: 'Foundation of Indian flavor building',
      },
      {
        ingredient: 'chili powder',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Heat and color for Indian dishes',
        usage: 'Curries, marinades, spice blends',
        culturalContext: 'Essential for authentic Indian heat',
      },
      {
        ingredient: 'mustard seeds',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential for tempering in Indian cooking',
        usage: 'Tempering, pickles, curries',
        culturalContext: 'Cannot make authentic Indian food without tempering',
      },
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Indian meals',
        usage: 'Basmati rice, biryani, everyday meals',
        culturalContext: 'Foundation of Indian meals',
      },
      {
        ingredient: 'lentils',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein source in Indian cuisine',
        usage: 'Dal, curries, soups, side dishes',
        culturalContext: 'Primary protein source for many Indians',
      },
      {
        ingredient: 'ghee',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Traditional cooking fat for Indian cuisine',
        usage: 'Tempering, rice, desserts, cooking',
        culturalContext: 'Sacred and essential in Indian cooking',
      },
      {
        ingredient: 'coconut milk',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Creamy base for South Indian dishes',
        usage: 'Curries, rice, desserts, beverages',
        culturalContext: 'Essential for South Indian cuisine',
      },
      {
        ingredient: 'cilantro',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Indian cooking',
        usage: 'Garnishes, chutneys, curries',
        culturalContext: 'Cannot make authentic Indian food without cilantro',
      },
    ],
  }, */

  /* moved to asian/korean.ts */
  /* korean_legacy: {
    cuisine: 'Korean',
    description:
      'Essential ingredients for authentic Korean cooking with fermented flavors',
    subStyles: ['Seoul', 'Busan', 'Jeju', 'Gyeongju', 'Traditional Korean'],
    staples: [
      {
        ingredient: 'gochujang',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Signature Korean fermented chili paste',
        usage: 'Bulgogi, bibimbap, stews, marinades',
        culturalContext: 'The soul of Korean cuisine - cannot be substituted',
      },
      {
        ingredient: 'kimchi',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'National dish and essential Korean ingredient',
        usage: 'Side dish, stews, fried rice, pancakes',
        culturalContext: 'Koreans eat kimchi with every meal',
      },
      {
        ingredient: 'sesame oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential Korean flavor and aroma',
        usage: 'Finishing oil, marinades, dressings, garnishes',
        culturalContext: 'Essential for authentic Korean aroma',
      },
      {
        ingredient: 'soy sauce',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Fundamental seasoning for Korean cuisine',
        usage: 'Marinades, dipping sauces, stews',
        culturalContext: 'Base seasoning for most Korean dishes',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Korean cooking',
        usage: 'Marinades, stews, kimchi, pastes',
        culturalContext: 'Koreans use more garlic than any other cuisine',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Korean dishes',
        usage: 'Marinades, teas, kimchi, health benefits',
        culturalContext:
          'Medicinal and culinary importance in Korean culture',
      },
      {
        ingredient: 'green onions',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential garnish and flavor enhancer',
        usage: 'Garnish, pancakes, stews, marinades',
        culturalContext:
          'Cannot make authentic Korean food without scallions',
      },
      {
        ingredient: 'gochugaru',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Korean chili flakes for authentic heat',
        usage: 'Kimchi, stews, marinades, spice blends',
        culturalContext: 'Essential for authentic Korean spice level',
      },
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Korean meals',
        usage: 'Steamed rice, fried rice, porridge',
        culturalContext: 'Foundation of Korean meals',
      },
      {
        ingredient: 'noodles',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for Korean noodle dishes',
        usage: 'Japchae, cold noodles, soup noodles',
        culturalContext: 'Noodles represent longevity in Korean culture',
      },
      {
        ingredient: 'tofu',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Important protein in Korean cuisine',
        usage: 'Stews, stir-fries, soups, side dishes',
        culturalContext: 'Important protein source in Korean cooking',
      },
      {
        ingredient: 'mushrooms',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular ingredient in Korean dishes',
        usage: 'Stir-fries, stews, soups, side dishes',
        culturalContext: 'Important ingredient in Korean cuisine',
      },
      {
        ingredient: 'seaweed',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Traditional Korean ingredient',
        usage: 'Soups, side dishes, rice rolls',
        culturalContext: 'Important in Korean coastal cuisine',
      },
      {
        ingredient: 'bean sprouts',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Korean vegetable',
        usage: 'Stir-fries, soups, side dishes, bibimbap',
        culturalContext: 'Common ingredient in Korean dishes',
      },
      {
        ingredient: 'pear',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Used in Korean marinades and sauces',
        usage: 'Bulgogi marinades, sauces, desserts',
        culturalContext: 'Korean pears tenderize meat naturally',
      },
      {
        ingredient: 'sesame seeds',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Essential garnish for Korean dishes',
        usage: 'Garnishes, marinades, dressings',
        culturalContext: 'Essential for authentic Korean presentation',
      },
    ],
  }, */

  /* moved to asian/japanese.ts */
  /* japanese_legacy: {
    cuisine: 'Japanese',
    description:
      'Essential ingredients for authentic Japanese cooking with fresh ingredients',
    subStyles: [
      'Tokyo',
      'Osaka',
      'Kyoto',
      'Traditional Japanese',
      'Modern Japanese',
    ],
    staples: [
      {
        ingredient: 'soy sauce',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Fundamental seasoning for Japanese cuisine',
        usage: 'Sushi, marinades, dipping sauces, cooking',
        culturalContext: 'The backbone of Japanese flavor profile',
      },
      {
        ingredient: 'miso',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential fermented paste for Japanese cooking',
        usage: 'Soups, marinades, dressings, glazes',
        culturalContext: 'Miso is the soul of Japanese cooking',
      },
      {
        ingredient: 'rice vinegar',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential acid for Japanese cuisine',
        usage: 'Sushi rice, dressings, pickling, marinades',
        culturalContext: 'Essential for authentic Japanese sour flavor',
      },
      {
        ingredient: 'mirin',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Sweet rice wine for Japanese cooking',
        usage: 'Teriyaki, glazes, marinades, sauces',
        culturalContext: 'Essential for authentic Japanese sweetness',
      },
      {
        ingredient: 'sake',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Japanese rice wine for cooking',
        usage: 'Marinades, sauces, steaming, deglazing',
        culturalContext: 'Essential for authentic Japanese flavor building',
      },
      {
        ingredient: 'dashi',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential Japanese stock base',
        usage: 'Soups, sauces, rice, everything',
        culturalContext: 'The foundation of Japanese umami',
      },
      {
        ingredient: 'wasabi',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential Japanese condiment',
        usage: 'Sushi, sashimi, marinades, dressings',
        culturalContext:
          'Cannot have authentic Japanese sushi without wasabi',
      },
      {
        ingredient: 'nori',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential seaweed for Japanese cuisine',
        usage: 'Sushi, rice balls, garnishes, snacks',
        culturalContext: 'Essential for sushi and many Japanese dishes',
      },
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Japanese meals',
        usage: 'Sushi rice, steamed rice, rice balls',
        culturalContext: 'Foundation of Japanese meals',
      },
      {
        ingredient: 'noodles',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for Japanese noodle dishes',
        usage: 'Ramen, udon, soba, cold noodles',
        culturalContext: 'Essential for authentic Japanese noodle dishes',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Japanese cooking',
        usage: 'Sushi, marinades, pickles, tea',
        culturalContext: 'Essential for authentic Japanese flavor',
      },
      {
        ingredient: 'green onions',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential garnish for Japanese dishes',
        usage: 'Garnish, soups, rice, marinades',
        culturalContext: 'Essential for authentic Japanese presentation',
      },
      {
        ingredient: 'tofu',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein in Japanese cuisine',
        usage: 'Miso soup, stir-fries, hot pot, desserts',
        culturalContext: 'Fundamental protein in Japanese cooking',
      },
      {
        ingredient: 'mushrooms',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular ingredient in Japanese dishes',
        usage: 'Stir-fries, soups, rice, side dishes',
        culturalContext: 'Important ingredient in Japanese cuisine',
      },
      {
        ingredient: 'daikon',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Japanese root vegetable',
        usage: 'Pickles, soups, garnishes, side dishes',
        culturalContext: 'Important vegetable in Japanese cooking',
      },
      {
        ingredient: 'bonito flakes',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Essential for authentic dashi',
        usage: 'Dashi stock, garnishes, seasonings',
        culturalContext: 'Essential for authentic Japanese umami',
      },
      {
        ingredient: 'kombu',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Essential seaweed for dashi',
        usage: 'Dashi stock, cooking, seasonings',
        culturalContext: 'Essential for authentic Japanese stock',
      },
    ],
  }, */
  malaysian,
  /* moved to asian/malaysian.ts */
  /* malaysian_legacy: {
    cuisine: 'Malaysian',
    description:
      'Essential ingredients for authentic Malaysian cooking with laksa and nasi lemak',
    subStyles: [
      'Kuala Lumpur',
      'Penang',
      'Malacca',
      'Traditional Malaysian',
      'Modern Malaysian',
    ],
    staples: [
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Malaysian meals',
        usage: 'Nasi lemak, main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of Malaysian meals',
      },
      {
        ingredient: 'coconut milk',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for Malaysian curries and stews',
        usage: 'Laksa, curries, stews, desserts, beverages',
        culturalContext: 'Essential for authentic Malaysian creaminess',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Malaysian cooking',
        usage: 'Laksa, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Malaysian flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Malaysian cooking',
        usage: 'Laksa, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Malaysian flavor building',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Malaysian dishes',
        usage: 'Laksa, marinades, teas, health benefits',
        culturalContext:
          'Medicinal and culinary importance in Malaysian culture',
      },
      {
        ingredient: 'chili peppers',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential heat for Malaysian cuisine',
        usage: 'Laksa, stews, marinades, sauces',
        culturalContext: 'Malaysian cuisine is known for its heat',
      },
      {
        ingredient: 'lemongrass',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Malaysian cuisine',
        usage: 'Laksa, curries, stews, marinades, aromatics',
        culturalContext:
          'Cannot make authentic Malaysian food without lemongrass',
      },
      {
        ingredient: 'galangal',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential root for Malaysian cuisine',
        usage: 'Laksa, curries, stews, marinades, aromatics',
        culturalContext: 'Essential for authentic Malaysian flavor',
      },
      {
        ingredient: 'turmeric',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Malaysian cuisine',
        usage: 'Laksa, curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Malaysian color and flavor',
      },
      {
        ingredient: 'coriander',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Malaysian cuisine',
        usage: 'Laksa, garnishes, marinades, main dishes, salads',
        culturalContext:
          'Cannot make authentic Malaysian food without coriander',
      },
      {
        ingredient: 'cumin',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Malaysian cuisine',
        usage: 'Laksa, curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Malaysian flavor',
      },
      {
        ingredient: 'candlenuts',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential nut for Malaysian cuisine',
        usage: 'Laksa, curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Malaysian richness',
      },
      {
        ingredient: 'palm sugar',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential sweetener for Malaysian cuisine',
        usage: 'Laksa, curries, desserts, marinades, main dishes',
        culturalContext: 'Essential for authentic Malaysian sweetness',
      },
      {
        ingredient: 'tamarind',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Malaysian ingredient',
        usage: 'Laksa, curries, stews, marinades, main dishes',
        culturalContext: 'Important in Malaysian cuisine',
      },
      {
        ingredient: 'shrimp paste',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Malaysian ingredient',
        usage: 'Laksa, curries, stews, marinades, main dishes',
        culturalContext: 'Important in Malaysian cuisine',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Malaysian protein',
        usage: 'Laksa, main dishes, soups, side dishes, traditional',
        culturalContext: 'Important in Malaysian cuisine',
      },
    ],
  }, */
  singaporean,
  /* moved to asian/singaporean.ts */
  /* singaporean_legacy: {
    cuisine: 'Singaporean',
    description:
      'Essential ingredients for authentic Singaporean cooking with Hainanese chicken rice and chili crab',
    subStyles: [
      'Singapore',
      'Chinatown',
      'Little India',
      'Traditional Singaporean',
      'Modern Singaporean',
    ],
    staples: [
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Singaporean meals',
        usage:
          'Hainanese chicken rice, main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of Singaporean meals',
      },
      {
        ingredient: 'chicken',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Singaporean cuisine',
        usage: 'Hainanese chicken rice, main dishes, soups, side dishes',
        culturalContext: 'Chicken is the soul of Singaporean cuisine',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Singaporean cooking',
        usage: 'Hainanese chicken rice, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Singaporean flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Singaporean cooking',
        usage: 'Hainanese chicken rice, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Singaporean flavor building',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Singaporean dishes',
        usage: 'Hainanese chicken rice, marinades, teas, health benefits',
        culturalContext:
          'Medicinal and culinary importance in Singaporean culture',
      },
      {
        ingredient: 'chili peppers',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential heat for Singaporean cuisine',
        usage: 'Chili crab, stews, marinades, sauces',
        culturalContext: 'Singaporean cuisine is known for its heat',
      },
      {
        ingredient: 'lemongrass',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Singaporean cuisine',
        usage: 'Curries, stews, marinades, aromatics',
        culturalContext:
          'Cannot make authentic Singaporean food without lemongrass',
      },
      {
        ingredient: 'galangal',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential root for Singaporean cuisine',
        usage: 'Curries, stews, marinades, aromatics',
        culturalContext: 'Essential for authentic Singaporean flavor',
      },
      {
        ingredient: 'turmeric',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Singaporean cuisine',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Singaporean color and flavor',
      },
      {
        ingredient: 'coriander',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Singaporean cuisine',
        usage: 'Garnishes, marinades, main dishes, salads',
        culturalContext:
          'Cannot make authentic Singaporean food without coriander',
      },
      {
        ingredient: 'cumin',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Singaporean cuisine',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Singaporean flavor',
      },
      {
        ingredient: 'candlenuts',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential nut for Singaporean cuisine',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Singaporean richness',
      },
      {
        ingredient: 'palm sugar',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential sweetener for Singaporean cuisine',
        usage: 'Curries, desserts, marinades, main dishes',
        culturalContext: 'Essential for authentic Singaporean sweetness',
      },
      {
        ingredient: 'tamarind',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Singaporean ingredient',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Important in Singaporean cuisine',
      },
      {
        ingredient: 'shrimp paste',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Singaporean ingredient',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Important in Singaporean cuisine',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Singaporean protein',
        usage: 'Main dishes, soups, side dishes, traditional',
        culturalContext: 'Important in Singaporean cuisine',
      },
    ],
  }, */
};
