import { CuisineStaplesData } from '../cuisine-staples';

export const asianCuisines: Record<string, CuisineStaplesData> = {
  indonesian: {
    cuisine: 'Indonesian',
    description:
      'Essential ingredients for authentic Indonesian cooking with nasi goreng and rendang',
    subStyles: [
      'Jakarta',
      'Bali',
      'Surabaya',
      'Traditional Indonesian',
      'Modern Indonesian',
    ],
    staples: [
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Indonesian meals',
        usage: 'Nasi goreng, main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of Indonesian meals',
      },
      {
        ingredient: 'coconut milk',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for Indonesian curries and stews',
        usage: 'Curries, stews, desserts, beverages',
        culturalContext: 'Essential for authentic Indonesian creaminess',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Indonesian cooking',
        usage: 'Nasi goreng, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Indonesian flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Indonesian cooking',
        usage: 'Nasi goreng, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Indonesian flavor building',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Indonesian dishes',
        usage: 'Nasi goreng, marinades, teas, health benefits',
        culturalContext:
          'Medicinal and culinary importance in Indonesian culture',
      },
      {
        ingredient: 'chili peppers',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential heat for Indonesian cuisine',
        usage: 'Nasi goreng, stews, marinades, sauces',
        culturalContext: 'Indonesian cuisine is known for its heat',
      },
      {
        ingredient: 'lemongrass',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Indonesian cuisine',
        usage: 'Curries, stews, marinades, aromatics',
        culturalContext:
          'Cannot make authentic Indonesian food without lemongrass',
      },
      {
        ingredient: 'galangal',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential root for Indonesian cuisine',
        usage: 'Curries, stews, marinades, aromatics',
        culturalContext: 'Essential for authentic Indonesian flavor',
      },
      {
        ingredient: 'turmeric',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Indonesian cuisine',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Indonesian color and flavor',
      },
      {
        ingredient: 'coriander',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Indonesian cuisine',
        usage: 'Garnishes, marinades, main dishes, salads',
        culturalContext:
          'Cannot make authentic Indonesian food without coriander',
      },
      {
        ingredient: 'cumin',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Indonesian cuisine',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Indonesian flavor',
      },
      {
        ingredient: 'candlenuts',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential nut for Indonesian cuisine',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Indonesian richness',
      },
      {
        ingredient: 'palm sugar',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential sweetener for Indonesian cuisine',
        usage: 'Curries, desserts, marinades, main dishes',
        culturalContext: 'Essential for authentic Indonesian sweetness',
      },
      {
        ingredient: 'tamarind',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Indonesian ingredient',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Important in Indonesian cuisine',
      },
      {
        ingredient: 'shrimp paste',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Indonesian ingredient',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Important in Indonesian cuisine',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Indonesian protein',
        usage: 'Main dishes, soups, side dishes, traditional',
        culturalContext: 'Important in Indonesian cuisine',
      },
    ],
  },
  malaysian: {
    cuisine: 'Malaysian',
    description:
      'Essential ingredients for authentic Malaysian cooking with laksa and nasi lemak',
    subStyles: [
      'Kuala Lumpur',
      'Penang',
      'Malacca',
      'Traditional Malaysian',
      'Modern Malaysian',
    ],
    staples: [
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Malaysian meals',
        usage: 'Nasi lemak, main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of Malaysian meals',
      },
      {
        ingredient: 'coconut milk',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for Malaysian curries and stews',
        usage: 'Laksa, curries, stews, desserts, beverages',
        culturalContext: 'Essential for authentic Malaysian creaminess',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Malaysian cooking',
        usage: 'Laksa, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Malaysian flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Malaysian cooking',
        usage: 'Laksa, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Malaysian flavor building',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Malaysian dishes',
        usage: 'Laksa, marinades, teas, health benefits',
        culturalContext:
          'Medicinal and culinary importance in Malaysian culture',
      },
      {
        ingredient: 'chili peppers',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential heat for Malaysian cuisine',
        usage: 'Laksa, stews, marinades, sauces',
        culturalContext: 'Malaysian cuisine is known for its heat',
      },
      {
        ingredient: 'lemongrass',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Malaysian cuisine',
        usage: 'Laksa, curries, stews, marinades, aromatics',
        culturalContext:
          'Cannot make authentic Malaysian food without lemongrass',
      },
      {
        ingredient: 'galangal',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential root for Malaysian cuisine',
        usage: 'Laksa, curries, stews, marinades, aromatics',
        culturalContext: 'Essential for authentic Malaysian flavor',
      },
      {
        ingredient: 'turmeric',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Malaysian cuisine',
        usage: 'Laksa, curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Malaysian color and flavor',
      },
      {
        ingredient: 'coriander',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Malaysian cuisine',
        usage: 'Laksa, garnishes, marinades, main dishes, salads',
        culturalContext:
          'Cannot make authentic Malaysian food without coriander',
      },
      {
        ingredient: 'cumin',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Malaysian cuisine',
        usage: 'Laksa, curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Malaysian flavor',
      },
      {
        ingredient: 'candlenuts',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential nut for Malaysian cuisine',
        usage: 'Laksa, curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Malaysian richness',
      },
      {
        ingredient: 'palm sugar',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential sweetener for Malaysian cuisine',
        usage: 'Laksa, curries, desserts, marinades, main dishes',
        culturalContext: 'Essential for authentic Malaysian sweetness',
      },
      {
        ingredient: 'tamarind',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Malaysian ingredient',
        usage: 'Laksa, curries, stews, marinades, main dishes',
        culturalContext: 'Important in Malaysian cuisine',
      },
      {
        ingredient: 'shrimp paste',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Malaysian ingredient',
        usage: 'Laksa, curries, stews, marinades, main dishes',
        culturalContext: 'Important in Malaysian cuisine',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Malaysian protein',
        usage: 'Laksa, main dishes, soups, side dishes, traditional',
        culturalContext: 'Important in Malaysian cuisine',
      },
    ],
  },
  singaporean: {
    cuisine: 'Singaporean',
    description:
      'Essential ingredients for authentic Singaporean cooking with Hainanese chicken rice and chili crab',
    subStyles: [
      'Singapore',
      'Chinatown',
      'Little India',
      'Traditional Singaporean',
      'Modern Singaporean',
    ],
    staples: [
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Singaporean meals',
        usage:
          'Hainanese chicken rice, main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of Singaporean meals',
      },
      {
        ingredient: 'chicken',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Singaporean cuisine',
        usage: 'Hainanese chicken rice, main dishes, soups, side dishes',
        culturalContext: 'Chicken is the soul of Singaporean cuisine',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Singaporean cooking',
        usage: 'Hainanese chicken rice, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Singaporean flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Singaporean cooking',
        usage: 'Hainanese chicken rice, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Singaporean flavor building',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Singaporean dishes',
        usage: 'Hainanese chicken rice, marinades, teas, health benefits',
        culturalContext:
          'Medicinal and culinary importance in Singaporean culture',
      },
      {
        ingredient: 'chili peppers',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential heat for Singaporean cuisine',
        usage: 'Chili crab, stews, marinades, sauces',
        culturalContext: 'Singaporean cuisine is known for its heat',
      },
      {
        ingredient: 'lemongrass',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Singaporean cuisine',
        usage: 'Curries, stews, marinades, aromatics',
        culturalContext:
          'Cannot make authentic Singaporean food without lemongrass',
      },
      {
        ingredient: 'galangal',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential root for Singaporean cuisine',
        usage: 'Curries, stews, marinades, aromatics',
        culturalContext: 'Essential for authentic Singaporean flavor',
      },
      {
        ingredient: 'turmeric',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Singaporean cuisine',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Singaporean color and flavor',
      },
      {
        ingredient: 'coriander',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Singaporean cuisine',
        usage: 'Garnishes, marinades, main dishes, salads',
        culturalContext:
          'Cannot make authentic Singaporean food without coriander',
      },
      {
        ingredient: 'cumin',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Singaporean cuisine',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Singaporean flavor',
      },
      {
        ingredient: 'candlenuts',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential nut for Singaporean cuisine',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Essential for authentic Singaporean richness',
      },
      {
        ingredient: 'palm sugar',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential sweetener for Singaporean cuisine',
        usage: 'Curries, desserts, marinades, main dishes',
        culturalContext: 'Essential for authentic Singaporean sweetness',
      },
      {
        ingredient: 'tamarind',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Singaporean ingredient',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Important in Singaporean cuisine',
      },
      {
        ingredient: 'shrimp paste',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Singaporean ingredient',
        usage: 'Curries, stews, marinades, main dishes',
        culturalContext: 'Important in Singaporean cuisine',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Singaporean protein',
        usage: 'Main dishes, soups, side dishes, traditional',
        culturalContext: 'Important in Singaporean cuisine',
      },
    ],
  },
};
