import { CuisineStaplesData } from '../cuisine-staples';

export const caribbeanCuisines: Record<string, CuisineStaplesData> = {
  cuban: {
    cuisine: 'Cuban',
    description:
      'Essential ingredients for authentic Cuban cooking with ropa vieja and mojitos',
    subStyles: [
      'Havana',
      'Santiago',
      'Camagüey',
      'Traditional Cuban',
      'Modern Cuban',
    ],
    staples: [
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Cuban meals',
        usage: 'Ropa vieja, main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of Cuban meals',
      },
      {
        ingredient: 'black beans',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential legume for Cuban cuisine',
        usage: 'Ropa vieja, stews, main dishes, side dishes',
        culturalContext: 'Black beans are the soul of Cuban cuisine',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Cuban cooking',
        usage: 'Ropa vieja, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Cuban flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Cuban cooking',
        usage: 'Ropa vieja, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Cuban flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Cuban dishes',
        usage: 'Ropa vieja, stews, main dishes, sauces',
        culturalContext: 'Essential for authentic Cuban dishes',
      },
      {
        ingredient: 'bell peppers',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Cuban cuisine',
        usage: 'Ropa vieja, stews, main dishes, side dishes',
        culturalContext: 'Bell peppers are essential for Cuban flavor',
      },
      {
        ingredient: 'lime',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for Cuban cuisine',
        usage: 'Ropa vieja, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Cuban brightness',
      },
      {
        ingredient: 'olive oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential cooking oil for Cuban cuisine',
        usage: 'Ropa vieja, cooking, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Cuban cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Cuban cuisine',
        usage: 'Ropa vieja, garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Cannot make authentic Cuban food without herbs',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Cuban cuisine',
        usage: 'Ropa vieja, marinades, stews, main dishes, everything',
        culturalContext: 'Essential for authentic Cuban flavor',
      },
      {
        ingredient: 'rum',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spirit for Cuban cuisine',
        usage: 'Mojitos, cooking, marinades, sauces, drinking',
        culturalContext: 'Cuban rum is world-famous',
      },
      {
        ingredient: 'sugar',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential sweetener for Cuban cuisine',
        usage: 'Mojitos, desserts, marinades, main dishes',
        culturalContext: 'Essential for Cuban mojitos and desserts',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Cuban ingredients',
        usage: 'Ropa vieja, stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Important in Cuban cuisine',
      },
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Cuban protein',
        usage: 'Ropa vieja, main dishes, stews, soups, side dishes',
        culturalContext: 'Important in Cuban cuisine',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Cuban protein',
        usage: 'Ropa vieja, main dishes, soups, side dishes, traditional',
        culturalContext: 'Important in Cuban cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Cuban ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Cuban wine is important in the cuisine',
      },
    ],
  },
  puerto_rican: {
    cuisine: 'Puerto Rican',
    description:
      'Essential ingredients for authentic Puerto Rican cooking with mofongo and arroz con gandules',
    subStyles: [
      'San Juan',
      'Ponce',
      'Mayagüez',
      'Traditional Puerto Rican',
      'Modern Puerto Rican',
    ],
    staples: [
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Puerto Rican meals',
        usage: 'Arroz con gandules, main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of Puerto Rican meals',
      },
      {
        ingredient: 'pigeon peas',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential legume for Puerto Rican cuisine',
        usage: 'Arroz con gandules, stews, main dishes, side dishes',
        culturalContext: 'Pigeon peas are the soul of Puerto Rican cuisine',
      },
      {
        ingredient: 'plantains',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential fruit for Puerto Rican cuisine',
        usage: 'Mofongo, main dishes, side dishes, snacks',
        culturalContext: 'Plantains are essential for Puerto Rican mofongo',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Puerto Rican cooking',
        usage: 'Arroz con gandules, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Puerto Rican flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Puerto Rican cooking',
        usage: 'Arroz con gandules, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Puerto Rican flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Puerto Rican dishes',
        usage: 'Arroz con gandules, stews, main dishes, sauces',
        culturalContext: 'Essential for authentic Puerto Rican dishes',
      },
      {
        ingredient: 'bell peppers',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Puerto Rican cuisine',
        usage: 'Arroz con gandules, stews, main dishes, side dishes',
        culturalContext: 'Bell peppers are essential for Puerto Rican flavor',
      },
      {
        ingredient: 'lime',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for Puerto Rican cuisine',
        usage: 'Arroz con gandules, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Puerto Rican brightness',
      },
      {
        ingredient: 'olive oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential cooking oil for Puerto Rican cuisine',
        usage: 'Arroz con gandules, cooking, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Puerto Rican cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Puerto Rican cuisine',
        usage:
          'Arroz con gandules, garnishes, marinades, main dishes, aromatics',
        culturalContext:
          'Cannot make authentic Puerto Rican food without herbs',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Puerto Rican cuisine',
        usage: 'Arroz con gandules, marinades, stews, main dishes, everything',
        culturalContext: 'Essential for authentic Puerto Rican flavor',
      },
      {
        ingredient: 'rum',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spirit for Puerto Rican cuisine',
        usage: 'Cocktails, cooking, marinades, sauces, drinking',
        culturalContext: 'Puerto Rican rum is world-famous',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Puerto Rican ingredients',
        usage:
          'Arroz con gandules, stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Important in Puerto Rican cuisine',
      },
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Puerto Rican protein',
        usage: 'Arroz con gandules, main dishes, stews, soups, side dishes',
        culturalContext: 'Important in Puerto Rican cuisine',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Puerto Rican protein',
        usage:
          'Arroz con gandules, main dishes, soups, side dishes, traditional',
        culturalContext: 'Important in Puerto Rican cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Puerto Rican ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Puerto Rican wine is important in the cuisine',
      },
    ],
  },
  dominican: {
    cuisine: 'Dominican',
    description:
      'Essential ingredients for authentic Dominican cooking with sancocho and mangu',
    subStyles: [
      'Santo Domingo',
      'Santiago',
      'La Romana',
      'Traditional Dominican',
      'Modern Dominican',
    ],
    staples: [
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Dominican meals',
        usage: 'Sancocho, main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of Dominican meals',
      },
      {
        ingredient: 'plantains',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential fruit for Dominican cuisine',
        usage: 'Mangu, main dishes, side dishes, snacks',
        culturalContext: 'Plantains are essential for Dominican mangu',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Dominican cooking',
        usage: 'Sancocho, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Dominican flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Dominican cooking',
        usage: 'Sancocho, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Dominican flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Dominican dishes',
        usage: 'Sancocho, stews, main dishes, sauces',
        culturalContext: 'Essential for authentic Dominican dishes',
      },
      {
        ingredient: 'bell peppers',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Dominican cuisine',
        usage: 'Sancocho, stews, main dishes, side dishes',
        culturalContext: 'Bell peppers are essential for Dominican flavor',
      },
      {
        ingredient: 'lime',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for Dominican cuisine',
        usage: 'Sancocho, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Dominican brightness',
      },
      {
        ingredient: 'olive oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential cooking oil for Dominican cuisine',
        usage: 'Sancocho, cooking, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Dominican cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Dominican cuisine',
        usage: 'Sancocho, garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Cannot make authentic Dominican food without herbs',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Dominican cuisine',
        usage: 'Sancocho, marinades, stews, main dishes, everything',
        culturalContext: 'Essential for authentic Dominican flavor',
      },
      {
        ingredient: 'rum',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spirit for Dominican cuisine',
        usage: 'Cocktails, cooking, marinades, sauces, drinking',
        culturalContext: 'Dominican rum is world-famous',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Dominican cuisine',
        usage: 'Sancocho, stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Essential for authentic Dominican dishes',
      },
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Dominican protein',
        usage: 'Sancocho, main dishes, stews, soups, side dishes',
        culturalContext: 'Important in Dominican cuisine',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Dominican protein',
        usage: 'Sancocho, main dishes, soups, side dishes, traditional',
        culturalContext: 'Important in Dominican cuisine',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'recommended',
        reason: 'Popular Dominican ingredient',
        usage: 'Mangu, main dishes, snacks, side dishes',
        culturalContext: 'Important in Dominican cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Dominican ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Dominican wine is important in the cuisine',
      },
    ],
  },
};
