import { CuisineStaplesData } from '../cuisine-staples/types';

export const culturalAdaptations: Record<string, CuisineStaplesData> = {
  kosher: {
    cuisine: 'Kosher',
    description:
      'Essential ingredients for authentic kosher cooking following Jewish dietary laws',
    subStyles: [
      'Traditional Kosher',
      'Modern Kosher',
      'Ashkenazi Kosher',
      'Sephardic Kosher',
      'Contemporary Kosher',
    ],
    staples: [
      {
        ingredient: 'kosher_salt',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasoning for kosher cooking',
        usage: 'Curing, seasoning, main dishes, everything',
        culturalContext:
          'Kosher salt is essential for authentic kosher cooking',
      },
      {
        ingredient: 'matzo',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential staple for kosher cooking',
        usage: 'Main dishes, side dishes, snacks, desserts',
        culturalContext: 'Matzo is essential for kosher cooking',
      },
      {
        ingredient: 'chicken',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for kosher cooking',
        usage: 'Main dishes, soups, side dishes, traditional',
        culturalContext: 'Chicken is the primary protein in kosher cooking',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for kosher cooking',
        usage: 'Main dishes, soups, side dishes, traditional',
        culturalContext: 'Fish is essential for kosher cooking',
      },
      {
        ingredient: 'eggs',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for kosher cooking',
        usage: 'Baking, main dishes, desserts, side dishes',
        culturalContext: 'Essential for kosher baking and main dishes',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for kosher cooking',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Vegetables are the foundation of kosher cooking',
      },
      {
        ingredient: 'fruits',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for kosher cooking',
        usage: 'Desserts, snacks, main dishes, side dishes',
        culturalContext: 'Fruits provide natural sweetness in kosher cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for kosher cooking',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Herbs add flavor and nutrients to kosher dishes',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for kosher cooking',
        usage: 'Marinades, main dishes, everything',
        culturalContext: 'Spices add depth and flavor to kosher dishes',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for kosher cooking',
        usage: 'Marinades, sauces, main dishes, aromatics',
        culturalContext: 'Foundation of kosher flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for kosher cooking',
        usage: 'Stews, main dishes, aromatics',
        culturalContext: 'Foundation of kosher flavor building',
      },
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fat for kosher cooking',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext:
          'Olive oil is the primary healthy fat in kosher cooking',
      },
      {
        ingredient: 'grains',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular kosher ingredients',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Important in kosher cuisine',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular kosher ingredients',
        usage: 'Desserts, main dishes, snacks, side dishes',
        culturalContext: 'Important in kosher cuisine',
      },
      {
        ingredient: 'honey',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular kosher ingredient',
        usage: 'Desserts, marinades, beverages, main dishes',
        culturalContext: 'Important in kosher cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular kosher ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Kosher wine is important in the cuisine',
      },
    ],
  },
  halal: {
    cuisine: 'Halal',
    description:
      'Essential ingredients for authentic halal cooking following Islamic dietary laws',
    subStyles: [
      'Traditional Halal',
      'Modern Halal',
      'Middle Eastern Halal',
      'South Asian Halal',
      'Contemporary Halal',
    ],
    staples: [
      {
        ingredient: 'lamb',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for halal cooking',
        usage: 'Main dishes, stews, soups, side dishes',
        culturalContext: 'Lamb is the primary protein in halal cooking',
      },
      {
        ingredient: 'chicken',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for halal cooking',
        usage: 'Main dishes, soups, side dishes, traditional',
        culturalContext: 'Chicken is essential for halal cooking',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for halal cooking',
        usage: 'Main dishes, soups, side dishes, traditional',
        culturalContext: 'Fish is essential for halal cooking',
      },
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for halal meals',
        usage: 'Main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of halal meals',
      },
      {
        ingredient: 'legumes',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein source for halal cooking',
        usage: 'Main dishes, stews, salads, side dishes',
        culturalContext: 'Legumes are the foundation of halal protein',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for halal cooking',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Vegetables are the foundation of halal cooking',
      },
      {
        ingredient: 'fruits',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for halal cooking',
        usage: 'Desserts, snacks, main dishes, side dishes',
        culturalContext: 'Fruits provide natural sweetness in halal cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for halal cooking',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Herbs add flavor and nutrients to halal dishes',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for halal cooking',
        usage: 'Marinades, main dishes, everything',
        culturalContext: 'Spices add depth and flavor to halal dishes',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for halal cooking',
        usage: 'Marinades, sauces, main dishes, aromatics',
        culturalContext: 'Foundation of halal flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for halal cooking',
        usage: 'Stews, main dishes, aromatics',
        culturalContext: 'Foundation of halal flavor building',
      },
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fat for halal cooking',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext:
          'Olive oil is the primary healthy fat in halal cooking',
      },
      {
        ingredient: 'grains',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular halal ingredients',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Important in halal cuisine',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular halal ingredients',
        usage: 'Desserts, main dishes, snacks, side dishes',
        culturalContext: 'Important in halal cuisine',
      },
      {
        ingredient: 'honey',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular halal ingredient',
        usage: 'Desserts, marinades, beverages, main dishes',
        culturalContext: 'Important in halal cuisine',
      },
      {
        ingredient: 'dates',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular halal ingredient',
        usage: 'Desserts, snacks, main dishes, side dishes',
        culturalContext: 'Important in halal cuisine',
      },
    ],
  },
  vegetarian_adaptations: {
    cuisine: 'Vegetarian Adaptations',
    description:
      'Essential ingredients for authentic vegetarian adaptations of traditional cuisines',
    subStyles: [
      'Traditional Vegetarian',
      'Modern Vegetarian',
      'Mediterranean Vegetarian',
      'Asian Vegetarian',
      'Indian Vegetarian',
    ],
    staples: [
      {
        ingredient: 'tofu',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for vegetarian adaptations',
        usage: 'Main dishes, stir-fries, soups, side dishes',
        culturalContext: 'Tofu is the foundation of vegetarian protein',
      },
      {
        ingredient: 'tempeh',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for vegetarian adaptations',
        usage: 'Main dishes, stir-fries, soups, side dishes',
        culturalContext: 'Tempeh provides essential vegetarian protein',
      },
      {
        ingredient: 'legumes',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein source for vegetarian adaptations',
        usage: 'Main dishes, stews, salads, side dishes',
        culturalContext: 'Legumes are the foundation of vegetarian protein',
      },
      {
        ingredient: 'quinoa',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Complete protein grain for vegetarian adaptations',
        usage: 'Bowls, salads, main dishes, side dishes',
        culturalContext:
          'Quinoa is a complete protein essential for vegetarian diets',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein and healthy fats for vegetarian adaptations',
        usage: 'Snacks, main dishes, desserts, side dishes',
        culturalContext: 'Nuts provide essential healthy fats and protein',
      },
      {
        ingredient: 'seeds',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein and healthy fats for vegetarian adaptations',
        usage: 'Snacks, main dishes, desserts, side dishes',
        culturalContext: 'Seeds provide essential healthy fats and protein',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for vegetarian adaptations',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext:
          'Vegetables are the foundation of vegetarian adaptations',
      },
      {
        ingredient: 'fruits',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for vegetarian adaptations',
        usage: 'Desserts, snacks, main dishes, side dishes',
        culturalContext: 'Fruits provide natural sweetness and nutrients',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for vegetarian adaptations',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Herbs add flavor and nutrients to vegetarian dishes',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for vegetarian adaptations',
        usage: 'Marinades, main dishes, everything',
        culturalContext: 'Spices add depth and flavor to vegetarian dishes',
      },
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fat for vegetarian adaptations',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext:
          'Olive oil is the primary healthy fat in vegetarian cooking',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for vegetarian adaptations',
        usage: 'Marinades, sauces, main dishes, aromatics',
        culturalContext: 'Foundation of vegetarian flavor building',
      },
      {
        ingredient: 'grains',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular vegetarian adaptation ingredients',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Important in vegetarian adaptation cuisine',
      },
      {
        ingredient: 'mushrooms',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular vegetarian adaptation ingredients',
        usage: 'Main dishes, side dishes, appetizers',
        culturalContext: 'Important in vegetarian adaptation cuisine',
      },
      {
        ingredient: 'avocado',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular vegetarian adaptation ingredient',
        usage: 'Salads, toast, smoothies, main dishes, garnishes',
        culturalContext: 'Important in vegetarian adaptation cuisine',
      },
      {
        ingredient: 'coconut',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular vegetarian adaptation ingredient',
        usage: 'Desserts, main dishes, beverages, snacks',
        culturalContext: 'Important in vegetarian adaptation cuisine',
      },
    ],
  },
};
