import { CuisineStaplesData } from '../cuisine-staples';

export const europeanCuisines: Record<string, CuisineStaplesData> = {
  portuguese: {
    cuisine: 'Portuguese',
    description:
      'Essential ingredients for authentic Portuguese cooking with bacalhau and pastéis de nata',
    subStyles: [
      'Lisbon',
      'Porto',
      'Algarve',
      'Traditional Portuguese',
      'Modern Portuguese',
    ],
    staples: [
      {
        ingredient: 'cod',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Portuguese cuisine',
        usage: 'Bacalhau, main dishes, stews, side dishes',
        culturalContext: 'Cod is the soul of Portuguese cuisine',
      },
      {
        ingredient: 'olive oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential cooking oil for Portuguese cuisine',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Portuguese cooking',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Portuguese cooking',
        usage: 'Bacalhau, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Portuguese flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Portuguese cooking',
        usage: 'Bacalhau, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Portuguese flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Portuguese dishes',
        usage: 'Bacalhau, stews, main dishes, sauces',
        culturalContext: 'Essential for authentic Portuguese dishes',
      },
      {
        ingredient: 'potatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Portuguese cuisine',
        usage: 'Bacalhau, main dishes, side dishes, soups',
        culturalContext: 'Potatoes are essential for Portuguese bacalhau',
      },
      {
        ingredient: 'eggs',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Portuguese cuisine',
        usage: 'Pastéis de nata, baking, main dishes, desserts',
        culturalContext: 'Essential for Portuguese pastries and desserts',
      },
      {
        ingredient: 'flour',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for Portuguese baking and cooking',
        usage: 'Pastéis de nata, bread, pastries, dumplings',
        culturalContext: 'Portuguese flour is essential for authentic baking',
      },
      {
        ingredient: 'sugar',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential sweetener for Portuguese cuisine',
        usage: 'Pastéis de nata, desserts, baking, main dishes',
        culturalContext: 'Essential for Portuguese pastries and desserts',
      },
      {
        ingredient: 'milk',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Portuguese cuisine',
        usage: 'Pastéis de nata, desserts, beverages, main dishes',
        culturalContext: 'Essential for Portuguese pastries and desserts',
      },
      {
        ingredient: 'butter',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential cooking fat for Portuguese cuisine',
        usage: 'Cooking, baking, sauces, finishing',
        culturalContext: 'Essential for authentic Portuguese richness',
      },
      {
        ingredient: 'bay leaves',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential herb for Portuguese cooking',
        usage: 'Bacalhau, stews, marinades, main dishes',
        culturalContext:
          'Cannot make authentic Portuguese bacalhau without bay leaves',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Portuguese ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Portuguese wine is important in the cuisine',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Portuguese ingredients',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Important in Portuguese cuisine',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Portuguese ingredients',
        usage: 'Marinades, stews, main dishes, everything',
        culturalContext: 'Important in Portuguese cuisine',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Portuguese ingredients',
        usage: 'Stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Important in Portuguese cuisine',
      },
    ],
  },
  belgian: {
    cuisine: 'Belgian',
    description:
      'Essential ingredients for authentic Belgian cooking with moules-frites and waffles',
    subStyles: [
      'Brussels',
      'Antwerp',
      'Ghent',
      'Traditional Belgian',
      'Modern Belgian',
    ],
    staples: [
      {
        ingredient: 'mussels',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Belgian cuisine',
        usage: 'Moules-frites, main dishes, stews, side dishes',
        culturalContext: 'Mussels are the soul of Belgian cuisine',
      },
      {
        ingredient: 'potatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Belgian cuisine',
        usage: 'Moules-frites, main dishes, side dishes, soups',
        culturalContext: 'Potatoes are essential for Belgian moules-frites',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Belgian cooking',
        usage: 'Moules-frites, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Belgian flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Belgian cooking',
        usage: 'Moules-frites, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Belgian flavor building',
      },
      {
        ingredient: 'white wine',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential liquid for Belgian cuisine',
        usage: 'Moules-frites, cooking, marinades, sauces',
        culturalContext: 'Essential for authentic Belgian moules-frites',
      },
      {
        ingredient: 'butter',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential cooking fat for Belgian cuisine',
        usage: 'Cooking, baking, sauces, finishing',
        culturalContext: 'Essential for authentic Belgian richness',
      },
      {
        ingredient: 'flour',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for Belgian baking and cooking',
        usage: 'Waffles, bread, pastries, dumplings',
        culturalContext: 'Belgian flour is essential for authentic baking',
      },
      {
        ingredient: 'eggs',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Belgian cuisine',
        usage: 'Waffles, baking, main dishes, desserts',
        culturalContext: 'Essential for Belgian waffles and baking',
      },
      {
        ingredient: 'sugar',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential sweetener for Belgian cuisine',
        usage: 'Waffles, desserts, baking, main dishes',
        culturalContext: 'Essential for Belgian waffles and desserts',
      },
      {
        ingredient: 'milk',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Belgian cuisine',
        usage: 'Waffles, desserts, beverages, main dishes',
        culturalContext: 'Essential for Belgian waffles and desserts',
      },
      {
        ingredient: 'chocolate',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential ingredient for Belgian cuisine',
        usage: 'Desserts, beverages, main dishes, side dishes',
        culturalContext: 'Belgian chocolate is world-famous',
      },
      {
        ingredient: 'beer',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential beverage for Belgian cuisine',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Belgian beer is world-famous',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Belgian ingredients',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Important in Belgian cuisine',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Belgian ingredients',
        usage: 'Marinades, stews, main dishes, everything',
        culturalContext: 'Important in Belgian cuisine',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Belgian ingredients',
        usage: 'Stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Important in Belgian cuisine',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'recommended',
        reason: 'Popular Belgian ingredient',
        usage: 'Main dishes, snacks, side dishes, traditional',
        culturalContext: 'Important in Belgian cuisine',
      },
    ],
  },
  swiss: {
    cuisine: 'Swiss',
    description:
      'Essential ingredients for authentic Swiss cooking with fondue and raclette',
    subStyles: [
      'Zurich',
      'Geneva',
      'Bern',
      'Traditional Swiss',
      'Modern Swiss',
    ],
    staples: [
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Swiss cuisine',
        usage: 'Fondue, raclette, main dishes, snacks, side dishes',
        culturalContext: 'Cheese is the soul of Swiss cuisine',
      },
      {
        ingredient: 'bread',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential staple for Swiss cuisine',
        usage: 'Fondue, raclette, main dishes, side dishes, snacks',
        culturalContext: 'Essential for Swiss fondue and raclette',
      },
      {
        ingredient: 'potatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Swiss cuisine',
        usage: 'Raclette, main dishes, side dishes, soups',
        culturalContext: 'Potatoes are essential for Swiss raclette',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Swiss cooking',
        usage: 'Fondue, raclette, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Swiss flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Swiss cooking',
        usage: 'Fondue, raclette, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Swiss flavor building',
      },
      {
        ingredient: 'white wine',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential liquid for Swiss cuisine',
        usage: 'Fondue, cooking, marinades, sauces',
        culturalContext: 'Essential for authentic Swiss fondue',
      },
      {
        ingredient: 'butter',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential cooking fat for Swiss cuisine',
        usage: 'Cooking, baking, sauces, finishing',
        culturalContext: 'Essential for authentic Swiss richness',
      },
      {
        ingredient: 'flour',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for Swiss baking and cooking',
        usage: 'Bread, pastries, dumplings, thickening',
        culturalContext: 'Swiss flour is essential for authentic baking',
      },
      {
        ingredient: 'eggs',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Swiss cuisine',
        usage: 'Baking, main dishes, desserts, side dishes',
        culturalContext: 'Essential for Swiss baking and main dishes',
      },
      {
        ingredient: 'milk',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Swiss cuisine',
        usage: 'Fondue, desserts, beverages, main dishes',
        culturalContext: 'Essential for Swiss fondue and desserts',
      },
      {
        ingredient: 'cream',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Swiss cuisine',
        usage: 'Fondue, sauces, desserts, main dishes, beverages',
        culturalContext: 'Essential for Swiss fondue and cream sauces',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Swiss ingredients',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Important in Swiss cuisine',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Swiss ingredients',
        usage: 'Marinades, stews, main dishes, everything',
        culturalContext: 'Important in Swiss cuisine',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Swiss ingredients',
        usage: 'Stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Important in Swiss cuisine',
      },
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Swiss protein',
        usage: 'Main dishes, stews, soups, side dishes',
        culturalContext: 'Important in Swiss cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Swiss ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Swiss wine is important in the cuisine',
      },
    ],
  },
};
