import { CuisineStaplesData } from '../cuisine-staples/types';

export const fusionCuisines: Record<string, CuisineStaplesData> = {
  modern_american: {
    cuisine: 'Modern American',
    description:
      'Essential ingredients for authentic Modern American cooking with contemporary and innovative flavors',
    subStyles: [
      'Contemporary American',
      'New American',
      'Fusion American',
      'Gourmet American',
      'Health-Conscious American',
    ],
    staples: [
      {
        ingredient: 'olive oil',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential Modern American ingredient',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext: 'Modern American cuisine emphasizes quality oils',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic',
        usage: 'Seasonings, marinades, main dishes',
        culturalContext: 'Foundation of Modern American flavor',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic',
        usage: 'Seasonings, marinades, main dishes',
        culturalContext: 'Foundation of Modern American flavor',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential Modern American ingredient',
        usage: 'Seasonings, garnishes, main dishes',
        culturalContext: 'Modern American cuisine emphasizes fresh herbs',
      },
      {
        ingredient: 'citrus',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential Modern American ingredient',
        usage: 'Juices, marinades, desserts, main dishes',
        culturalContext: 'Modern American cuisine emphasizes bright flavors',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential Modern American ingredient',
        usage: 'Salads, sauces, main dishes, side dishes',
        culturalContext: 'Modern American cuisine emphasizes fresh produce',
      },
      {
        ingredient: 'lettuce',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential Modern American ingredient',
        usage: 'Salads, wraps, main dishes, side dishes',
        culturalContext: 'Modern American cuisine emphasizes fresh greens',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential Modern American ingredient',
        usage: 'Salads, main dishes, side dishes, snacks',
        culturalContext: 'Modern American cuisine emphasizes quality cheese',
      },
      {
        ingredient: 'wine',
        category: 'beverages',
        priority: 'recommended',
        reason: 'Popular Modern American ingredient',
        usage: 'Cooking, marinades, beverages, desserts',
        culturalContext: 'Modern American cuisine incorporates wine',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Modern American ingredient',
        usage: 'Snacks, salads, desserts, main dishes',
        culturalContext: 'Modern American cuisine emphasizes nuts',
      },
      {
        ingredient: 'seafood',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Modern American ingredient',
        usage: 'Main dishes, salads, side dishes',
        culturalContext: 'Modern American cuisine emphasizes seafood',
      },
      {
        ingredient: 'bread',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Modern American ingredient',
        usage: 'Toast, sandwiches, side dishes',
        culturalContext: 'Modern American cuisine emphasizes quality bread',
      },
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Modern American ingredient',
        usage: 'Side dishes, main dishes, salads',
        culturalContext: 'Modern American cuisine incorporates rice',
      },
      {
        ingredient: 'beans',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Modern American ingredient',
        usage: 'Side dishes, main dishes, salads',
        culturalContext: 'Modern American cuisine incorporates beans',
      },
      {
        ingredient: 'honey',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Modern American ingredient',
        usage: 'Dressings, marinades, desserts, beverages',
        culturalContext: 'Important in Modern American cuisine',
      },
    ],
  },
};
