import { CuisineStaplesData } from '../cuisine-staples';

export const fusionCuisines: Record<string, CuisineStaplesData> = {
  tex_mex: {
    cuisine: 'Tex-Mex',
    description:
      'Essential ingredients for authentic Tex-Mex cooking with bold flavors and Mexican-American fusion',
    subStyles: [
      'Traditional Tex-Mex',
      'Modern Tex-Mex',
      'Spicy Tex-Mex',
      'Mild Tex-Mex',
      'Gourmet Tex-Mex',
    ],
    staples: [
      {
        ingredient: 'chili peppers',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential heat for Tex-Mex cuisine',
        usage: 'Chili, tacos, salsas, marinades, sauces',
        culturalContext: 'Tex-Mex cuisine is known for its bold heat',
      },
      {
        ingredient: 'cumin',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Signature spice for Tex-Mex flavor',
        usage: 'Chili, tacos, marinades, spice blends',
        culturalContext: 'Essential for authentic Tex-Mex spice profile',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Tex-Mex cooking',
        usage: 'Chili, tacos, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Tex-Mex flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Tex-Mex cooking',
        usage: 'Chili, tacos, salsas, main dishes, aromatics',
        culturalContext: 'Foundation of Tex-Mex flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Tex-Mex dishes',
        usage: 'Chili, salsas, tacos, main dishes, sauces',
        culturalContext: 'Essential for authentic Tex-Mex dishes',
      },
      {
        ingredient: 'cilantro',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Tex-Mex cuisine',
        usage: 'Garnishes, salsas, tacos, marinades',
        culturalContext: 'Cannot make authentic Tex-Mex food without cilantro',
      },
      {
        ingredient: 'lime',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for Tex-Mex cuisine',
        usage: 'Salsas, marinades, dressings, finishing',
        culturalContext: 'Essential for authentic Tex-Mex brightness',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Tex-Mex cuisine',
        usage: 'Tacos, nachos, quesadillas, main dishes, snacks',
        culturalContext: 'Essential for Tex-Mex tacos and nachos',
      },
      {
        ingredient: 'sour cream',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Tex-Mex cuisine',
        usage: 'Tacos, nachos, chili, main dishes, garnishes',
        culturalContext: 'Essential for Tex-Mex tacos and chili',
      },
      {
        ingredient: 'beans',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential legume for Tex-Mex cuisine',
        usage: 'Chili, tacos, burritos, main dishes, side dishes',
        culturalContext: 'Essential for Tex-Mex chili and tacos',
      },
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Tex-Mex meals',
        usage: 'Burritos, bowls, main dishes, side dishes',
        culturalContext: 'Foundation of Tex-Mex meals',
      },
      {
        ingredient: 'tortillas',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential staple for Tex-Mex cuisine',
        usage: 'Tacos, burritos, quesadillas, main dishes, snacks',
        culturalContext: 'Essential for Tex-Mex tacos and burritos',
      },
      {
        ingredient: 'avocado',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Tex-Mex ingredient',
        usage: 'Guacamole, tacos, salads, garnishes',
        culturalContext: 'Important in Tex-Mex cuisine',
      },
      {
        ingredient: 'jalapeños',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Tex-Mex pepper',
        usage: 'Salsas, marinades, garnishes, pickles',
        culturalContext: 'Important in Tex-Mex cuisine',
      },
      {
        ingredient: 'corn',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Tex-Mex ingredient',
        usage: 'Salsas, tacos, salads, side dishes',
        culturalContext: 'Important in Tex-Mex cuisine',
      },
      {
        ingredient: 'beef',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Tex-Mex protein',
        usage: 'Chili, tacos, burritos, main dishes',
        culturalContext: 'Important in Tex-Mex cuisine',
      },
    ],
  },
  california: {
    cuisine: 'California',
    description:
      'Essential ingredients for authentic California cooking with fresh, healthy, and innovative flavors',
    subStyles: [
      'Northern California',
      'Southern California',
      'Coastal California',
      'Farm-to-Table',
      'Modern California',
    ],
    staples: [
      {
        ingredient: 'avocado',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Signature California ingredient',
        usage: 'Salads, toast, smoothies, main dishes, garnishes',
        culturalContext: 'Avocado is the soul of California cuisine',
      },
      {
        ingredient: 'citrus',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for California cuisine',
        usage: 'Dressings, marinades, finishing, beverages',
        culturalContext: 'California is famous for its citrus',
      },
      {
        ingredient: 'olive oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential cooking oil for California cuisine',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext: 'California olive oil is world-renowned',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for California cuisine',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'California cuisine emphasizes fresh herbs',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for California cooking',
        usage: 'Marinades, sauces, main dishes, aromatics',
        culturalContext: 'Foundation of California flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for California cooking',
        usage: 'Salads, marinades, main dishes, aromatics',
        culturalContext: 'Foundation of California flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for California dishes',
        usage: 'Salads, salsas, main dishes, sauces',
        culturalContext: 'Essential for authentic California dishes',
      },
      {
        ingredient: 'lettuce',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential green for California cuisine',
        usage: 'Salads, wraps, main dishes, side dishes',
        culturalContext: 'Essential for California salads and wraps',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential ingredients for California cuisine',
        usage: 'Salads, main dishes, snacks, side dishes',
        culturalContext: 'California is famous for its nuts',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for California cuisine',
        usage: 'Salads, main dishes, snacks, side dishes',
        culturalContext: 'Essential for California salads and main dishes',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential beverage for California cuisine',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'California wine is world-famous',
      },
      {
        ingredient: 'seafood',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for California cuisine',
        usage: 'Main dishes, salads, appetizers, side dishes',
        culturalContext: 'California cuisine emphasizes fresh seafood',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular California ingredients',
        usage: 'Salads, stir-fries, main dishes, side dishes',
        culturalContext: 'Important in California cuisine',
      },
      {
        ingredient: 'grains',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular California ingredients',
        usage: 'Bowls, salads, main dishes, side dishes',
        culturalContext: 'Important in California cuisine',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular California ingredients',
        usage: 'Marinades, dressings, main dishes, everything',
        culturalContext: 'Important in California cuisine',
      },
      {
        ingredient: 'honey',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular California ingredient',
        usage: 'Dressings, marinades, desserts, beverages',
        culturalContext: 'California honey is important in the cuisine',
      },
    ],
  },
  modern_american: {
    cuisine: 'Modern American',
    description:
      'Essential ingredients for authentic Modern American cooking with contemporary techniques and global influences',
    subStyles: [
      'Contemporary American',
      'Farm-to-Table',
      'New American',
      'Gourmet American',
      'Fusion American',
    ],
    staples: [
      {
        ingredient: 'olive oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential cooking oil for Modern American cuisine',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Modern American cooking',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Modern American cooking',
        usage: 'Marinades, sauces, main dishes, aromatics',
        culturalContext: 'Foundation of Modern American flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Modern American cooking',
        usage: 'Sauces, marinades, main dishes, aromatics',
        culturalContext: 'Foundation of Modern American flavor building',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Modern American cuisine',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Modern American cuisine emphasizes fresh herbs',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Modern American cuisine',
        usage: 'Marinades, sauces, main dishes, everything',
        culturalContext: 'Essential for authentic Modern American flavor',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential beverage for Modern American cuisine',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Wine is essential in Modern American cooking',
      },
      {
        ingredient: 'butter',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential cooking fat for Modern American cuisine',
        usage: 'Cooking, baking, sauces, finishing',
        culturalContext: 'Essential for authentic Modern American richness',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Modern American cuisine',
        usage: 'Main dishes, appetizers, snacks, side dishes',
        culturalContext: 'Essential for Modern American main dishes',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Modern American cuisine',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Essential for authentic Modern American dishes',
      },
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Modern American cuisine',
        usage: 'Main dishes, appetizers, side dishes',
        culturalContext: 'Essential for Modern American main dishes',
      },
      {
        ingredient: 'seafood',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Modern American cuisine',
        usage: 'Main dishes, appetizers, side dishes',
        culturalContext: 'Essential for Modern American main dishes',
      },
      {
        ingredient: 'grains',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential staples for Modern American cuisine',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Essential for Modern American meals',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Modern American ingredients',
        usage: 'Salads, main dishes, snacks, side dishes',
        culturalContext: 'Important in Modern American cuisine',
      },
      {
        ingredient: 'citrus',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Modern American ingredients',
        usage: 'Dressings, marinades, finishing, beverages',
        culturalContext: 'Important in Modern American cuisine',
      },
      {
        ingredient: 'mushrooms',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Modern American ingredients',
        usage: 'Main dishes, side dishes, appetizers',
        culturalContext: 'Important in Modern American cuisine',
      },
      {
        ingredient: 'honey',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Modern American ingredient',
        usage: 'Dressings, marinades, desserts, beverages',
        culturalContext: 'Important in Modern American cuisine',
      },
    ],
  },
};
