import { CuisineStaplesData } from '../cuisine-staples/types';

export const healthFocusedCuisines: Record<string, CuisineStaplesData> = {
  mediterranean_diet: {
    cuisine: 'Mediterranean Diet',
    description:
      'Essential ingredients for authentic Mediterranean diet cooking with heart-healthy ingredients',
    subStyles: [
      'Traditional Mediterranean',
      'Modern Mediterranean',
      'Greek Mediterranean',
      'Italian Mediterranean',
      'Spanish Mediterranean',
    ],
    staples: [
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'The foundation of Mediterranean diet',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext:
          'Extra virgin olive oil is the heart of Mediterranean diet',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Mediterranean diet',
        usage: 'Main dishes, salads, appetizers, side dishes',
        culturalContext: 'Fish is the primary protein in Mediterranean diet',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Mediterranean diet',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Vegetables are the foundation of Mediterranean diet',
      },
      {
        ingredient: 'fruits',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Mediterranean diet',
        usage: 'Desserts, snacks, main dishes, side dishes',
        culturalContext: 'Fruits provide natural sweetness and antioxidants',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential healthy fats for Mediterranean diet',
        usage: 'Snacks, main dishes, desserts, side dishes',
        culturalContext: 'Nuts provide essential healthy fats and protein',
      },
      {
        ingredient: 'legumes',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein source for Mediterranean diet',
        usage: 'Main dishes, stews, salads, side dishes',
        culturalContext: 'Legumes are the foundation of Mediterranean protein',
      },
      {
        ingredient: 'whole_grains',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential staples for Mediterranean diet',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Whole grains are essential for Mediterranean diet',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Mediterranean diet',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext:
          'Herbs add flavor and nutrients to Mediterranean dishes',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Mediterranean diet',
        usage: 'Marinades, sauces, main dishes, aromatics',
        culturalContext: 'Foundation of Mediterranean flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Mediterranean diet',
        usage: 'Stews, main dishes, aromatics',
        culturalContext: 'Foundation of Mediterranean flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Mediterranean diet',
        usage: 'Salads, sauces, main dishes, everything',
        culturalContext: 'Essential for Mediterranean diet dishes',
      },
      {
        ingredient: 'citrus',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for Mediterranean diet',
        usage: 'Dressings, marinades, finishing, beverages',
        culturalContext: 'Essential for Mediterranean diet brightness',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Mediterranean diet ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Wine is important in Mediterranean diet culture',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'recommended',
        reason: 'Popular Mediterranean diet ingredient',
        usage: 'Main dishes, snacks, side dishes',
        culturalContext: 'Important in Mediterranean diet cuisine',
      },
      {
        ingredient: 'yogurt',
        category: 'dairy_cold',
        priority: 'recommended',
        reason: 'Popular Mediterranean diet ingredient',
        usage: 'Main dishes, desserts, beverages, snacks',
        culturalContext: 'Important in Mediterranean diet cuisine',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Mediterranean diet ingredients',
        usage: 'Marinades, main dishes, everything',
        culturalContext: 'Important in Mediterranean diet cuisine',
      },
    ],
  },
  nordic_diet: {
    cuisine: 'Nordic Diet',
    description:
      'Essential ingredients for authentic Nordic diet cooking with local, seasonal ingredients',
    subStyles: [
      'Traditional Nordic',
      'Modern Nordic',
      'Swedish Nordic',
      'Norwegian Nordic',
      'Danish Nordic',
    ],
    staples: [
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Nordic diet',
        usage: 'Main dishes, salads, appetizers, side dishes',
        culturalContext: 'Fish is the primary protein in Nordic diet',
      },
      {
        ingredient: 'berries',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential fruit for Nordic diet',
        usage: 'Desserts, snacks, main dishes, side dishes',
        culturalContext: 'Nordic berries are rich in antioxidants',
      },
      {
        ingredient: 'root_vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetables for Nordic diet',
        usage: 'Main dishes, side dishes, soups, everything',
        culturalContext: 'Root vegetables are the foundation of Nordic diet',
      },
      {
        ingredient: 'rye_bread',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential staple for Nordic diet',
        usage: 'Main dishes, side dishes, snacks',
        culturalContext: 'Rye bread is the foundation of Nordic diet',
      },
      {
        ingredient: 'oats',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential grain for Nordic diet',
        usage: 'Breakfast, main dishes, side dishes, desserts',
        culturalContext: 'Oats are essential for Nordic diet',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential healthy fats for Nordic diet',
        usage: 'Snacks, main dishes, desserts, side dishes',
        culturalContext: 'Nuts provide essential healthy fats and protein',
      },
      {
        ingredient: 'seeds',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential healthy fats for Nordic diet',
        usage: 'Snacks, main dishes, desserts, side dishes',
        culturalContext: 'Seeds provide essential healthy fats and protein',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Nordic diet',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Herbs add flavor and nutrients to Nordic dishes',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Nordic diet',
        usage: 'Marinades, sauces, main dishes, aromatics',
        culturalContext: 'Foundation of Nordic flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Nordic diet',
        usage: 'Stews, main dishes, aromatics',
        culturalContext: 'Foundation of Nordic flavor building',
      },
      {
        ingredient: 'citrus',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for Nordic diet',
        usage: 'Dressings, marinades, finishing, beverages',
        culturalContext: 'Essential for Nordic diet brightness',
      },
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fat for Nordic diet',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext: 'Olive oil is the primary healthy fat in Nordic diet',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Nordic diet ingredients',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Important in Nordic diet cuisine',
      },
      {
        ingredient: 'grains',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Nordic diet ingredients',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Important in Nordic diet cuisine',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Nordic diet ingredients',
        usage: 'Marinades, main dishes, everything',
        culturalContext: 'Important in Nordic diet cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Nordic diet ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Nordic wine is important in the cuisine',
      },
    ],
  },
  plant_based_health: {
    cuisine: 'Plant-Based Health',
    description:
      'Essential ingredients for authentic plant-based health cooking with nutrient-dense ingredients',
    subStyles: [
      'Whole Food Plant-Based',
      'Modern Plant-Based',
      'Raw Plant-Based',
      'Mediterranean Plant-Based',
      'Asian Plant-Based',
    ],
    staples: [
      {
        ingredient: 'leafy_greens',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential nutrient-dense ingredients for plant-based health',
        usage: 'Salads, main dishes, smoothies, side dishes',
        culturalContext:
          'Leafy greens are the foundation of plant-based health',
      },
      {
        ingredient: 'cruciferous_vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential nutrient-dense vegetables for plant-based health',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext:
          'Cruciferous vegetables are essential for plant-based health',
      },
      {
        ingredient: 'legumes',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein source for plant-based health',
        usage: 'Main dishes, stews, salads, side dishes',
        culturalContext:
          'Legumes are the foundation of plant-based health protein',
      },
      {
        ingredient: 'quinoa',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Complete protein grain for plant-based health',
        usage: 'Bowls, salads, main dishes, side dishes',
        culturalContext:
          'Quinoa is a complete protein essential for plant-based health',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein and healthy fats for plant-based health',
        usage: 'Snacks, main dishes, desserts, side dishes',
        culturalContext: 'Nuts provide essential healthy fats and protein',
      },
      {
        ingredient: 'seeds',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein and healthy fats for plant-based health',
        usage: 'Snacks, main dishes, desserts, side dishes',
        culturalContext: 'Seeds provide essential healthy fats and protein',
      },
      {
        ingredient: 'berries',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential antioxidant-rich fruits for plant-based health',
        usage: 'Desserts, snacks, main dishes, side dishes',
        culturalContext:
          'Berries are rich in antioxidants essential for plant-based health',
      },
      {
        ingredient: 'citrus',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vitamin C for plant-based health',
        usage: 'Dressings, marinades, finishing, beverages',
        culturalContext: 'Essential for plant-based health vitamin C',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for plant-based health',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext:
          'Herbs add flavor and nutrients to plant-based health dishes',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for plant-based health',
        usage: 'Marinades, main dishes, everything',
        culturalContext:
          'Spices add depth and flavor to plant-based health dishes',
      },
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fat for plant-based health',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext:
          'Olive oil is the primary healthy fat in plant-based health',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for plant-based health',
        usage: 'Marinades, sauces, main dishes, aromatics',
        culturalContext: 'Foundation of plant-based health flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular plant-based health ingredient',
        usage: 'Stews, main dishes, aromatics',
        culturalContext: 'Important in plant-based health cuisine',
      },
      {
        ingredient: 'mushrooms',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular plant-based health ingredient',
        usage: 'Main dishes, side dishes, appetizers',
        culturalContext: 'Important in plant-based health cuisine',
      },
      {
        ingredient: 'avocado',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular plant-based health ingredient',
        usage: 'Salads, toast, smoothies, main dishes, garnishes',
        culturalContext: 'Important in plant-based health cuisine',
      },
      {
        ingredient: 'coconut',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular plant-based health ingredient',
        usage: 'Desserts, main dishes, beverages, snacks',
        culturalContext: 'Important in plant-based health cuisine',
      },
    ],
  },
};
