import { CuisineStaplesData } from '../cuisine-staples/types';

export const internationalFusionCuisines: Record<string, CuisineStaplesData> = {
  korean_mexican: {
    cuisine: 'Korean-Mexican',
    description:
      'Essential ingredients for authentic Korean-Mexican fusion cooking with bold flavors and innovative combinations',
    subStyles: [
      'Traditional Korean-Mexican',
      'Modern Korean-Mexican',
      'Spicy Korean-Mexican',
      'Mild Korean-Mexican',
      'Gourmet Korean-Mexican',
    ],
    staples: [
      {
        ingredient: 'gochujang',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Signature Korean fermented chili paste for fusion',
        usage: 'Tacos, burritos, marinades, sauces',
        culturalContext: 'Gochujang is the soul of Korean-Mexican fusion',
      },
      {
        ingredient: 'kimchi',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential Korean ingredient for fusion',
        usage: 'Tacos, burritos, quesadillas, main dishes',
        culturalContext:
          'Kimchi adds authentic Korean flavor to Mexican dishes',
      },
      {
        ingredient: 'chili peppers',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential heat for Korean-Mexican fusion',
        usage: 'Tacos, burritos, salsas, marinades, sauces',
        culturalContext: 'Korean-Mexican fusion is known for its bold heat',
      },
      {
        ingredient: 'cilantro',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Korean-Mexican fusion',
        usage: 'Garnishes, salsas, tacos, marinades',
        culturalContext:
          'Cannot make authentic Korean-Mexican fusion without cilantro',
      },
      {
        ingredient: 'lime',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for Korean-Mexican fusion',
        usage: 'Salsas, marinades, dressings, finishing',
        culturalContext: 'Essential for authentic Korean-Mexican brightness',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Korean-Mexican fusion',
        usage: 'Tacos, burritos, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Korean-Mexican fusion flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Korean-Mexican fusion',
        usage: 'Tacos, burritos, salsas, main dishes, aromatics',
        culturalContext: 'Foundation of Korean-Mexican fusion flavor building',
      },
      {
        ingredient: 'sesame oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential Korean flavor and aroma',
        usage: 'Finishing oil, marinades, dressings, garnishes',
        culturalContext: 'Essential for authentic Korean-Mexican aroma',
      },
      {
        ingredient: 'soy sauce',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Fundamental seasoning for Korean-Mexican fusion',
        usage: 'Marinades, dipping sauces, tacos, burritos',
        culturalContext: 'Base seasoning for most Korean-Mexican fusion dishes',
      },
      {
        ingredient: 'tortillas',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential staple for Korean-Mexican fusion',
        usage: 'Tacos, burritos, quesadillas, main dishes, snacks',
        culturalContext:
          'Essential for Korean-Mexican fusion tacos and burritos',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Korean-Mexican fusion',
        usage: 'Tacos, burritos, quesadillas, main dishes, snacks',
        culturalContext:
          'Essential for Korean-Mexican fusion tacos and burritos',
      },
      {
        ingredient: 'avocado',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Korean-Mexican fusion',
        usage: 'Guacamole, tacos, burritos, salads, garnishes',
        culturalContext:
          'Essential for Korean-Mexican fusion tacos and burritos',
      },
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Korean-Mexican fusion ingredient',
        usage: 'Burritos, bowls, main dishes, side dishes',
        culturalContext: 'Important in Korean-Mexican fusion cuisine',
      },
      {
        ingredient: 'beans',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Korean-Mexican fusion ingredient',
        usage: 'Burritos, tacos, main dishes, side dishes',
        culturalContext: 'Important in Korean-Mexican fusion cuisine',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Korean-Mexican fusion ingredients',
        usage: 'Marinades, tacos, burritos, main dishes, everything',
        culturalContext: 'Important in Korean-Mexican fusion cuisine',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Korean-Mexican fusion ingredients',
        usage: 'Tacos, burritos, salads, main dishes, side dishes',
        culturalContext: 'Important in Korean-Mexican fusion cuisine',
      },
    ],
  },
  indian_chinese: {
    cuisine: 'Indian-Chinese',
    description:
      'Essential ingredients for authentic Indian-Chinese fusion cooking with bold spices and Chinese techniques',
    subStyles: [
      'Traditional Indian-Chinese',
      'Modern Indian-Chinese',
      'Spicy Indian-Chinese',
      'Mild Indian-Chinese',
      'Gourmet Indian-Chinese',
    ],
    staples: [
      {
        ingredient: 'soy sauce',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Fundamental seasoning for Indian-Chinese fusion',
        usage: 'Stir-fries, marinades, dipping sauces, cooking',
        culturalContext: 'The backbone of Indian-Chinese fusion flavor profile',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Indian-Chinese fusion',
        usage: 'Stir-fries, marinades, teas, health benefits',
        culturalContext:
          'Medicinal and culinary importance in Indian-Chinese fusion culture',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Indian-Chinese fusion',
        usage: 'Stir-fries, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Indian-Chinese fusion flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Indian-Chinese fusion',
        usage: 'Stir-fries, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Indian-Chinese fusion flavor building',
      },
      {
        ingredient: 'chili peppers',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential heat for Indian-Chinese fusion',
        usage: 'Stir-fries, marinades, sauces, main dishes',
        culturalContext: 'Indian-Chinese fusion is known for its heat',
      },
      {
        ingredient: 'cumin',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Indian-Chinese fusion',
        usage: 'Stir-fries, marinades, spice blends, main dishes',
        culturalContext:
          'Essential for authentic Indian-Chinese fusion spice profile',
      },
      {
        ingredient: 'turmeric',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Indian-Chinese fusion',
        usage: 'Stir-fries, marinades, main dishes',
        culturalContext:
          'Essential for authentic Indian-Chinese fusion color and flavor',
      },
      {
        ingredient: 'coriander',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Indian-Chinese fusion',
        usage: 'Garnishes, marinades, main dishes, salads',
        culturalContext:
          'Cannot make authentic Indian-Chinese fusion food without coriander',
      },
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Indian-Chinese fusion meals',
        usage: 'Fried rice, main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of Indian-Chinese fusion meals',
      },
      {
        ingredient: 'noodles',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for Indian-Chinese fusion noodle dishes',
        usage: 'Hakka noodles, stir-fries, main dishes',
        culturalContext:
          'Essential for authentic Indian-Chinese fusion noodle dishes',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Indian-Chinese fusion',
        usage: 'Stir-fries, main dishes, side dishes, everything',
        culturalContext: 'Essential for authentic Indian-Chinese fusion dishes',
      },
      {
        ingredient: 'oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential cooking medium for Indian-Chinese fusion',
        usage: 'Stir-frying, cooking, marinades, finishing',
        culturalContext:
          'Essential for authentic Indian-Chinese fusion cooking',
      },
      {
        ingredient: 'vinegar',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Indian-Chinese fusion ingredient',
        usage: 'Dressings, marinades, pickles, sauces',
        culturalContext: 'Important in Indian-Chinese fusion cuisine',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Indian-Chinese fusion ingredients',
        usage: 'Marinades, stir-fries, main dishes, everything',
        culturalContext: 'Important in Indian-Chinese fusion cuisine',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Indian-Chinese fusion ingredients',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Important in Indian-Chinese fusion cuisine',
      },
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Indian-Chinese fusion protein',
        usage: 'Stir-fries, main dishes, appetizers, side dishes',
        culturalContext: 'Important in Indian-Chinese fusion cuisine',
      },
    ],
  },
  mediterranean_american: {
    cuisine: 'Mediterranean-American',
    description:
      'Essential ingredients for authentic Mediterranean-American fusion cooking with healthy flavors and American techniques',
    subStyles: [
      'Traditional Mediterranean-American',
      'Modern Mediterranean-American',
      'Coastal Mediterranean-American',
      'Farm Mediterranean-American',
      'Gourmet Mediterranean-American',
    ],
    staples: [
      {
        ingredient: 'olive oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'The foundation of Mediterranean-American fusion',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext:
          'Extra virgin olive oil is sacred in Mediterranean-American fusion cooking',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Mediterranean-American fusion',
        usage: 'Marinades, sauces, main dishes, aromatics',
        culturalContext:
          'Foundation of Mediterranean-American fusion flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Mediterranean-American fusion',
        usage: 'Salads, marinades, main dishes, aromatics',
        culturalContext:
          'Foundation of Mediterranean-American fusion flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential Mediterranean ingredient',
        usage: 'Salads, sauces, main dishes, everything',
        culturalContext:
          'Essential for authentic Mediterranean-American fusion dishes',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Mediterranean-American fusion',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Mediterranean-American fusion emphasizes fresh herbs',
      },
      {
        ingredient: 'lemon',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for Mediterranean-American fusion',
        usage: 'Dressings, marinades, finishing, desserts',
        culturalContext:
          'Essential for authentic Mediterranean-American fusion brightness',
      },
      {
        ingredient: 'olives',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential Mediterranean ingredient',
        usage: 'Appetizers, salads, main dishes, garnishes',
        culturalContext:
          'Olives are the soul of Mediterranean-American fusion cuisine',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Mediterranean-American fusion',
        usage: 'Salads, main dishes, appetizers, snacks',
        culturalContext:
          'Essential for Mediterranean-American fusion main dishes',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Mediterranean-American fusion',
        usage: 'Salads, main dishes, side dishes, everything',
        culturalContext:
          'Essential for authentic Mediterranean-American fusion dishes',
      },
      {
        ingredient: 'seafood',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Mediterranean-American fusion',
        usage: 'Main dishes, salads, appetizers, side dishes',
        culturalContext:
          'Mediterranean-American fusion emphasizes fresh seafood',
      },
      {
        ingredient: 'grains',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential staples for Mediterranean-American fusion',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Essential for Mediterranean-American fusion meals',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential beverage for Mediterranean-American fusion',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext:
          'Wine is essential in Mediterranean-American fusion culture',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Mediterranean-American fusion ingredients',
        usage: 'Salads, main dishes, snacks, side dishes',
        culturalContext: 'Important in Mediterranean-American fusion cuisine',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Mediterranean-American fusion ingredients',
        usage: 'Marinades, dressings, main dishes, everything',
        culturalContext: 'Important in Mediterranean-American fusion cuisine',
      },
      {
        ingredient: 'honey',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Mediterranean-American fusion ingredient',
        usage: 'Dressings, marinades, desserts, beverages',
        culturalContext: 'Important in Mediterranean-American fusion cuisine',
      },
      {
        ingredient: 'vinegar',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Mediterranean-American fusion ingredient',
        usage: 'Dressings, marinades, pickles, sauces',
        culturalContext: 'Important in Mediterranean-American fusion cuisine',
      },
    ],
  },
};
