import { CuisineStaplesData } from '../cuisine-staples';

export const middleEasternCuisines: Record<string, CuisineStaplesData> = {
  iranian: {
    cuisine: 'Iranian',
    description:
      'Essential ingredients for authentic Iranian cooking with kebabs and rice dishes',
    subStyles: [
      'Tehran',
      'Isfahan',
      'Shiraz',
      'Traditional Iranian',
      'Modern Iranian',
    ],
    staples: [
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Iranian meals',
        usage: 'Chelo, main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of Iranian meals',
      },
      {
        ingredient: 'saffron',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential spice for Iranian cuisine',
        usage: 'Chelo, stews, marinades, main dishes',
        culturalContext: 'Saffron is the soul of Iranian cuisine',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Iranian cooking',
        usage: 'Chelo, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Iranian flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Iranian cooking',
        usage: 'Chelo, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Iranian flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Iranian dishes',
        usage: 'Chelo, stews, main dishes, sauces',
        culturalContext: 'Essential for authentic Iranian dishes',
      },
      {
        ingredient: 'lamb',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Iranian cuisine',
        usage: 'Kebabs, stews, main dishes, side dishes',
        culturalContext: 'Lamb is the soul of Iranian cuisine',
      },
      {
        ingredient: 'yogurt',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Iranian cuisine',
        usage: 'Chelo, main dishes, desserts, beverages',
        culturalContext: 'Essential for Iranian chelo and desserts',
      },
      {
        ingredient: 'butter',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential cooking fat for Iranian cuisine',
        usage: 'Chelo, cooking, baking, sauces, finishing',
        culturalContext: 'Essential for authentic Iranian richness',
      },
      {
        ingredient: 'olive oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential cooking oil for Iranian cuisine',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Iranian cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Iranian cuisine',
        usage: 'Chelo, garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Cannot make authentic Iranian food without herbs',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Iranian cuisine',
        usage: 'Chelo, marinades, stews, main dishes, everything',
        culturalContext: 'Essential for authentic Iranian flavor',
      },
      {
        ingredient: 'lemon',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for Iranian cuisine',
        usage: 'Chelo, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Iranian brightness',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Iranian ingredients',
        usage: 'Stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Important in Iranian cuisine',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Iranian ingredients',
        usage: 'Desserts, main dishes, snacks, side dishes',
        culturalContext: 'Important in Iranian cuisine',
      },
      {
        ingredient: 'dried fruits',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Iranian ingredients',
        usage: 'Desserts, main dishes, snacks, side dishes',
        culturalContext: 'Important in Iranian cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Iranian ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Iranian wine is important in the cuisine',
      },
    ],
  },
  israeli: {
    cuisine: 'Israeli',
    description:
      'Essential ingredients for authentic Israeli cooking with falafel and hummus',
    subStyles: [
      'Tel Aviv',
      'Jerusalem',
      'Haifa',
      'Traditional Israeli',
      'Modern Israeli',
    ],
    staples: [
      {
        ingredient: 'chickpeas',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential legume for Israeli cuisine',
        usage: 'Falafel, hummus, stews, main dishes, side dishes',
        culturalContext: 'Chickpeas are the soul of Israeli cuisine',
      },
      {
        ingredient: 'tahini',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential paste for Israeli cuisine',
        usage: 'Hummus, falafel, dressings, marinades, main dishes',
        culturalContext: 'Tahini is essential for Israeli hummus and falafel',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Israeli cooking',
        usage: 'Falafel, hummus, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Israeli flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Israeli cooking',
        usage: 'Falafel, hummus, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Israeli flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Israeli dishes',
        usage: 'Falafel, hummus, stews, main dishes, sauces',
        culturalContext: 'Essential for authentic Israeli dishes',
      },
      {
        ingredient: 'cucumber',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Israeli cuisine',
        usage: 'Falafel, hummus, salads, main dishes, side dishes',
        culturalContext: 'Essential for Israeli falafel and salads',
      },
      {
        ingredient: 'lemon',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for Israeli cuisine',
        usage: 'Falafel, hummus, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Israeli brightness',
      },
      {
        ingredient: 'olive oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential cooking oil for Israeli cuisine',
        usage: 'Falafel, hummus, cooking, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Israeli cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Israeli cuisine',
        usage: 'Falafel, hummus, garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Cannot make authentic Israeli food without herbs',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Israeli cuisine',
        usage: 'Falafel, hummus, marinades, stews, main dishes, everything',
        culturalContext: 'Essential for authentic Israeli flavor',
      },
      {
        ingredient: 'bread',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential staple for Israeli cuisine',
        usage: 'Falafel, hummus, main dishes, side dishes, snacks',
        culturalContext: 'Essential for Israeli falafel and hummus',
      },
      {
        ingredient: 'eggs',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Israeli cuisine',
        usage: 'Falafel, baking, main dishes, desserts, side dishes',
        culturalContext: 'Essential for Israeli falafel and baking',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Israeli ingredients',
        usage: 'Falafel, hummus, stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Important in Israeli cuisine',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'recommended',
        reason: 'Popular Israeli ingredient',
        usage: 'Falafel, hummus, main dishes, snacks, side dishes',
        culturalContext: 'Important in Israeli cuisine',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Israeli ingredients',
        usage: 'Falafel, hummus, desserts, main dishes, snacks, side dishes',
        culturalContext: 'Important in Israeli cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Israeli ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Israeli wine is important in the cuisine',
      },
    ],
  },
  syrian: {
    cuisine: 'Syrian',
    description:
      'Essential ingredients for authentic Syrian cooking with kebabs and rice dishes',
    subStyles: [
      'Damascus',
      'Aleppo',
      'Homs',
      'Traditional Syrian',
      'Modern Syrian',
    ],
    staples: [
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Staple grain for Syrian meals',
        usage: 'Kebabs, main dishes, side dishes, everyday meals',
        culturalContext: 'Foundation of Syrian meals',
      },
      {
        ingredient: 'lamb',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Syrian cuisine',
        usage: 'Kebabs, stews, main dishes, side dishes',
        culturalContext: 'Lamb is the soul of Syrian cuisine',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Syrian cooking',
        usage: 'Kebabs, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Syrian flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Syrian cooking',
        usage: 'Kebabs, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Syrian flavor building',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Syrian dishes',
        usage: 'Kebabs, stews, main dishes, sauces',
        culturalContext: 'Essential for authentic Syrian dishes',
      },
      {
        ingredient: 'yogurt',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Syrian cuisine',
        usage: 'Kebabs, main dishes, desserts, beverages',
        culturalContext: 'Essential for Syrian kebabs and desserts',
      },
      {
        ingredient: 'butter',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential cooking fat for Syrian cuisine',
        usage: 'Kebabs, cooking, baking, sauces, finishing',
        culturalContext: 'Essential for authentic Syrian richness',
      },
      {
        ingredient: 'olive oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential cooking oil for Syrian cuisine',
        usage: 'Kebabs, cooking, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Syrian cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Syrian cuisine',
        usage: 'Kebabs, garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Cannot make authentic Syrian food without herbs',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Syrian cuisine',
        usage: 'Kebabs, marinades, stews, main dishes, everything',
        culturalContext: 'Essential for authentic Syrian flavor',
      },
      {
        ingredient: 'lemon',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for Syrian cuisine',
        usage: 'Kebabs, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Syrian brightness',
      },
      {
        ingredient: 'bread',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential staple for Syrian cuisine',
        usage: 'Kebabs, main dishes, side dishes, snacks',
        culturalContext: 'Essential for Syrian kebabs and main dishes',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Syrian ingredients',
        usage: 'Kebabs, stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Important in Syrian cuisine',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Syrian ingredients',
        usage: 'Kebabs, desserts, main dishes, snacks, side dishes',
        culturalContext: 'Important in Syrian cuisine',
      },
      {
        ingredient: 'dried fruits',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Syrian ingredients',
        usage: 'Kebabs, desserts, main dishes, snacks, side dishes',
        culturalContext: 'Important in Syrian cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Syrian ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Syrian wine is important in the cuisine',
      },
    ],
  },
};
