import { CuisineStaplesData } from '../cuisine-staples';

export const regionalAmericanCuisines: Record<string, CuisineStaplesData> = {
  southern: {
    cuisine: 'Southern',
    description:
      'Essential ingredients for authentic Southern cooking with comfort food and traditional flavors',
    subStyles: [
      'Traditional Southern',
      'Modern Southern',
      'Cajun Southern',
      'Creole Southern',
      'Soul Food',
    ],
    staples: [
      {
        ingredient: 'butter',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential cooking fat for Southern cuisine',
        usage: 'Biscuits, cornbread, cooking, baking, sauces',
        culturalContext: 'Butter is the soul of Southern cooking',
      },
      {
        ingredient: 'flour',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for Southern baking and cooking',
        usage: 'Biscuits, cornbread, gravies, thickening',
        culturalContext: 'Southern flour is essential for authentic baking',
      },
      {
        ingredient: 'cornmeal',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential grain for Southern cuisine',
        usage: 'Cornbread, hush puppies, main dishes, side dishes',
        culturalContext: 'Cornmeal is the foundation of Southern cuisine',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Southern cooking',
        usage: 'Gravies, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Southern flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Southern cooking',
        usage: 'Gravies, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Southern flavor building',
      },
      {
        ingredient: 'bell peppers',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Southern cuisine',
        usage: 'Gumbo, jambalaya, main dishes, side dishes',
        culturalContext: 'Bell peppers are essential for Southern flavor',
      },
      {
        ingredient: 'celery',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Southern cuisine',
        usage: 'Gumbo, jambalaya, main dishes, side dishes',
        culturalContext: 'Celery is essential for Southern flavor',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Southern dishes',
        usage: 'Gravies, stews, main dishes, sauces',
        culturalContext: 'Essential for authentic Southern dishes',
      },
      {
        ingredient: 'bacon',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Southern cuisine',
        usage: 'Gravies, main dishes, side dishes, flavoring',
        culturalContext: 'Bacon is the soul of Southern flavor',
      },
      {
        ingredient: 'eggs',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Southern cuisine',
        usage: 'Biscuits, baking, main dishes, breakfast',
        culturalContext: 'Essential for Southern biscuits and baking',
      },
      {
        ingredient: 'milk',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Southern cuisine',
        usage: 'Biscuits, gravies, baking, beverages',
        culturalContext: 'Essential for Southern biscuits and gravies',
      },
      {
        ingredient: 'sugar',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential sweetener for Southern cuisine',
        usage: 'Desserts, baking, main dishes, beverages',
        culturalContext: 'Essential for Southern desserts and baking',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Southern ingredients',
        usage: 'Stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Important in Southern cuisine',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Southern ingredients',
        usage: 'Marinades, gravies, main dishes, everything',
        culturalContext: 'Important in Southern cuisine',
      },
      {
        ingredient: 'vinegar',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Southern ingredient',
        usage: 'Dressings, marinades, pickles, sauces',
        culturalContext: 'Important in Southern cuisine',
      },
      {
        ingredient: 'hot sauce',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Southern ingredient',
        usage: 'Gravies, marinades, main dishes, everything',
        culturalContext: 'Important in Southern cuisine',
      },
    ],
  },
  new_england: {
    cuisine: 'New England',
    description:
      'Essential ingredients for authentic New England cooking with seafood and traditional flavors',
    subStyles: [
      'Traditional New England',
      'Modern New England',
      'Coastal New England',
      'Mountain New England',
      'Farm New England',
    ],
    staples: [
      {
        ingredient: 'lobster',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for New England cuisine',
        usage: 'Rolls, bisque, main dishes, appetizers',
        culturalContext: 'Lobster is the soul of New England cuisine',
      },
      {
        ingredient: 'clams',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for New England cuisine',
        usage: 'Chowder, fritters, main dishes, appetizers',
        culturalContext: 'Clams are essential for New England chowder',
      },
      {
        ingredient: 'cod',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for New England cuisine',
        usage: 'Fish and chips, main dishes, stews',
        culturalContext: 'Cod is essential for New England fish and chips',
      },
      {
        ingredient: 'potatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for New England cuisine',
        usage: 'Chowder, fish and chips, main dishes, side dishes',
        culturalContext: 'Potatoes are essential for New England chowder',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for New England cooking',
        usage: 'Chowder, stews, main dishes, aromatics',
        culturalContext: 'Foundation of New England flavor building',
      },
      {
        ingredient: 'celery',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for New England cuisine',
        usage: 'Chowder, stews, main dishes, side dishes',
        culturalContext: 'Celery is essential for New England chowder',
      },
      {
        ingredient: 'butter',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential cooking fat for New England cuisine',
        usage: 'Cooking, baking, sauces, finishing',
        culturalContext: 'Essential for authentic New England richness',
      },
      {
        ingredient: 'cream',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for New England cuisine',
        usage: 'Chowder, sauces, desserts, main dishes',
        culturalContext: 'Essential for New England chowder and cream sauces',
      },
      {
        ingredient: 'flour',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for New England baking and cooking',
        usage: 'Chowder, bread, pastries, thickening',
        culturalContext: 'New England flour is essential for authentic baking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for New England cuisine',
        usage: 'Chowder, garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Cannot make authentic New England food without herbs',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for New England cuisine',
        usage: 'Chowder, marinades, stews, main dishes, everything',
        culturalContext: 'Essential for authentic New England flavor',
      },
      {
        ingredient: 'bread',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential staple for New England cuisine',
        usage: 'Lobster rolls, main dishes, side dishes, snacks',
        culturalContext: 'Essential for New England lobster rolls',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular New England ingredients',
        usage: 'Chowder, stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Important in New England cuisine',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'recommended',
        reason: 'Popular New England ingredient',
        usage: 'Main dishes, snacks, side dishes',
        culturalContext: 'Important in New England cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular New England ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'New England wine is important in the cuisine',
      },
      {
        ingredient: 'maple syrup',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular New England ingredient',
        usage: 'Desserts, marinades, main dishes, beverages',
        culturalContext: 'New England maple syrup is world-famous',
      },
    ],
  },
  pacific_northwest: {
    cuisine: 'Pacific Northwest',
    description:
      'Essential ingredients for authentic Pacific Northwest cooking with fresh seafood and local ingredients',
    subStyles: [
      'Seattle',
      'Portland',
      'Coastal PNW',
      'Mountain PNW',
      'Farm PNW',
    ],
    staples: [
      {
        ingredient: 'salmon',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Pacific Northwest cuisine',
        usage: 'Grilled, smoked, main dishes, appetizers',
        culturalContext: 'Salmon is the soul of Pacific Northwest cuisine',
      },
      {
        ingredient: 'dungeness crab',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Pacific Northwest cuisine',
        usage: 'Cakes, bisque, main dishes, appetizers',
        culturalContext:
          'Dungeness crab is essential for Pacific Northwest cuisine',
      },
      {
        ingredient: 'oysters',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Pacific Northwest cuisine',
        usage: 'Raw, grilled, main dishes, appetizers',
        culturalContext: 'Oysters are essential for Pacific Northwest cuisine',
      },
      {
        ingredient: 'mushrooms',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for Pacific Northwest cuisine',
        usage: 'Main dishes, side dishes, appetizers, everything',
        culturalContext: 'Pacific Northwest is famous for its mushrooms',
      },
      {
        ingredient: 'berries',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential fruit for Pacific Northwest cuisine',
        usage: 'Desserts, main dishes, snacks, beverages',
        culturalContext: 'Pacific Northwest is famous for its berries',
      },
      {
        ingredient: 'apples',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential fruit for Pacific Northwest cuisine',
        usage: 'Desserts, main dishes, snacks, beverages',
        culturalContext: 'Pacific Northwest is famous for its apples',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Pacific Northwest cooking',
        usage: 'Stews, main dishes, aromatics',
        culturalContext: 'Foundation of Pacific Northwest flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Pacific Northwest cooking',
        usage: 'Marinades, sauces, main dishes',
        culturalContext: 'Foundation of Pacific Northwest flavor building',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Pacific Northwest cuisine',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext:
          'Cannot make authentic Pacific Northwest food without herbs',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Pacific Northwest cuisine',
        usage: 'Marinades, stews, main dishes, everything',
        culturalContext: 'Essential for authentic Pacific Northwest flavor',
      },
      {
        ingredient: 'olive oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential cooking oil for Pacific Northwest cuisine',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext: 'Essential for authentic Pacific Northwest cooking',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential beverage for Pacific Northwest cuisine',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Pacific Northwest wine is world-famous',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Pacific Northwest ingredients',
        usage: 'Stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Important in Pacific Northwest cuisine',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Pacific Northwest ingredients',
        usage: 'Desserts, main dishes, snacks, side dishes',
        culturalContext: 'Important in Pacific Northwest cuisine',
      },
      {
        ingredient: 'honey',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Pacific Northwest ingredient',
        usage: 'Desserts, marinades, beverages, main dishes',
        culturalContext: 'Pacific Northwest honey is important in the cuisine',
      },
      {
        ingredient: 'maple syrup',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Pacific Northwest ingredient',
        usage: 'Desserts, marinades, main dishes, beverages',
        culturalContext:
          'Pacific Northwest maple syrup is important in the cuisine',
      },
    ],
  },
};
