import { CuisineStaplesData } from '../cuisine-staples/types';

export const scandinavianCuisines: Record<string, CuisineStaplesData> = {
  norwegian: {
    cuisine: 'Norwegian',
    description:
      'Essential ingredients for authentic Norwegian cooking with gravlax and lutefisk',
    subStyles: [
      'Oslo',
      'Bergen',
      'Trondheim',
      'Traditional Norwegian',
      'Modern Norwegian',
    ],
    staples: [
      {
        ingredient: 'salmon',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Norwegian cuisine',
        usage: 'Gravlax, main dishes, soups, side dishes',
        culturalContext: 'Salmon is the soul of Norwegian cuisine',
      },
      {
        ingredient: 'potatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Norwegian cuisine',
        usage: 'Lutefisk, main dishes, side dishes, soups',
        culturalContext: 'Potatoes are essential for Norwegian lutefisk',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Norwegian cooking',
        usage: 'Gravlax, stews, main dishes, aromatics',
        culturalContext: 'Foundation of Norwegian flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Norwegian cooking',
        usage: 'Gravlax, marinades, sauces, main dishes',
        culturalContext: 'Foundation of Norwegian flavor building',
      },
      {
        ingredient: 'dill',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential herb for Norwegian cuisine',
        usage: 'Gravlax, garnishes, main dishes, salads',
        culturalContext: 'Cannot make authentic Norwegian food without dill',
      },
      {
        ingredient: 'salt',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasoning for Norwegian cuisine',
        usage: 'Gravlax, curing, main dishes, everything',
        culturalContext: 'Essential for Norwegian gravlax and curing',
      },
      {
        ingredient: 'sugar',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential sweetener for Norwegian cuisine',
        usage: 'Gravlax, desserts, marinades, main dishes',
        culturalContext: 'Essential for Norwegian gravlax and desserts',
      },
      {
        ingredient: 'butter',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential cooking fat for Norwegian cuisine',
        usage: 'Gravlax, cooking, baking, sauces, finishing',
        culturalContext: 'Essential for authentic Norwegian richness',
      },
      {
        ingredient: 'cream',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Norwegian cuisine',
        usage: 'Gravlax, sauces, desserts, main dishes, beverages',
        culturalContext: 'Essential for Norwegian gravlax and cream sauces',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Norwegian cuisine',
        usage: 'Gravlax, garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Cannot make authentic Norwegian food without herbs',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Norwegian cuisine',
        usage: 'Gravlax, marinades, stews, main dishes, everything',
        culturalContext: 'Essential for authentic Norwegian flavor',
      },
      {
        ingredient: 'bread',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential staple for Norwegian cuisine',
        usage: 'Gravlax, main dishes, side dishes, snacks',
        culturalContext: 'Essential for Norwegian gravlax and main dishes',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Norwegian ingredients',
        usage: 'Gravlax, stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Important in Norwegian cuisine',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Norwegian protein',
        usage: 'Gravlax, main dishes, soups, side dishes, traditional',
        culturalContext: 'Important in Norwegian cuisine',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'recommended',
        reason: 'Popular Norwegian ingredient',
        usage: 'Gravlax, main dishes, snacks, side dishes',
        culturalContext: 'Important in Norwegian cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Norwegian ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Norwegian wine is important in the cuisine',
      },
    ],
  },
  danish: {
    cuisine: 'Danish',
    description:
      'Essential ingredients for authentic Danish cooking with smørrebrød and pastries',
    subStyles: [
      'Copenhagen',
      'Aarhus',
      'Odense',
      'Traditional Danish',
      'Modern Danish',
    ],
    staples: [
      {
        ingredient: 'bread',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential staple for Danish cuisine',
        usage: 'Smørrebrød, main dishes, side dishes, snacks',
        culturalContext: 'Bread is the soul of Danish cuisine',
      },
      {
        ingredient: 'butter',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential cooking fat for Danish cuisine',
        usage: 'Smørrebrød, cooking, baking, sauces, finishing',
        culturalContext: 'Essential for authentic Danish richness',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Danish cuisine',
        usage: 'Smørrebrød, main dishes, snacks, side dishes',
        culturalContext: 'Essential for Danish smørrebrød and main dishes',
      },
      {
        ingredient: 'eggs',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Danish cuisine',
        usage: 'Smørrebrød, baking, main dishes, desserts',
        culturalContext: 'Essential for Danish smørrebrød and baking',
      },
      {
        ingredient: 'flour',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential for Danish baking and cooking',
        usage: 'Smørrebrød, bread, pastries, dumplings',
        culturalContext: 'Danish flour is essential for authentic baking',
      },
      {
        ingredient: 'sugar',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential sweetener for Danish cuisine',
        usage: 'Smørrebrød, desserts, baking, main dishes',
        culturalContext: 'Essential for Danish smørrebrød and desserts',
      },
      {
        ingredient: 'milk',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Danish cuisine',
        usage: 'Smørrebrød, baking, desserts, beverages',
        culturalContext: 'Essential for Danish smørrebrød and baking',
      },
      {
        ingredient: 'cream',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Danish cuisine',
        usage: 'Smørrebrød, sauces, desserts, main dishes, beverages',
        culturalContext: 'Essential for Danish smørrebrød and cream sauces',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Danish cuisine',
        usage: 'Smørrebrød, garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Cannot make authentic Danish food without herbs',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Danish cuisine',
        usage: 'Smørrebrød, marinades, stews, main dishes, everything',
        culturalContext: 'Essential for authentic Danish flavor',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Danish cuisine',
        usage: 'Smørrebrød, stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Essential for authentic Danish dishes',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Danish cuisine',
        usage: 'Smørrebrød, main dishes, soups, side dishes, traditional',
        culturalContext: 'Essential for Danish smørrebrød and main dishes',
      },
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular Danish protein',
        usage: 'Smørrebrød, main dishes, stews, soups, side dishes',
        culturalContext: 'Important in Danish cuisine',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Danish ingredients',
        usage: 'Smørrebrød, desserts, main dishes, snacks, side dishes',
        culturalContext: 'Important in Danish cuisine',
      },
      {
        ingredient: 'dried fruits',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Danish ingredients',
        usage: 'Smørrebrød, desserts, main dishes, snacks, side dishes',
        culturalContext: 'Important in Danish cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Danish ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Danish wine is important in the cuisine',
      },
    ],
  },
  finnish: {
    cuisine: 'Finnish',
    description:
      'Essential ingredients for authentic Finnish cooking with reindeer and rye bread',
    subStyles: [
      'Helsinki',
      'Tampere',
      'Turku',
      'Traditional Finnish',
      'Modern Finnish',
    ],
    staples: [
      {
        ingredient: 'rye bread',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential staple for Finnish cuisine',
        usage: 'Main dishes, side dishes, snacks',
        culturalContext: 'Rye bread is the soul of Finnish cuisine',
      },
      {
        ingredient: 'reindeer',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Finnish cuisine',
        usage: 'Main dishes, stews, soups, side dishes',
        culturalContext: 'Reindeer is the soul of Finnish cuisine',
      },
      {
        ingredient: 'potatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vegetable for Finnish cuisine',
        usage: 'Main dishes, side dishes, soups',
        culturalContext: 'Potatoes are essential for Finnish meals',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for Finnish cooking',
        usage: 'Stews, main dishes, aromatics',
        culturalContext: 'Foundation of Finnish flavor building',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Finnish cooking',
        usage: 'Marinades, sauces, main dishes',
        culturalContext: 'Foundation of Finnish flavor building',
      },
      {
        ingredient: 'butter',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential cooking fat for Finnish cuisine',
        usage: 'Cooking, baking, sauces, finishing',
        culturalContext: 'Essential for authentic Finnish richness',
      },
      {
        ingredient: 'cream',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for Finnish cuisine',
        usage: 'Sauces, desserts, main dishes, beverages',
        culturalContext: 'Essential for Finnish cream sauces and desserts',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Finnish cuisine',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Cannot make authentic Finnish food without herbs',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Finnish cuisine',
        usage: 'Marinades, stews, main dishes, everything',
        culturalContext: 'Essential for authentic Finnish flavor',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Finnish cuisine',
        usage: 'Stews, stir-fries, main dishes, side dishes',
        culturalContext: 'Essential for authentic Finnish dishes',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Finnish cuisine',
        usage: 'Main dishes, soups, side dishes, traditional',
        culturalContext: 'Essential for Finnish main dishes',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'recommended',
        reason: 'Popular Finnish ingredient',
        usage: 'Main dishes, snacks, side dishes',
        culturalContext: 'Important in Finnish cuisine',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Finnish ingredients',
        usage: 'Desserts, main dishes, snacks, side dishes',
        culturalContext: 'Important in Finnish cuisine',
      },
      {
        ingredient: 'dried fruits',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Finnish ingredients',
        usage: 'Desserts, main dishes, snacks, side dishes',
        culturalContext: 'Important in Finnish cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Finnish ingredient',
        usage: 'Cooking, marinades, sauces, drinking',
        culturalContext: 'Finnish wine is important in the cuisine',
      },
      {
        ingredient: 'berries',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Finnish ingredients',
        usage: 'Desserts, main dishes, snacks, side dishes',
        culturalContext: 'Important in Finnish cuisine',
      },
    ],
  },
};
