import { CuisineStaplesData } from '../cuisine-staples/types';

export const specialtyDietFurtherExpansions: Record<
  string,
  CuisineStaplesData
> = {
  aip: {
    cuisine: 'Autoimmune Protocol (AIP)',
    description:
      'Essential ingredients for authentic AIP cooking with elimination diet specialties',
    subStyles: [
      'Traditional AIP',
      'Modern AIP',
      'Mediterranean AIP',
      'Asian AIP',
      'American AIP',
    ],
    staples: [
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for AIP diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Meat is the foundation of AIP diet',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for AIP diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Fish is essential for AIP diet',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for AIP diet',
        usage: 'Main dishes, side dishes, everything',
        culturalContext: 'Vegetables are essential for AIP diet',
      },
      {
        ingredient: 'leafy_greens',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for AIP diet',
        usage: 'Main dishes, side dishes, everything',
        culturalContext: 'Leafy greens are essential for AIP diet',
      },
      {
        ingredient: 'coconut_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential fat for AIP diet',
        usage: 'Cooking, everything',
        culturalContext: 'Coconut oil is essential for AIP diet',
      },
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential fat for AIP diet',
        usage: 'Cooking, everything',
        culturalContext: 'Olive oil is essential for AIP diet',
      },
      {
        ingredient: 'avocado',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential healthy fat for AIP diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Avocado is essential for AIP diet',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for AIP diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Herbs add essential flavor to AIP dishes',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for AIP diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Garlic is essential for AIP diet flavor',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for AIP diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Onion is essential for AIP diet flavor',
      },
      {
        ingredient: 'citrus',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for AIP diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Citrus is essential for AIP diet brightness',
      },
      {
        ingredient: 'sea_salt',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasoning for AIP diet',
        usage: 'Seasoning, everything',
        culturalContext: 'Sea salt is essential for AIP diet',
      },
      {
        ingredient: 'bone_broth',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular AIP ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in AIP cuisine',
      },
      {
        ingredient: 'coconut',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular AIP ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in AIP cuisine',
      },
      {
        ingredient: 'sweet_potato',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular AIP ingredient',
        usage: 'Main dishes, side dishes, everything',
        culturalContext: 'Important in AIP cuisine',
      },
      {
        ingredient: 'carrots',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular AIP ingredient',
        usage: 'Main dishes, side dishes, everything',
        culturalContext: 'Important in AIP cuisine',
      },
    ],
  },
  low_fodmap: {
    cuisine: 'Low FODMAP',
    description:
      'Essential ingredients for authentic Low FODMAP cooking with digestive health specialties',
    subStyles: [
      'Traditional Low FODMAP',
      'Modern Low FODMAP',
      'Mediterranean Low FODMAP',
      'Asian Low FODMAP',
      'American Low FODMAP',
    ],
    staples: [
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential grain for Low FODMAP diet',
        usage: 'Main dishes, side dishes, everything',
        culturalContext: 'Rice is the foundation of Low FODMAP diet',
      },
      {
        ingredient: 'quinoa',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential grain for Low FODMAP diet',
        usage: 'Main dishes, side dishes, everything',
        culturalContext: 'Quinoa is essential for Low FODMAP diet',
      },
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Low FODMAP diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Meat is essential for Low FODMAP diet',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Low FODMAP diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Fish is essential for Low FODMAP diet',
      },
      {
        ingredient: 'eggs',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Low FODMAP diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Eggs are essential for Low FODMAP diet',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Low FODMAP diet',
        usage: 'Main dishes, side dishes, everything',
        culturalContext: 'Vegetables are essential for Low FODMAP diet',
      },
      {
        ingredient: 'leafy_greens',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Low FODMAP diet',
        usage: 'Main dishes, side dishes, everything',
        culturalContext: 'Leafy greens are essential for Low FODMAP diet',
      },
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential fat for Low FODMAP diet',
        usage: 'Cooking, everything',
        culturalContext: 'Olive oil is essential for Low FODMAP diet',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Low FODMAP diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Herbs add essential flavor to Low FODMAP dishes',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Low FODMAP diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Spices add essential flavor to Low FODMAP dishes',
      },
      {
        ingredient: 'garlic_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential flavor for Low FODMAP diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Garlic oil is essential for Low FODMAP diet flavor',
      },
      {
        ingredient: 'salt',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasoning for Low FODMAP diet',
        usage: 'Seasoning, everything',
        culturalContext: 'Salt is essential for Low FODMAP diet',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'recommended',
        reason: 'Popular Low FODMAP ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in Low FODMAP cuisine',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular Low FODMAP ingredient',
        usage: 'Snacks, main dishes, everything',
        culturalContext: 'Important in Low FODMAP cuisine',
      },
      {
        ingredient: 'citrus',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Low FODMAP ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in Low FODMAP cuisine',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Low FODMAP ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in Low FODMAP cuisine',
      },
    ],
  },
  anti_inflammatory: {
    cuisine: 'Anti-Inflammatory',
    description:
      'Essential ingredients for authentic anti-inflammatory cooking with inflammation-reducing specialties',
    subStyles: [
      'Traditional Anti-Inflammatory',
      'Modern Anti-Inflammatory',
      'Mediterranean Anti-Inflammatory',
      'Asian Anti-Inflammatory',
      'American Anti-Inflammatory',
    ],
    staples: [
      {
        ingredient: 'fatty_fish',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential omega-3 for anti-inflammatory diet',
        usage: 'Main dishes, everything',
        culturalContext:
          'Fatty fish is the foundation of anti-inflammatory diet',
      },
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fat for anti-inflammatory diet',
        usage: 'Cooking, everything',
        culturalContext: 'Olive oil is essential for anti-inflammatory diet',
      },
      {
        ingredient: 'avocado',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential healthy fat for anti-inflammatory diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Avocado is essential for anti-inflammatory diet',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential healthy fats for anti-inflammatory diet',
        usage: 'Snacks, main dishes, everything',
        culturalContext:
          'Nuts provide essential healthy fats for anti-inflammatory diet',
      },
      {
        ingredient: 'seeds',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential healthy fats for anti-inflammatory diet',
        usage: 'Snacks, main dishes, everything',
        culturalContext:
          'Seeds provide essential healthy fats for anti-inflammatory diet',
      },
      {
        ingredient: 'leafy_greens',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for anti-inflammatory diet',
        usage: 'Main dishes, side dishes, everything',
        culturalContext:
          'Leafy greens are essential for anti-inflammatory diet',
      },
      {
        ingredient: 'berries',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential antioxidants for anti-inflammatory diet',
        usage: 'Main dishes, side dishes, everything',
        culturalContext:
          'Berries provide essential antioxidants for anti-inflammatory diet',
      },
      {
        ingredient: 'turmeric',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential anti-inflammatory spice',
        usage: 'Main dishes, everything',
        culturalContext: 'Turmeric is essential for anti-inflammatory diet',
      },
      {
        ingredient: 'ginger',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential anti-inflammatory ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Ginger is essential for anti-inflammatory diet',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential anti-inflammatory ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Garlic is essential for anti-inflammatory diet',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for anti-inflammatory diet',
        usage: 'Main dishes, everything',
        culturalContext:
          'Herbs add essential flavor to anti-inflammatory dishes',
      },
      {
        ingredient: 'citrus',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential vitamin C for anti-inflammatory diet',
        usage: 'Main dishes, everything',
        culturalContext:
          'Citrus provides essential vitamin C for anti-inflammatory diet',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular anti-inflammatory ingredient',
        usage: 'Main dishes, side dishes, everything',
        culturalContext: 'Important in anti-inflammatory cuisine',
      },
      {
        ingredient: 'green_tea',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular anti-inflammatory ingredient',
        usage: 'Beverages, everything',
        culturalContext: 'Important in anti-inflammatory cuisine',
      },
      {
        ingredient: 'dark_chocolate',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular anti-inflammatory ingredient',
        usage: 'Desserts, everything',
        culturalContext: 'Important in anti-inflammatory cuisine',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular anti-inflammatory ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in anti-inflammatory cuisine',
      },
    ],
  },
};
