import { CuisineStaplesData } from '../cuisine-staples/types';

export const specialtyCookingMethods: Record<string, CuisineStaplesData> = {
  grilled: {
    cuisine: 'Grilled',
    description:
      'Essential ingredients for authentic grilled cooking with BBQ and outdoor cooking specialties',
    subStyles: [
      'Traditional BBQ',
      'Modern Grilling',
      'Mediterranean Grilled',
      'Asian Grilled',
      'American BBQ',
    ],
    staples: [
      {
        ingredient: 'charcoal',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential fuel for authentic grilled cooking',
        usage: 'Grilling, smoking, BBQ, everything',
        culturalContext: 'Charcoal is the foundation of grilled cooking',
      },
      {
        ingredient: 'wood_chips',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential for smoking and flavor in grilled cooking',
        usage: 'Smoking, grilling, BBQ, everything',
        culturalContext:
          'Wood chips add essential smoke flavor to grilled dishes',
      },
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for grilled cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Meat is the foundation of grilled cooking',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for grilled cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Fish is essential for grilled cooking',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for grilled cooking',
        usage: 'Main dishes, side dishes, everything',
        culturalContext: 'Vegetables are essential for grilled cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for grilled cooking',
        usage: 'Marinades, rubs, garnishes, everything',
        culturalContext: 'Herbs add essential flavor to grilled dishes',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for grilled cooking',
        usage: 'Rubs, marinades, everything',
        culturalContext: 'Spices add depth and flavor to grilled dishes',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for grilled cooking',
        usage: 'Marinades, rubs, everything',
        culturalContext: 'Foundation of grilled flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for grilled cooking',
        usage: 'Marinades, side dishes, everything',
        culturalContext: 'Foundation of grilled flavor building',
      },
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential oil for grilled cooking',
        usage: 'Marinades, basting, everything',
        culturalContext: 'Olive oil is essential for grilled cooking',
      },
      {
        ingredient: 'citrus',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for grilled cooking',
        usage: 'Marinades, finishing, everything',
        culturalContext: 'Essential for grilled brightness and flavor',
      },
      {
        ingredient: 'vinegar',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential acid for grilled cooking',
        usage: 'Marinades, sauces, everything',
        culturalContext: 'Vinegar adds essential acidity to grilled dishes',
      },
      {
        ingredient: 'salt',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular grilled ingredient',
        usage: 'Seasoning, rubs, everything',
        culturalContext: 'Important in grilled cuisine',
      },
      {
        ingredient: 'pepper',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular grilled ingredient',
        usage: 'Seasoning, rubs, everything',
        culturalContext: 'Important in grilled cuisine',
      },
      {
        ingredient: 'sugar',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular grilled ingredient',
        usage: 'Rubs, glazes, everything',
        culturalContext: 'Important in grilled cuisine',
      },
      {
        ingredient: 'mustard',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular grilled ingredient',
        usage: 'Marinades, sauces, everything',
        culturalContext: 'Important in grilled cuisine',
      },
    ],
  },
  slow_cooker: {
    cuisine: 'Slow Cooker',
    description:
      'Essential ingredients for authentic slow cooker cooking with braised and comfort food specialties',
    subStyles: [
      'Traditional Braised',
      'Modern Slow Cooker',
      'Mediterranean Slow Cooker',
      'Asian Slow Cooker',
      'American Comfort',
    ],
    staples: [
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for slow cooker cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Meat is the foundation of slow cooker cooking',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for slow cooker cooking',
        usage: 'Main dishes, side dishes, everything',
        culturalContext: 'Vegetables are essential for slow cooker cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for slow cooker cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Herbs add essential flavor to slow cooker dishes',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for slow cooker cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Spices add depth and flavor to slow cooker dishes',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for slow cooker cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Foundation of slow cooker flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for slow cooker cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Foundation of slow cooker flavor building',
      },
      {
        ingredient: 'stock',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential liquid for slow cooker cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Stock is essential for slow cooker cooking',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential liquid for slow cooker cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Wine adds depth to slow cooker dishes',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for slow cooker cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Tomatoes add essential flavor to slow cooker dishes',
      },
      {
        ingredient: 'potatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for slow cooker cooking',
        usage: 'Main dishes, side dishes, everything',
        culturalContext: 'Potatoes are essential for slow cooker cooking',
      },
      {
        ingredient: 'carrots',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for slow cooker cooking',
        usage: 'Main dishes, side dishes, everything',
        culturalContext: 'Carrots are essential for slow cooker cooking',
      },
      {
        ingredient: 'celery',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for slow cooker cooking',
        usage: 'Main dishes, side dishes, everything',
        culturalContext: 'Celery is essential for slow cooker cooking',
      },
      {
        ingredient: 'salt',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular slow cooker ingredient',
        usage: 'Seasoning, everything',
        culturalContext: 'Important in slow cooker cuisine',
      },
      {
        ingredient: 'pepper',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular slow cooker ingredient',
        usage: 'Seasoning, everything',
        culturalContext: 'Important in slow cooker cuisine',
      },
      {
        ingredient: 'bay_leaves',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular slow cooker ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in slow cooker cuisine',
      },
      {
        ingredient: 'thyme',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular slow cooker ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in slow cooker cuisine',
      },
    ],
  },
  one_pot: {
    cuisine: 'One-Pot',
    description:
      'Essential ingredients for authentic one-pot cooking with simple, easy, minimal cleanup specialties',
    subStyles: [
      'Traditional One-Pot',
      'Modern One-Pot',
      'Mediterranean One-Pot',
      'Asian One-Pot',
      'American One-Pot',
    ],
    staples: [
      {
        ingredient: 'rice',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential grain for one-pot cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Rice is the foundation of one-pot cooking',
      },
      {
        ingredient: 'pasta',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential grain for one-pot cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Pasta is essential for one-pot cooking',
      },
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for one-pot cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Meat is the foundation of one-pot cooking',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for one-pot cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Vegetables are essential for one-pot cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for one-pot cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Herbs add essential flavor to one-pot dishes',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for one-pot cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Spices add depth and flavor to one-pot dishes',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for one-pot cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Foundation of one-pot flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for one-pot cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Foundation of one-pot flavor building',
      },
      {
        ingredient: 'stock',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential liquid for one-pot cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Stock is essential for one-pot cooking',
      },
      {
        ingredient: 'tomatoes',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredient for one-pot cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Tomatoes add essential flavor to one-pot dishes',
      },
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential oil for one-pot cooking',
        usage: 'Cooking, everything',
        culturalContext: 'Olive oil is essential for one-pot cooking',
      },
      {
        ingredient: 'salt',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasoning for one-pot cooking',
        usage: 'Seasoning, everything',
        culturalContext: 'Salt is essential for one-pot cooking',
      },
      {
        ingredient: 'pepper',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular one-pot ingredient',
        usage: 'Seasoning, everything',
        culturalContext: 'Important in one-pot cuisine',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'recommended',
        reason: 'Popular one-pot ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in one-pot cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular one-pot ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in one-pot cuisine',
      },
      {
        ingredient: 'citrus',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular one-pot ingredient',
        usage: 'Finishing, everything',
        culturalContext: 'Important in one-pot cuisine',
      },
    ],
  },
};
