import { CuisineStaplesData } from '../cuisine-staples/types';

export const specialtyDietFinalExpansions: Record<string, CuisineStaplesData> =
  {
    whole30: {
      cuisine: 'Whole30',
      description:
        'Essential ingredients for authentic Whole30 cooking with 30-day elimination diet specialties',
      subStyles: [
        'Traditional Whole30',
        'Modern Whole30',
        'Mediterranean Whole30',
        'Asian Whole30',
        'American Whole30',
      ],
      staples: [
        {
          ingredient: 'meat',
          category: 'proteins',
          priority: 'essential',
          reason: 'Essential protein for Whole30 diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Meat is the foundation of Whole30 diet',
        },
        {
          ingredient: 'fish',
          category: 'proteins',
          priority: 'essential',
          reason: 'Essential protein for Whole30 diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Fish is essential for Whole30 diet',
        },
        {
          ingredient: 'eggs',
          category: 'proteins',
          priority: 'essential',
          reason: 'Essential protein for Whole30 diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Eggs are essential for Whole30 diet',
        },
        {
          ingredient: 'vegetables',
          category: 'fresh_produce',
          priority: 'essential',
          reason: 'Essential ingredients for Whole30 diet',
          usage: 'Main dishes, side dishes, everything',
          culturalContext: 'Vegetables are essential for Whole30 diet',
        },
        {
          ingredient: 'fruits',
          category: 'fresh_produce',
          priority: 'essential',
          reason: 'Essential ingredients for Whole30 diet',
          usage: 'Main dishes, side dishes, everything',
          culturalContext: 'Fruits are essential for Whole30 diet',
        },
        {
          ingredient: 'nuts',
          category: 'pantry_staples',
          priority: 'essential',
          reason: 'Essential healthy fats for Whole30 diet',
          usage: 'Snacks, main dishes, everything',
          culturalContext:
            'Nuts provide essential healthy fats for Whole30 diet',
        },
        {
          ingredient: 'seeds',
          category: 'pantry_staples',
          priority: 'essential',
          reason: 'Essential healthy fats for Whole30 diet',
          usage: 'Snacks, main dishes, everything',
          culturalContext:
            'Seeds provide essential healthy fats for Whole30 diet',
        },
        {
          ingredient: 'avocado',
          category: 'fresh_produce',
          priority: 'essential',
          reason: 'Essential healthy fat for Whole30 diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Avocado is essential for Whole30 diet',
        },
        {
          ingredient: 'olive_oil',
          category: 'flavor_builders',
          priority: 'essential',
          reason: 'Essential healthy fat for Whole30 diet',
          usage: 'Cooking, everything',
          culturalContext: 'Olive oil is essential for Whole30 diet',
        },
        {
          ingredient: 'coconut_oil',
          category: 'flavor_builders',
          priority: 'essential',
          reason: 'Essential healthy fat for Whole30 diet',
          usage: 'Cooking, everything',
          culturalContext: 'Coconut oil is essential for Whole30 diet',
        },
        {
          ingredient: 'herbs',
          category: 'fresh_produce',
          priority: 'essential',
          reason: 'Essential ingredients for Whole30 diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Herbs add essential flavor to Whole30 dishes',
        },
        {
          ingredient: 'spices',
          category: 'flavor_builders',
          priority: 'essential',
          reason: 'Essential seasonings for Whole30 diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Spices add essential flavor to Whole30 dishes',
        },
        {
          ingredient: 'garlic',
          category: 'fresh_produce',
          priority: 'essential',
          reason: 'Essential aromatic for Whole30 diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Garlic is essential for Whole30 diet flavor',
        },
        {
          ingredient: 'onion',
          category: 'fresh_produce',
          priority: 'recommended',
          reason: 'Popular Whole30 ingredient',
          usage: 'Main dishes, everything',
          culturalContext: 'Important in Whole30 cuisine',
        },
        {
          ingredient: 'citrus',
          category: 'fresh_produce',
          priority: 'recommended',
          reason: 'Popular Whole30 ingredient',
          usage: 'Main dishes, everything',
          culturalContext: 'Important in Whole30 cuisine',
        },
        {
          ingredient: 'sweet_potato',
          category: 'fresh_produce',
          priority: 'recommended',
          reason: 'Popular Whole30 ingredient',
          usage: 'Main dishes, side dishes, everything',
          culturalContext: 'Important in Whole30 cuisine',
        },
      ],
    },
    dash_diet: {
      cuisine: 'DASH Diet',
      description:
        'Essential ingredients for authentic DASH diet cooking with blood pressure management specialties',
      subStyles: [
        'Traditional DASH',
        'Modern DASH',
        'Mediterranean DASH',
        'Asian DASH',
        'American DASH',
      ],
      staples: [
        {
          ingredient: 'vegetables',
          category: 'fresh_produce',
          priority: 'essential',
          reason: 'Essential ingredients for DASH diet',
          usage: 'Main dishes, side dishes, everything',
          culturalContext: 'Vegetables are the foundation of DASH diet',
        },
        {
          ingredient: 'fruits',
          category: 'fresh_produce',
          priority: 'essential',
          reason: 'Essential ingredients for DASH diet',
          usage: 'Main dishes, side dishes, everything',
          culturalContext: 'Fruits are essential for DASH diet',
        },
        {
          ingredient: 'whole_grains',
          category: 'pantry_staples',
          priority: 'essential',
          reason: 'Essential grains for DASH diet',
          usage: 'Main dishes, side dishes, everything',
          culturalContext: 'Whole grains are essential for DASH diet',
        },
        {
          ingredient: 'lean_protein',
          category: 'proteins',
          priority: 'essential',
          reason: 'Essential protein for DASH diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Lean protein is essential for DASH diet',
        },
        {
          ingredient: 'fish',
          category: 'proteins',
          priority: 'essential',
          reason: 'Essential protein for DASH diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Fish is essential for DASH diet',
        },
        {
          ingredient: 'nuts',
          category: 'pantry_staples',
          priority: 'essential',
          reason: 'Essential healthy fats for DASH diet',
          usage: 'Snacks, main dishes, everything',
          culturalContext: 'Nuts provide essential healthy fats for DASH diet',
        },
        {
          ingredient: 'seeds',
          category: 'pantry_staples',
          priority: 'essential',
          reason: 'Essential healthy fats for DASH diet',
          usage: 'Snacks, main dishes, everything',
          culturalContext: 'Seeds provide essential healthy fats for DASH diet',
        },
        {
          ingredient: 'legumes',
          category: 'pantry_staples',
          priority: 'essential',
          reason: 'Essential protein source for DASH diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Legumes are essential for DASH diet',
        },
        {
          ingredient: 'low_fat_dairy',
          category: 'dairy_cold',
          priority: 'essential',
          reason: 'Essential dairy for DASH diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Low-fat dairy is essential for DASH diet',
        },
        {
          ingredient: 'olive_oil',
          category: 'flavor_builders',
          priority: 'essential',
          reason: 'Essential healthy fat for DASH diet',
          usage: 'Cooking, everything',
          culturalContext: 'Olive oil is essential for DASH diet',
        },
        {
          ingredient: 'herbs',
          category: 'fresh_produce',
          priority: 'essential',
          reason: 'Essential ingredients for DASH diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Herbs add essential flavor to DASH dishes',
        },
        {
          ingredient: 'spices',
          category: 'flavor_builders',
          priority: 'essential',
          reason: 'Essential seasonings for DASH diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Spices add essential flavor to DASH dishes',
        },
        {
          ingredient: 'garlic',
          category: 'fresh_produce',
          priority: 'recommended',
          reason: 'Popular DASH ingredient',
          usage: 'Main dishes, everything',
          culturalContext: 'Important in DASH cuisine',
        },
        {
          ingredient: 'onion',
          category: 'fresh_produce',
          priority: 'recommended',
          reason: 'Popular DASH ingredient',
          usage: 'Main dishes, everything',
          culturalContext: 'Important in DASH cuisine',
        },
        {
          ingredient: 'citrus',
          category: 'fresh_produce',
          priority: 'recommended',
          reason: 'Popular DASH ingredient',
          usage: 'Main dishes, everything',
          culturalContext: 'Important in DASH cuisine',
        },
        {
          ingredient: 'avocado',
          category: 'fresh_produce',
          priority: 'recommended',
          reason: 'Popular DASH ingredient',
          usage: 'Main dishes, everything',
          culturalContext: 'Important in DASH cuisine',
        },
      ],
    },
    mind_diet: {
      cuisine: 'MIND Diet',
      description:
        'Essential ingredients for authentic MIND diet cooking with brain health and cognitive function specialties',
      subStyles: [
        'Traditional MIND',
        'Modern MIND',
        'Mediterranean MIND',
        'Asian MIND',
        'American MIND',
      ],
      staples: [
        {
          ingredient: 'leafy_greens',
          category: 'fresh_produce',
          priority: 'essential',
          reason: 'Essential brain health ingredients for MIND diet',
          usage: 'Main dishes, side dishes, everything',
          culturalContext: 'Leafy greens are the foundation of MIND diet',
        },
        {
          ingredient: 'berries',
          category: 'fresh_produce',
          priority: 'essential',
          reason: 'Essential antioxidants for MIND diet',
          usage: 'Main dishes, side dishes, everything',
          culturalContext:
            'Berries provide essential antioxidants for MIND diet',
        },
        {
          ingredient: 'nuts',
          category: 'pantry_staples',
          priority: 'essential',
          reason: 'Essential healthy fats for MIND diet',
          usage: 'Snacks, main dishes, everything',
          culturalContext: 'Nuts provide essential healthy fats for MIND diet',
        },
        {
          ingredient: 'olive_oil',
          category: 'flavor_builders',
          priority: 'essential',
          reason: 'Essential healthy fat for MIND diet',
          usage: 'Cooking, everything',
          culturalContext: 'Olive oil is essential for MIND diet',
        },
        {
          ingredient: 'fish',
          category: 'proteins',
          priority: 'essential',
          reason: 'Essential omega-3 for MIND diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Fish provides essential omega-3 for MIND diet',
        },
        {
          ingredient: 'poultry',
          category: 'proteins',
          priority: 'essential',
          reason: 'Essential protein for MIND diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Poultry is essential for MIND diet',
        },
        {
          ingredient: 'beans',
          category: 'pantry_staples',
          priority: 'essential',
          reason: 'Essential protein source for MIND diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Beans are essential for MIND diet',
        },
        {
          ingredient: 'whole_grains',
          category: 'pantry_staples',
          priority: 'essential',
          reason: 'Essential grains for MIND diet',
          usage: 'Main dishes, side dishes, everything',
          culturalContext: 'Whole grains are essential for MIND diet',
        },
        {
          ingredient: 'wine',
          category: 'flavor_builders',
          priority: 'essential',
          reason: 'Essential antioxidant for MIND diet',
          usage: 'Beverages, everything',
          culturalContext: 'Wine provides essential antioxidants for MIND diet',
        },
        {
          ingredient: 'vegetables',
          category: 'fresh_produce',
          priority: 'essential',
          reason: 'Essential ingredients for MIND diet',
          usage: 'Main dishes, side dishes, everything',
          culturalContext: 'Vegetables are essential for MIND diet',
        },
        {
          ingredient: 'herbs',
          category: 'fresh_produce',
          priority: 'essential',
          reason: 'Essential ingredients for MIND diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Herbs add essential flavor to MIND dishes',
        },
        {
          ingredient: 'spices',
          category: 'flavor_builders',
          priority: 'essential',
          reason: 'Essential seasonings for MIND diet',
          usage: 'Main dishes, everything',
          culturalContext: 'Spices add essential flavor to MIND dishes',
        },
        {
          ingredient: 'garlic',
          category: 'fresh_produce',
          priority: 'recommended',
          reason: 'Popular MIND ingredient',
          usage: 'Main dishes, everything',
          culturalContext: 'Important in MIND cuisine',
        },
        {
          ingredient: 'onion',
          category: 'fresh_produce',
          priority: 'recommended',
          reason: 'Popular MIND ingredient',
          usage: 'Main dishes, everything',
          culturalContext: 'Important in MIND cuisine',
        },
        {
          ingredient: 'citrus',
          category: 'fresh_produce',
          priority: 'recommended',
          reason: 'Popular MIND ingredient',
          usage: 'Main dishes, everything',
          culturalContext: 'Important in MIND cuisine',
        },
        {
          ingredient: 'avocado',
          category: 'fresh_produce',
          priority: 'recommended',
          reason: 'Popular MIND ingredient',
          usage: 'Main dishes, everything',
          culturalContext: 'Important in MIND cuisine',
        },
      ],
    },
  };
