import { CuisineStaplesData } from '../cuisine-staples/types';

export const specialtyDietExpansions: Record<string, CuisineStaplesData> = {
  intermittent_fasting: {
    cuisine: 'Intermittent Fasting',
    description:
      'Essential ingredients for authentic intermittent fasting cooking with time-restricted eating specialties',
    subStyles: [
      '16:8 Fasting',
      '18:6 Fasting',
      '20:4 Fasting',
      'OMAD (One Meal a Day)',
      '5:2 Fasting',
    ],
    staples: [
      {
        ingredient: 'protein',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for intermittent fasting',
        usage: 'Main dishes, everything',
        culturalContext:
          'Protein is the foundation of intermittent fasting nutrition',
      },
      {
        ingredient: 'healthy_fats',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fats for intermittent fasting',
        usage: 'Cooking, main dishes, everything',
        culturalContext:
          'Healthy fats are essential for intermittent fasting satiety',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for intermittent fasting',
        usage: 'Main dishes, side dishes, everything',
        culturalContext:
          'Vegetables are essential for intermittent fasting nutrition',
      },
      {
        ingredient: 'fruits',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for intermittent fasting',
        usage: 'Main dishes, side dishes, everything',
        culturalContext:
          'Fruits provide essential nutrients for intermittent fasting',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential healthy fats for intermittent fasting',
        usage: 'Snacks, main dishes, everything',
        culturalContext:
          'Nuts provide essential healthy fats for intermittent fasting',
      },
      {
        ingredient: 'seeds',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential healthy fats for intermittent fasting',
        usage: 'Snacks, main dishes, everything',
        culturalContext:
          'Seeds provide essential healthy fats for intermittent fasting',
      },
      {
        ingredient: 'avocado',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential healthy fat for intermittent fasting',
        usage: 'Main dishes, everything',
        culturalContext:
          'Avocado is essential for intermittent fasting satiety',
      },
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fat for intermittent fasting',
        usage: 'Cooking, everything',
        culturalContext:
          'Olive oil is essential for intermittent fasting cooking',
      },
      {
        ingredient: 'coconut_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fat for intermittent fasting',
        usage: 'Cooking, everything',
        culturalContext:
          'Coconut oil is essential for intermittent fasting cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for intermittent fasting',
        usage: 'Main dishes, everything',
        culturalContext:
          'Herbs add essential flavor to intermittent fasting dishes',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for intermittent fasting',
        usage: 'Main dishes, everything',
        culturalContext:
          'Spices add essential flavor to intermittent fasting dishes',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for intermittent fasting',
        usage: 'Main dishes, everything',
        culturalContext: 'Garlic is essential for intermittent fasting flavor',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular intermittent fasting ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in intermittent fasting cuisine',
      },
      {
        ingredient: 'citrus',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular intermittent fasting ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in intermittent fasting cuisine',
      },
      {
        ingredient: 'eggs',
        category: 'proteins',
        priority: 'recommended',
        reason: 'Popular intermittent fasting ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in intermittent fasting cuisine',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'recommended',
        reason: 'Popular intermittent fasting ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in intermittent fasting cuisine',
      },
    ],
  },
  carnivore: {
    cuisine: 'Carnivore Diet',
    description:
      'Essential ingredients for authentic carnivore diet cooking with animal-based nutrition specialties',
    subStyles: [
      'Traditional Carnivore',
      'Modern Carnivore',
      'Mediterranean Carnivore',
      'Asian Carnivore',
      'American Carnivore',
    ],
    staples: [
      {
        ingredient: 'beef',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for carnivore diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Beef is the foundation of carnivore diet',
      },
      {
        ingredient: 'lamb',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for carnivore diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Lamb is essential for carnivore diet',
      },
      {
        ingredient: 'pork',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for carnivore diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Pork is essential for carnivore diet',
      },
      {
        ingredient: 'chicken',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for carnivore diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Chicken is essential for carnivore diet',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for carnivore diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Fish is essential for carnivore diet',
      },
      {
        ingredient: 'eggs',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for carnivore diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Eggs are essential for carnivore diet',
      },
      {
        ingredient: 'organ_meats',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for carnivore diet',
        usage: 'Main dishes, everything',
        culturalContext:
          'Organ meats are essential for carnivore diet nutrition',
      },
      {
        ingredient: 'bone_broth',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential liquid for carnivore diet',
        usage: 'Main dishes, everything',
        culturalContext: 'Bone broth is essential for carnivore diet',
      },
      {
        ingredient: 'butter',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential fat for carnivore diet',
        usage: 'Cooking, everything',
        culturalContext: 'Butter is essential for carnivore diet',
      },
      {
        ingredient: 'lard',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential fat for carnivore diet',
        usage: 'Cooking, everything',
        culturalContext: 'Lard is essential for carnivore diet',
      },
      {
        ingredient: 'tallow',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential fat for carnivore diet',
        usage: 'Cooking, everything',
        culturalContext: 'Tallow is essential for carnivore diet',
      },
      {
        ingredient: 'salt',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasoning for carnivore diet',
        usage: 'Seasoning, everything',
        culturalContext: 'Salt is essential for carnivore diet',
      },
      {
        ingredient: 'pepper',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular carnivore diet ingredient',
        usage: 'Seasoning, everything',
        culturalContext: 'Important in carnivore diet cuisine',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular carnivore diet ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in carnivore diet cuisine',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular carnivore diet ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in carnivore diet cuisine',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'recommended',
        reason: 'Popular carnivore diet ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in carnivore diet cuisine',
      },
    ],
  },
  mediterranean_keto: {
    cuisine: 'Mediterranean Keto',
    description:
      'Essential ingredients for authentic Mediterranean keto cooking with Mediterranean diet and keto principles',
    subStyles: [
      'Traditional Mediterranean Keto',
      'Modern Mediterranean Keto',
      'Greek Mediterranean Keto',
      'Italian Mediterranean Keto',
      'Spanish Mediterranean Keto',
    ],
    staples: [
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fat for Mediterranean keto',
        usage: 'Cooking, everything',
        culturalContext: 'Olive oil is the foundation of Mediterranean keto',
      },
      {
        ingredient: 'coconut_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fat for Mediterranean keto',
        usage: 'Cooking, everything',
        culturalContext: 'Coconut oil is essential for Mediterranean keto',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Mediterranean keto',
        usage: 'Main dishes, everything',
        culturalContext: 'Fish is the foundation of Mediterranean keto',
      },
      {
        ingredient: 'seafood',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for Mediterranean keto',
        usage: 'Main dishes, everything',
        culturalContext: 'Seafood is essential for Mediterranean keto',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Mediterranean keto',
        usage: 'Main dishes, everything',
        culturalContext: 'Vegetables are essential for Mediterranean keto',
      },
      {
        ingredient: 'leafy_greens',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Mediterranean keto',
        usage: 'Main dishes, everything',
        culturalContext: 'Leafy greens are essential for Mediterranean keto',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential healthy fats for Mediterranean keto',
        usage: 'Snacks, main dishes, everything',
        culturalContext:
          'Nuts provide essential healthy fats for Mediterranean keto',
      },
      {
        ingredient: 'seeds',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential healthy fats for Mediterranean keto',
        usage: 'Snacks, main dishes, everything',
        culturalContext:
          'Seeds provide essential healthy fats for Mediterranean keto',
      },
      {
        ingredient: 'avocado',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential healthy fat for Mediterranean keto',
        usage: 'Main dishes, everything',
        culturalContext: 'Avocado is essential for Mediterranean keto',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for Mediterranean keto',
        usage: 'Main dishes, everything',
        culturalContext:
          'Herbs add essential flavor to Mediterranean keto dishes',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for Mediterranean keto',
        usage: 'Main dishes, everything',
        culturalContext:
          'Spices add essential flavor to Mediterranean keto dishes',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for Mediterranean keto',
        usage: 'Main dishes, everything',
        culturalContext: 'Garlic is essential for Mediterranean keto flavor',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Mediterranean keto ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in Mediterranean keto cuisine',
      },
      {
        ingredient: 'citrus',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular Mediterranean keto ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in Mediterranean keto cuisine',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'recommended',
        reason: 'Popular Mediterranean keto ingredient',
        usage: 'Main dishes, everything',
        culturalContext: 'Important in Mediterranean keto cuisine',
      },
      {
        ingredient: 'wine',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular Mediterranean keto ingredient',
        usage: 'Cooking, everything',
        culturalContext: 'Important in Mediterranean keto cuisine',
      },
    ],
  },
};
