import { CuisineStaplesData } from '../cuisine-staples/types';

export const specialtyDiets: Record<string, CuisineStaplesData> = {
  keto: {
    cuisine: 'Keto',
    description:
      'Essential ingredients for authentic keto cooking with low-carb, high-fat ingredients',
    subStyles: [
      'Traditional Keto',
      'Modern Keto',
      'Mediterranean Keto',
      'Asian Keto',
      'Dirty Keto',
    ],
    staples: [
      {
        ingredient: 'coconut_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential high-fat oil for keto cooking',
        usage: 'Cooking, baking, main dishes, everything',
        culturalContext: 'Coconut oil is the foundation of keto cooking',
      },
      {
        ingredient: 'butter',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential high-fat dairy for keto cooking',
        usage: 'Cooking, baking, main dishes, everything',
        culturalContext: 'Butter is essential for keto cooking',
      },
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fat for keto cooking',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext: 'Olive oil is the primary healthy fat in keto cooking',
      },
      {
        ingredient: 'avocado',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential high-fat fruit for keto cooking',
        usage: 'Salads, main dishes, snacks, everything',
        culturalContext: 'Avocado is the foundation of keto nutrition',
      },
      {
        ingredient: 'eggs',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein and fat for keto cooking',
        usage: 'Main dishes, breakfast, baking, everything',
        culturalContext: 'Eggs are the foundation of keto protein',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential high-fat dairy for keto cooking',
        usage: 'Main dishes, snacks, side dishes, everything',
        culturalContext: 'Cheese is essential for keto cooking',
      },
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for keto cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Meat is the foundation of keto protein',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein and omega-3 for keto cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Fish is essential for keto nutrition',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential healthy fats for keto cooking',
        usage: 'Snacks, main dishes, desserts, everything',
        culturalContext: 'Nuts provide essential healthy fats',
      },
      {
        ingredient: 'seeds',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential healthy fats for keto cooking',
        usage: 'Snacks, main dishes, desserts, everything',
        culturalContext: 'Seeds provide essential healthy fats',
      },
      {
        ingredient: 'leafy_greens',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential low-carb vegetables for keto cooking',
        usage: 'Salads, main dishes, side dishes, everything',
        culturalContext: 'Leafy greens are the foundation of keto vegetables',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for keto cooking',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Herbs add flavor and nutrients to keto dishes',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for keto cooking',
        usage: 'Marinades, main dishes, everything',
        culturalContext: 'Spices add depth and flavor to keto dishes',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular keto ingredient',
        usage: 'Marinades, sauces, main dishes, aromatics',
        culturalContext: 'Important in keto cuisine',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular keto ingredient',
        usage: 'Stews, main dishes, aromatics',
        culturalContext: 'Important in keto cuisine',
      },
      {
        ingredient: 'mushrooms',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular keto ingredient',
        usage: 'Main dishes, side dishes, appetizers',
        culturalContext: 'Important in keto cuisine',
      },
    ],
  },
  paleo: {
    cuisine: 'Paleo',
    description:
      'Essential ingredients for authentic paleo cooking with ancient grains and natural ingredients',
    subStyles: [
      'Traditional Paleo',
      'Modern Paleo',
      'Mediterranean Paleo',
      'Asian Paleo',
      'Primal Paleo',
    ],
    staples: [
      {
        ingredient: 'coconut_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential natural fat for paleo cooking',
        usage: 'Cooking, baking, main dishes, everything',
        culturalContext: 'Coconut oil is the foundation of paleo cooking',
      },
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fat for paleo cooking',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext:
          'Olive oil is the primary healthy fat in paleo cooking',
      },
      {
        ingredient: 'meat',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for paleo cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Meat is the foundation of paleo protein',
      },
      {
        ingredient: 'fish',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein and omega-3 for paleo cooking',
        usage: 'Main dishes, everything',
        culturalContext: 'Fish is essential for paleo nutrition',
      },
      {
        ingredient: 'eggs',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for paleo cooking',
        usage: 'Main dishes, breakfast, baking, everything',
        culturalContext: 'Eggs are essential for paleo protein',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for paleo cooking',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Vegetables are the foundation of paleo cooking',
      },
      {
        ingredient: 'fruits',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for paleo cooking',
        usage: 'Desserts, snacks, main dishes, side dishes',
        culturalContext: 'Fruits provide natural sweetness in paleo cooking',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential healthy fats for paleo cooking',
        usage: 'Snacks, main dishes, desserts, everything',
        culturalContext: 'Nuts provide essential healthy fats',
      },
      {
        ingredient: 'seeds',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential healthy fats for paleo cooking',
        usage: 'Snacks, main dishes, desserts, everything',
        culturalContext: 'Seeds provide essential healthy fats',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for paleo cooking',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Herbs add flavor and nutrients to paleo dishes',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for paleo cooking',
        usage: 'Marinades, main dishes, everything',
        culturalContext: 'Spices add depth and flavor to paleo dishes',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for paleo cooking',
        usage: 'Marinades, sauces, main dishes, aromatics',
        culturalContext: 'Foundation of paleo flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for paleo cooking',
        usage: 'Stews, main dishes, aromatics',
        culturalContext: 'Foundation of paleo flavor building',
      },
      {
        ingredient: 'coconut',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular paleo ingredient',
        usage: 'Desserts, main dishes, beverages, snacks',
        culturalContext: 'Important in paleo cuisine',
      },
      {
        ingredient: 'honey',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular paleo ingredient',
        usage: 'Desserts, marinades, beverages, main dishes',
        culturalContext: 'Important in paleo cuisine',
      },
      {
        ingredient: 'mushrooms',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular paleo ingredient',
        usage: 'Main dishes, side dishes, appetizers',
        culturalContext: 'Important in paleo cuisine',
      },
    ],
  },
  raw_food: {
    cuisine: 'Raw Food',
    description:
      'Essential ingredients for authentic raw food cooking with uncooked, natural ingredients',
    subStyles: [
      'Traditional Raw',
      'Modern Raw',
      'Mediterranean Raw',
      'Asian Raw',
      'Fruitarian Raw',
    ],
    staples: [
      {
        ingredient: 'fruits',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for raw food cooking',
        usage: 'Desserts, snacks, main dishes, side dishes',
        culturalContext: 'Fruits are the foundation of raw food cooking',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for raw food cooking',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Vegetables are the foundation of raw food cooking',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein and healthy fats for raw food cooking',
        usage: 'Snacks, main dishes, desserts, everything',
        culturalContext: 'Nuts provide essential protein and healthy fats',
      },
      {
        ingredient: 'seeds',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein and healthy fats for raw food cooking',
        usage: 'Snacks, main dishes, desserts, everything',
        culturalContext: 'Seeds provide essential protein and healthy fats',
      },
      {
        ingredient: 'avocado',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential high-fat fruit for raw food cooking',
        usage: 'Salads, main dishes, snacks, everything',
        culturalContext: 'Avocado is the foundation of raw food nutrition',
      },
      {
        ingredient: 'coconut',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential ingredient for raw food cooking',
        usage: 'Desserts, main dishes, beverages, snacks',
        culturalContext: 'Coconut is essential for raw food cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for raw food cooking',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Herbs add flavor and nutrients to raw food dishes',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for raw food cooking',
        usage: 'Marinades, main dishes, everything',
        culturalContext: 'Spices add depth and flavor to raw food dishes',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for raw food cooking',
        usage: 'Marinades, sauces, main dishes, aromatics',
        culturalContext: 'Foundation of raw food flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for raw food cooking',
        usage: 'Salads, main dishes, aromatics',
        culturalContext: 'Foundation of raw food flavor building',
      },
      {
        ingredient: 'citrus',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for raw food cooking',
        usage: 'Dressings, marinades, finishing, beverages',
        culturalContext: 'Essential for raw food brightness and flavor',
      },
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fat for raw food cooking',
        usage: 'Dressings, marinades, finishing',
        culturalContext:
          'Olive oil is the primary healthy fat in raw food cooking',
      },
      {
        ingredient: 'honey',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular raw food ingredient',
        usage: 'Desserts, marinades, beverages, main dishes',
        culturalContext: 'Important in raw food cuisine',
      },
      {
        ingredient: 'mushrooms',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular raw food ingredient',
        usage: 'Main dishes, side dishes, appetizers',
        culturalContext: 'Important in raw food cuisine',
      },
      {
        ingredient: 'seaweed',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular raw food ingredient',
        usage: 'Salads, main dishes, snacks, side dishes',
        culturalContext: 'Important in raw food cuisine',
      },
      {
        ingredient: 'sprouts',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular raw food ingredient',
        usage: 'Salads, main dishes, snacks, side dishes',
        culturalContext: 'Important in raw food cuisine',
      },
    ],
  },
};
