import { CuisineStaplesData } from '../cuisine-staples/types';

export const vegetarianCuisines: Record<string, CuisineStaplesData> = {
  plant_based: {
    cuisine: 'Plant-Based',
    description:
      'Essential ingredients for authentic plant-based cooking with whole foods and natural ingredients',
    subStyles: [
      'Whole Food Plant-Based',
      'Modern Plant-Based',
      'Raw Plant-Based',
      'Mediterranean Plant-Based',
      'Asian Plant-Based',
    ],
    staples: [
      {
        ingredient: 'legumes',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein source for plant-based cuisine',
        usage: 'Main dishes, stews, salads, side dishes',
        culturalContext: 'Legumes are the foundation of plant-based protein',
      },
      {
        ingredient: 'quinoa',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Complete protein grain for plant-based cuisine',
        usage: 'Bowls, salads, main dishes, side dishes',
        culturalContext:
          'Quinoa is a complete protein essential for plant-based diets',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein and healthy fats for plant-based cuisine',
        usage: 'Snacks, main dishes, desserts, side dishes',
        culturalContext: 'Nuts provide essential healthy fats and protein',
      },
      {
        ingredient: 'seeds',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein and healthy fats for plant-based cuisine',
        usage: 'Snacks, main dishes, desserts, side dishes',
        culturalContext: 'Seeds provide essential healthy fats and protein',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for plant-based cuisine',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Vegetables are the foundation of plant-based cuisine',
      },
      {
        ingredient: 'fruits',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for plant-based cuisine',
        usage: 'Desserts, snacks, main dishes, side dishes',
        culturalContext: 'Fruits provide natural sweetness and nutrients',
      },
      {
        ingredient: 'olive oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fat for plant-based cuisine',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext:
          'Olive oil is the primary healthy fat in plant-based cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for plant-based cuisine',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Herbs add flavor and nutrients to plant-based dishes',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for plant-based cuisine',
        usage: 'Marinades, main dishes, everything',
        culturalContext: 'Spices add depth and flavor to plant-based dishes',
      },
      {
        ingredient: 'garlic',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential aromatic for plant-based cooking',
        usage: 'Marinades, sauces, main dishes, aromatics',
        culturalContext: 'Foundation of plant-based flavor building',
      },
      {
        ingredient: 'onion',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Base ingredient for plant-based cooking',
        usage: 'Stews, main dishes, aromatics',
        culturalContext: 'Foundation of plant-based flavor building',
      },
      {
        ingredient: 'citrus',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential acid for plant-based cuisine',
        usage: 'Dressings, marinades, finishing, beverages',
        culturalContext: 'Essential for plant-based brightness and flavor',
      },
      {
        ingredient: 'grains',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular plant-based ingredients',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Important in plant-based cuisine',
      },
      {
        ingredient: 'mushrooms',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular plant-based ingredients',
        usage: 'Main dishes, side dishes, appetizers',
        culturalContext: 'Important in plant-based cuisine',
      },
      {
        ingredient: 'avocado',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular plant-based ingredient',
        usage: 'Salads, toast, smoothies, main dishes, garnishes',
        culturalContext: 'Important in plant-based cuisine',
      },
      {
        ingredient: 'coconut',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular plant-based ingredient',
        usage: 'Desserts, main dishes, beverages, snacks',
        culturalContext: 'Important in plant-based cuisine',
      },
    ],
  },
  vegan: {
    cuisine: 'Vegan',
    description:
      'Essential ingredients for authentic vegan cooking with no animal products',
    subStyles: [
      'Traditional Vegan',
      'Modern Vegan',
      'Raw Vegan',
      'Mediterranean Vegan',
      'Asian Vegan',
    ],
    staples: [
      {
        ingredient: 'tofu',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for vegan cuisine',
        usage: 'Main dishes, stir-fries, soups, side dishes',
        culturalContext: 'Tofu is the foundation of vegan protein',
      },
      {
        ingredient: 'tempeh',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for vegan cuisine',
        usage: 'Main dishes, stir-fries, soups, side dishes',
        culturalContext: 'Tempeh provides essential vegan protein',
      },
      {
        ingredient: 'nutritional_yeast',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential umami flavor for vegan cuisine',
        usage: 'Cheese substitutes, main dishes, snacks',
        culturalContext: 'Nutritional yeast provides essential umami flavor',
      },
      {
        ingredient: 'legumes',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein source for vegan cuisine',
        usage: 'Main dishes, stews, salads, side dishes',
        culturalContext: 'Legumes are the foundation of vegan protein',
      },
      {
        ingredient: 'quinoa',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Complete protein grain for vegan cuisine',
        usage: 'Bowls, salads, main dishes, side dishes',
        culturalContext:
          'Quinoa is a complete protein essential for vegan diets',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein and healthy fats for vegan cuisine',
        usage: 'Snacks, main dishes, desserts, side dishes',
        culturalContext: 'Nuts provide essential healthy fats and protein',
      },
      {
        ingredient: 'seeds',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein and healthy fats for vegan cuisine',
        usage: 'Snacks, main dishes, desserts, side dishes',
        culturalContext: 'Seeds provide essential healthy fats and protein',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for vegan cuisine',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Vegetables are the foundation of vegan cuisine',
      },
      {
        ingredient: 'fruits',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for vegan cuisine',
        usage: 'Desserts, snacks, main dishes, side dishes',
        culturalContext: 'Fruits provide natural sweetness and nutrients',
      },
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fat for vegan cuisine',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext:
          'Olive oil is the primary healthy fat in vegan cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for vegan cuisine',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Herbs add flavor and nutrients to vegan dishes',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential seasonings for vegan cuisine',
        usage: 'Marinades, main dishes, everything',
        culturalContext: 'Spices add depth and flavor to vegan dishes',
      },
      {
        ingredient: 'grains',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular vegan ingredients',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Important in vegan cuisine',
      },
      {
        ingredient: 'mushrooms',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular vegan ingredients',
        usage: 'Main dishes, side dishes, appetizers',
        culturalContext: 'Important in vegan cuisine',
      },
      {
        ingredient: 'avocado',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular vegan ingredient',
        usage: 'Salads, toast, smoothies, main dishes, garnishes',
        culturalContext: 'Important in vegan cuisine',
      },
      {
        ingredient: 'coconut',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular vegan ingredient',
        usage: 'Desserts, main dishes, beverages, snacks',
        culturalContext: 'Important in vegan cuisine',
      },
    ],
  },
  vegetarian: {
    cuisine: 'Vegetarian',
    description:
      'Essential ingredients for authentic vegetarian cooking with dairy and eggs',
    subStyles: [
      'Traditional Vegetarian',
      'Modern Vegetarian',
      'Mediterranean Vegetarian',
      'Asian Vegetarian',
      'Indian Vegetarian',
    ],
    staples: [
      {
        ingredient: 'eggs',
        category: 'proteins',
        priority: 'essential',
        reason: 'Essential protein for vegetarian cuisine',
        usage: 'Main dishes, baking, breakfast, side dishes',
        culturalContext: 'Eggs are the foundation of vegetarian protein',
      },
      {
        ingredient: 'cheese',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for vegetarian cuisine',
        usage: 'Main dishes, snacks, side dishes, appetizers',
        culturalContext: 'Cheese is essential for vegetarian main dishes',
      },
      {
        ingredient: 'milk',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for vegetarian cuisine',
        usage: 'Baking, beverages, main dishes, desserts',
        culturalContext: 'Essential for vegetarian baking and beverages',
      },
      {
        ingredient: 'yogurt',
        category: 'dairy_cold',
        priority: 'essential',
        reason: 'Essential dairy for vegetarian cuisine',
        usage: 'Main dishes, desserts, beverages, snacks',
        culturalContext: 'Essential for vegetarian main dishes and desserts',
      },
      {
        ingredient: 'legumes',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein source for vegetarian cuisine',
        usage: 'Main dishes, stews, salads, side dishes',
        culturalContext: 'Legumes are the foundation of vegetarian protein',
      },
      {
        ingredient: 'quinoa',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Complete protein grain for vegetarian cuisine',
        usage: 'Bowls, salads, main dishes, side dishes',
        culturalContext:
          'Quinoa is a complete protein essential for vegetarian diets',
      },
      {
        ingredient: 'nuts',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein and healthy fats for vegetarian cuisine',
        usage: 'Snacks, main dishes, desserts, side dishes',
        culturalContext: 'Nuts provide essential healthy fats and protein',
      },
      {
        ingredient: 'seeds',
        category: 'pantry_staples',
        priority: 'essential',
        reason: 'Essential protein and healthy fats for vegetarian cuisine',
        usage: 'Snacks, main dishes, desserts, side dishes',
        culturalContext: 'Seeds provide essential healthy fats and protein',
      },
      {
        ingredient: 'vegetables',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for vegetarian cuisine',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Vegetables are the foundation of vegetarian cuisine',
      },
      {
        ingredient: 'fruits',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for vegetarian cuisine',
        usage: 'Desserts, snacks, main dishes, side dishes',
        culturalContext: 'Fruits provide natural sweetness and nutrients',
      },
      {
        ingredient: 'olive_oil',
        category: 'flavor_builders',
        priority: 'essential',
        reason: 'Essential healthy fat for vegetarian cuisine',
        usage: 'Cooking, dressings, marinades, finishing',
        culturalContext:
          'Olive oil is the primary healthy fat in vegetarian cooking',
      },
      {
        ingredient: 'herbs',
        category: 'fresh_produce',
        priority: 'essential',
        reason: 'Essential ingredients for vegetarian cuisine',
        usage: 'Garnishes, marinades, main dishes, aromatics',
        culturalContext: 'Herbs add flavor and nutrients to vegetarian dishes',
      },
      {
        ingredient: 'spices',
        category: 'flavor_builders',
        priority: 'recommended',
        reason: 'Popular vegetarian ingredients',
        usage: 'Marinades, main dishes, everything',
        culturalContext: 'Important in vegetarian cuisine',
      },
      {
        ingredient: 'grains',
        category: 'pantry_staples',
        priority: 'recommended',
        reason: 'Popular vegetarian ingredients',
        usage: 'Main dishes, side dishes, salads, everything',
        culturalContext: 'Important in vegetarian cuisine',
      },
      {
        ingredient: 'mushrooms',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular vegetarian ingredients',
        usage: 'Main dishes, side dishes, appetizers',
        culturalContext: 'Important in vegetarian cuisine',
      },
      {
        ingredient: 'avocado',
        category: 'fresh_produce',
        priority: 'recommended',
        reason: 'Popular vegetarian ingredient',
        usage: 'Salads, toast, smoothies, main dishes, garnishes',
        culturalContext: 'Important in vegetarian cuisine',
      },
    ],
  },
};
