import { CuisineStaplesData } from '../../cuisine-staples/types';

export const chinese: CuisineStaplesData = {
  cuisine: 'Chinese',
  description: 'Essential ingredients for authentic Chinese cooking',
  subStyles: ['Cantonese', 'Sichuan', 'Hunan', 'Shanghai', 'Beijing'],
  staples: [
    {
      ingredient: 'soy sauce',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Fundamental seasoning for Chinese cuisine',
      usage: 'Marinades, stir-fries, dipping sauces',
      culturalContext: 'The backbone of Chinese flavor profile',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Chinese cooking',
      usage: 'Stir-fries, marinades, sauces',
      culturalContext: 'Used in almost every Chinese dish',
    },
    {
      ingredient: 'ginger',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Core aromatic and medicinal ingredient',
      usage: 'Stir-fries, marinades, tea, soups',
      culturalContext: 'Balances flavors and aids digestion',
    },
    {
      ingredient: 'green onions',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential garnish and flavor enhancer',
      usage: 'Garnish, stir-fries, dumplings',
      culturalContext: 'Cannot make authentic Chinese food without scallions',
    },
    {
      ingredient: 'sesame oil',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Distinctive Chinese flavor and aroma',
      usage: 'Finishing oil, marinades, dressings',
      culturalContext: 'Adds authentic Chinese aroma',
    },
    {
      ingredient: 'rice vinegar',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential acid for Chinese cooking',
      usage: 'Stir-fries, dipping sauces, pickling',
      culturalContext: 'Milder than other vinegars, perfect for Chinese dishes',
    },
    {
      ingredient: 'oyster sauce',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Rich umami flavor for Chinese dishes',
      usage: 'Stir-fries, marinades, glazes',
      culturalContext: 'Essential for authentic Chinese stir-fries',
    },
    {
      ingredient: 'hoisin sauce',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Sweet and savory Chinese condiment',
      usage: 'Marinades, dipping sauces, glazes',
      culturalContext: 'Key ingredient in Peking duck and many dishes',
    },
    {
      ingredient: 'chili oil',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Adds heat and flavor to Chinese dishes',
      usage: 'Dipping sauces, stir-fries, noodles',
      culturalContext: 'Essential for Sichuan and Hunan cuisine',
    },
    {
      ingredient: 'star anise',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Distinctive Chinese spice for braising',
      usage: 'Braised dishes, five-spice powder, soups',
      culturalContext: 'Key spice in Chinese five-spice blend',
    },
    {
      ingredient: 'Sichuan peppercorns',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Unique numbing spice for Sichuan cuisine',
      usage: 'Sichuan dishes, marinades, spice blends',
      culturalContext: 'Essential for authentic Sichuan cooking',
    },
    {
      ingredient: 'rice',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Staple grain for Chinese meals',
      usage: 'Steamed rice, fried rice, congee',
      culturalContext: 'Foundation of Chinese meals',
    },
    {
      ingredient: 'noodles',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential for Chinese noodle dishes',
      usage: 'Lo mein, chow mein, soup noodles',
      culturalContext: 'Noodles represent longevity in Chinese culture',
    },
    {
      ingredient: 'tofu',
      category: 'proteins',
      priority: 'recommended',
      reason: 'Versatile protein for Chinese cooking',
      usage: 'Stir-fries, soups, braised dishes',
      culturalContext: 'Important protein source in Chinese cuisine',
    },
    {
      ingredient: 'bok choy',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Popular Chinese leafy green',
      usage: 'Stir-fries, soups, steamed dishes',
      culturalContext: 'Most common Chinese vegetable',
    },
  ],
};
