import { CuisineStaplesData } from '../types';

export const filipino: CuisineStaplesData = {
  cuisine: 'Filipino',
  description:
    'Essential ingredients for authentic Filipino cooking with adobo and lumpia',
  subStyles: [
    'Manila',
    'Cebu',
    'Davao',
    'Traditional Filipino',
    'Modern Filipino',
  ],
  staples: [
    {
      ingredient: 'rice',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Staple grain for Filipino meals',
      usage: 'Main dishes, side dishes, everyday meals',
      culturalContext: 'Foundation of Filipino meals',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Filipino cooking',
      usage: 'Adobo, marinades, sauces, main dishes',
      culturalContext: 'Foundation of Filipino flavor building',
    },
    {
      ingredient: 'onion',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Base ingredient for Filipino cooking',
      usage: 'Adobo, stews, main dishes, aromatics',
      culturalContext: 'Foundation of Filipino flavor building',
    },
    {
      ingredient: 'soy sauce',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential seasoning for Filipino cuisine',
      usage: 'Adobo, marinades, dipping sauces, main dishes',
      culturalContext: 'Soy sauce is the backbone of Filipino flavor',
    },
    {
      ingredient: 'vinegar',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential acid for Filipino cuisine',
      usage: 'Adobo, marinades, dressings, pickling',
      culturalContext: 'Essential for authentic Filipino sour flavor',
    },
    {
      ingredient: 'bay leaves',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential herb for Filipino cooking',
      usage: 'Adobo, stews, marinades, main dishes',
      culturalContext:
        'Cannot make authentic Filipino adobo without bay leaves',
    },
    {
      ingredient: 'black pepper',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential spice for Filipino cuisine',
      usage: 'Adobo, marinades, main dishes, everything',
      culturalContext: 'Essential for authentic Filipino heat',
    },
    {
      ingredient: 'fish sauce',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential umami for Filipino cooking',
      usage: 'Adobo, marinades, dipping sauces, main dishes',
      culturalContext: 'Fish sauce is the soul of Filipino cuisine',
    },
    {
      ingredient: 'coconut milk',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential for Filipino curries and stews',
      usage: 'Curries, stews, desserts, beverages',
      culturalContext: 'Essential for authentic Filipino creaminess',
    },
    {
      ingredient: 'ginger',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Filipino cooking',
      usage: 'Adobo, marinades, teas, health benefits',
      culturalContext: 'Medicinal and culinary importance in Filipino culture',
    },
    {
      ingredient: 'chili peppers',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential heat for Filipino cuisine',
      usage: 'Adobo, marinades, sauces, main dishes',
      culturalContext: 'Filipino cuisine is known for its heat',
    },
    {
      ingredient: 'cilantro',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential herb for Filipino cuisine',
      usage: 'Garnishes, marinades, main dishes, salads',
      culturalContext: 'Essential for authentic Filipino herb profile',
    },
    {
      ingredient: 'lime',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential acid for Filipino cuisine',
      usage: 'Adobo, marinades, dressings, finishing',
      culturalContext: 'Essential for authentic Filipino brightness',
    },
    {
      ingredient: 'sugar',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Popular Filipino sweetener',
      usage: 'Desserts, marinades, balance, main dishes',
      culturalContext: 'Important in Filipino desserts and balance',
    },
    {
      ingredient: 'eggs',
      category: 'proteins',
      priority: 'recommended',
      reason: 'Popular Filipino ingredient',
      usage: 'Adobo, main dishes, desserts, breakfast',
      culturalContext: 'Important in Filipino cuisine',
    },
    {
      ingredient: 'vegetables',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Popular Filipino ingredients',
      usage: 'Stir-fries, stews, main dishes, side dishes',
      culturalContext: 'Important in Filipino cuisine',
    },
  ],
};
