import { CuisineStaplesData } from '../../cuisine-staples/types';

export const indian: CuisineStaplesData = {
  cuisine: 'Indian',
  description: 'Essential spices and ingredients for authentic Indian cooking',
  subStyles: ['North Indian', 'South Indian', 'Gujarati', 'Bengali', 'Punjabi'],
  staples: [
    {
      ingredient: 'turmeric',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Golden spice that defines Indian cuisine',
      usage: 'Curries, rice, marinades, health benefits',
      culturalContext: 'Sacred spice with medicinal properties',
    },
    {
      ingredient: 'cumin',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Fundamental spice in Indian cooking',
      usage: 'Tempering, curries, rice dishes',
      culturalContext: 'Most important spice in Indian cuisine',
    },
    {
      ingredient: 'coriander',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential spice and herb combination',
      usage: 'Curries, chutneys, garnishes',
      culturalContext: 'Both seeds and leaves are essential',
    },
    {
      ingredient: 'garam masala',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Signature Indian spice blend',
      usage: 'Curries, rice, finishing spice',
      culturalContext: 'The heart of Indian flavor profile',
    },
    {
      ingredient: 'cardamom',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Aromatic spice for Indian dishes',
      usage: 'Curries, rice, desserts, tea',
      culturalContext: 'Queen of spices in Indian cuisine',
    },
    {
      ingredient: 'cinnamon',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Warm spice for Indian cooking',
      usage: 'Curries, rice, desserts, tea',
      culturalContext: 'Essential for authentic Indian flavor',
    },
    {
      ingredient: 'cloves',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Aromatic spice for Indian dishes',
      usage: 'Curries, rice, pickles, tea',
      culturalContext: 'Adds depth to Indian spice blends',
    },
    {
      ingredient: 'ginger',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Indian cooking',
      usage: 'Curries, marinades, tea, health benefits',
      culturalContext: 'Medicinal and culinary importance',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Fundamental aromatic for Indian dishes',
      usage: 'Curries, marinades, tempering',
      culturalContext: 'Essential base for most Indian dishes',
    },
    {
      ingredient: 'onion',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Base ingredient for Indian cooking',
      usage: 'Curries, rice, tempering, garnishes',
      culturalContext: 'Foundation of Indian flavor building',
    },
    {
      ingredient: 'chili powder',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Heat and color for Indian dishes',
      usage: 'Curries, marinades, spice blends',
      culturalContext: 'Essential for authentic Indian heat',
    },
    {
      ingredient: 'mustard seeds',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential for tempering in Indian cooking',
      usage: 'Tempering, pickles, curries',
      culturalContext: 'Cannot make authentic Indian food without tempering',
    },
    {
      ingredient: 'rice',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Staple grain for Indian meals',
      usage: 'Basmati rice, biryani, everyday meals',
      culturalContext: 'Foundation of Indian meals',
    },
    {
      ingredient: 'lentils',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential protein source in Indian cuisine',
      usage: 'Dal, curries, soups, side dishes',
      culturalContext: 'Primary protein source for many Indians',
    },
    {
      ingredient: 'ghee',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Traditional cooking fat for Indian cuisine',
      usage: 'Tempering, rice, desserts, cooking',
      culturalContext: 'Sacred and essential in Indian cooking',
    },
    {
      ingredient: 'coconut milk',
      category: 'pantry_staples',
      priority: 'recommended',
      reason: 'Creamy base for South Indian dishes',
      usage: 'Curries, rice, desserts, beverages',
      culturalContext: 'Essential for South Indian cuisine',
    },
    {
      ingredient: 'cilantro',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential herb for Indian cooking',
      usage: 'Garnishes, chutneys, curries',
      culturalContext: 'Cannot make authentic Indian food without cilantro',
    },
  ],
};
