import { CuisineStaplesData } from '../types';

export const indonesian: CuisineStaplesData = {
  cuisine: 'Indonesian',
  description:
    'Essential ingredients for authentic Indonesian cooking with nasi goreng and rendang',
  subStyles: [
    'Jakarta',
    'Bali',
    'Surabaya',
    'Traditional Indonesian',
    'Modern Indonesian',
  ],
  staples: [
    {
      ingredient: 'rice',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Staple grain for Indonesian meals',
      usage: 'Nasi goreng, main dishes, side dishes, everyday meals',
      culturalContext: 'Foundation of Indonesian meals',
    },
    {
      ingredient: 'coconut milk',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential for Indonesian curries and stews',
      usage: 'Curries, stews, desserts, beverages',
      culturalContext: 'Essential for authentic Indonesian creaminess',
    },
    {
      ingredient: 'onion',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Base ingredient for Indonesian cooking',
      usage: 'Nasi goreng, stews, main dishes, aromatics',
      culturalContext: 'Foundation of Indonesian flavor building',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Indonesian cooking',
      usage: 'Nasi goreng, marinades, sauces, main dishes',
      culturalContext: 'Foundation of Indonesian flavor building',
    },
    {
      ingredient: 'ginger',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Indonesian dishes',
      usage: 'Nasi goreng, marinades, teas, health benefits',
      culturalContext:
        'Medicinal and culinary importance in Indonesian culture',
    },
    {
      ingredient: 'chili peppers',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential heat for Indonesian cuisine',
      usage: 'Nasi goreng, stews, marinades, sauces',
      culturalContext: 'Indonesian cuisine is known for its heat',
    },
    {
      ingredient: 'lemongrass',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential herb for Indonesian cuisine',
      usage: 'Curries, stews, marinades, aromatics',
      culturalContext:
        'Cannot make authentic Indonesian food without lemongrass',
    },
    {
      ingredient: 'galangal',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential root for Indonesian cuisine',
      usage: 'Curries, stews, marinades, aromatics',
      culturalContext: 'Essential for authentic Indonesian flavor',
    },
    {
      ingredient: 'turmeric',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential spice for Indonesian cuisine',
      usage: 'Curries, stews, marinades, main dishes',
      culturalContext: 'Essential for authentic Indonesian color and flavor',
    },
    {
      ingredient: 'coriander',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential herb for Indonesian cuisine',
      usage: 'Garnishes, marinades, main dishes, salads',
      culturalContext:
        'Cannot make authentic Indonesian food without coriander',
    },
    {
      ingredient: 'cumin',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential spice for Indonesian cuisine',
      usage: 'Curries, stews, marinades, main dishes',
      culturalContext: 'Essential for authentic Indonesian flavor',
    },
    {
      ingredient: 'candlenuts',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential nut for Indonesian cuisine',
      usage: 'Curries, stews, marinades, main dishes',
      culturalContext: 'Essential for authentic Indonesian richness',
    },
    {
      ingredient: 'palm sugar',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential sweetener for Indonesian cuisine',
      usage: 'Curries, desserts, marinades, main dishes',
      culturalContext: 'Essential for authentic Indonesian sweetness',
    },
    {
      ingredient: 'tamarind',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Popular Indonesian ingredient',
      usage: 'Curries, stews, marinades, main dishes',
      culturalContext: 'Important in Indonesian cuisine',
    },
    {
      ingredient: 'shrimp paste',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Popular Indonesian ingredient',
      usage: 'Curries, stews, marinades, main dishes',
      culturalContext: 'Important in Indonesian cuisine',
    },
    {
      ingredient: 'fish',
      category: 'proteins',
      priority: 'recommended',
      reason: 'Popular Indonesian protein',
      usage: 'Main dishes, soups, side dishes, traditional',
      culturalContext: 'Important in Indonesian cuisine',
    },
  ],
};
