import { CuisineStaplesData } from '../../cuisine-staples/types';

export const japanese: CuisineStaplesData = {
  cuisine: 'Japanese',
  description:
    'Essential ingredients for authentic Japanese cooking with fresh ingredients',
  subStyles: [
    'Tokyo',
    'Osaka',
    'Kyoto',
    'Traditional Japanese',
    'Modern Japanese',
  ],
  staples: [
    {
      ingredient: 'soy sauce',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Fundamental seasoning for Japanese cuisine',
      usage: 'Sushi, marinades, dipping sauces, cooking',
      culturalContext: 'The backbone of Japanese flavor profile',
    },
    {
      ingredient: 'miso',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential fermented paste for Japanese cooking',
      usage: 'Soups, marinades, dressings, glazes',
      culturalContext: 'Miso is the soul of Japanese cooking',
    },
    {
      ingredient: 'rice vinegar',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential acid for Japanese cuisine',
      usage: 'Sushi rice, dressings, pickling, marinades',
      culturalContext: 'Essential for authentic Japanese sour flavor',
    },
    {
      ingredient: 'mirin',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Sweet rice wine for Japanese cooking',
      usage: 'Teriyaki, glazes, marinades, sauces',
      culturalContext: 'Essential for authentic Japanese sweetness',
    },
    {
      ingredient: 'sake',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Japanese rice wine for cooking',
      usage: 'Marinades, sauces, steaming, deglazing',
      culturalContext: 'Essential for authentic Japanese flavor building',
    },
    {
      ingredient: 'dashi',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential Japanese stock base',
      usage: 'Soups, sauces, rice, everything',
      culturalContext: 'The foundation of Japanese umami',
    },
    {
      ingredient: 'wasabi',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential Japanese condiment',
      usage: 'Sushi, sashimi, marinades, dressings',
      culturalContext: 'Cannot have authentic Japanese sushi without wasabi',
    },
    {
      ingredient: 'nori',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential seaweed for Japanese cuisine',
      usage: 'Sushi, rice balls, garnishes, snacks',
      culturalContext: 'Essential for sushi and many Japanese dishes',
    },
    {
      ingredient: 'rice',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Staple grain for Japanese meals',
      usage: 'Sushi rice, steamed rice, rice balls',
      culturalContext: 'Foundation of Japanese meals',
    },
    {
      ingredient: 'noodles',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential for Japanese noodle dishes',
      usage: 'Ramen, udon, soba, cold noodles',
      culturalContext: 'Essential for authentic Japanese noodle dishes',
    },
    {
      ingredient: 'ginger',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Japanese cooking',
      usage: 'Sushi, marinades, pickles, tea',
      culturalContext: 'Essential for authentic Japanese flavor',
    },
    {
      ingredient: 'green onions',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential garnish for Japanese dishes',
      usage: 'Garnish, soups, rice, marinades',
      culturalContext: 'Essential for authentic Japanese presentation',
    },
    {
      ingredient: 'tofu',
      category: 'proteins',
      priority: 'essential',
      reason: 'Essential protein in Japanese cuisine',
      usage: 'Miso soup, stir-fries, hot pot, desserts',
      culturalContext: 'Fundamental protein in Japanese cooking',
    },
    {
      ingredient: 'mushrooms',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Popular ingredient in Japanese dishes',
      usage: 'Stir-fries, soups, rice, side dishes',
      culturalContext: 'Important ingredient in Japanese cuisine',
    },
    {
      ingredient: 'daikon',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Popular Japanese root vegetable',
      usage: 'Pickles, soups, garnishes, side dishes',
      culturalContext: 'Important vegetable in Japanese cooking',
    },
    {
      ingredient: 'bonito flakes',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Essential for authentic dashi',
      usage: 'Dashi stock, garnishes, seasonings',
      culturalContext: 'Essential for authentic Japanese umami',
    },
    {
      ingredient: 'kombu',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Essential seaweed for dashi',
      usage: 'Dashi stock, cooking, seasonings',
      culturalContext: 'Essential for authentic Japanese stock',
    },
  ],
};
