import { CuisineStaplesData } from '../types';

export const korean: CuisineStaplesData = {
  cuisine: 'Korean',
  description:
    'Essential ingredients for authentic Korean cooking with fermented flavors',
  subStyles: ['Seoul', 'Busan', 'Jeju', 'Gyeongju', 'Traditional Korean'],
  staples: [
    {
      ingredient: 'gochujang',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Signature Korean fermented chili paste',
      usage: 'Bulgogi, bibimbap, stews, marinades',
      culturalContext: 'The soul of Korean cuisine - cannot be substituted',
    },
    {
      ingredient: 'kimchi',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'National dish and essential Korean ingredient',
      usage: 'Side dish, stews, fried rice, pancakes',
      culturalContext: 'Koreans eat kimchi with every meal',
    },
    {
      ingredient: 'sesame oil',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential Korean flavor and aroma',
      usage: 'Finishing oil, marinades, dressings, garnishes',
      culturalContext: 'Essential for authentic Korean aroma',
    },
    {
      ingredient: 'soy sauce',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Fundamental seasoning for Korean cuisine',
      usage: 'Marinades, dipping sauces, stews',
      culturalContext: 'Base seasoning for most Korean dishes',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Korean cooking',
      usage: 'Marinades, stews, kimchi, pastes',
      culturalContext: 'Koreans use more garlic than any other cuisine',
    },
    {
      ingredient: 'ginger',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Korean dishes',
      usage: 'Marinades, teas, kimchi, health benefits',
      culturalContext: 'Medicinal and culinary importance in Korean culture',
    },
    {
      ingredient: 'green onions',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential garnish and flavor enhancer',
      usage: 'Garnish, pancakes, stews, marinades',
      culturalContext: 'Cannot make authentic Korean food without scallions',
    },
    {
      ingredient: 'gochugaru',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Korean chili flakes for authentic heat',
      usage: 'Kimchi, stews, marinades, spice blends',
      culturalContext: 'Essential for authentic Korean spice level',
    },
    {
      ingredient: 'rice',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Staple grain for Korean meals',
      usage: 'Steamed rice, fried rice, porridge',
      culturalContext: 'Foundation of Korean meals',
    },
    {
      ingredient: 'noodles',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential for Korean noodle dishes',
      usage: 'Japchae, cold noodles, soup noodles',
      culturalContext: 'Noodles represent longevity in Korean culture',
    },
    {
      ingredient: 'tofu',
      category: 'proteins',
      priority: 'recommended',
      reason: 'Important protein in Korean cuisine',
      usage: 'Stews, stir-fries, soups, side dishes',
      culturalContext: 'Important protein source in Korean cooking',
    },
    {
      ingredient: 'mushrooms',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Popular ingredient in Korean dishes',
      usage: 'Stir-fries, stews, soups, side dishes',
      culturalContext: 'Important ingredient in Korean cuisine',
    },
    {
      ingredient: 'seaweed',
      category: 'pantry_staples',
      priority: 'recommended',
      reason: 'Traditional Korean ingredient',
      usage: 'Soups, side dishes, rice rolls',
      culturalContext: 'Important in Korean coastal cuisine',
    },
    {
      ingredient: 'bean sprouts',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Popular Korean vegetable',
      usage: 'Stir-fries, soups, side dishes, bibimbap',
      culturalContext: 'Common ingredient in Korean dishes',
    },
    {
      ingredient: 'pear',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Used in Korean marinades and sauces',
      usage: 'Bulgogi marinades, sauces, desserts',
      culturalContext: 'Korean pears tenderize meat naturally',
    },
    {
      ingredient: 'sesame seeds',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Essential garnish for Korean dishes',
      usage: 'Garnishes, marinades, dressings',
      culturalContext: 'Essential for authentic Korean presentation',
    },
  ],
};
