import { CuisineStaplesData } from '../types';

export const malaysian: CuisineStaplesData = {
  cuisine: 'Malaysian',
  description:
    'Essential ingredients for authentic Malaysian cooking with laksa and nasi lemak',
  subStyles: [
    'Kuala Lumpur',
    'Penang',
    'Malacca',
    'Traditional Malaysian',
    'Modern Malaysian',
  ],
  staples: [
    {
      ingredient: 'rice',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Staple grain for Malaysian meals',
      usage: 'Nasi lemak, main dishes, side dishes, everyday meals',
      culturalContext: 'Foundation of Malaysian meals',
    },
    {
      ingredient: 'coconut milk',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential for Malaysian curries and stews',
      usage: 'Laksa, curries, stews, desserts, beverages',
      culturalContext: 'Essential for authentic Malaysian creaminess',
    },
    {
      ingredient: 'onion',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Base ingredient for Malaysian cooking',
      usage: 'Laksa, stews, main dishes, aromatics',
      culturalContext: 'Foundation of Malaysian flavor building',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Malaysian cooking',
      usage: 'Laksa, marinades, sauces, main dishes',
      culturalContext: 'Foundation of Malaysian flavor building',
    },
    {
      ingredient: 'ginger',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Malaysian dishes',
      usage: 'Laksa, marinades, teas, health benefits',
      culturalContext: 'Medicinal and culinary importance in Malaysian culture',
    },
    {
      ingredient: 'chili peppers',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential heat for Malaysian cuisine',
      usage: 'Laksa, stews, marinades, sauces',
      culturalContext: 'Malaysian cuisine is known for its heat',
    },
    {
      ingredient: 'lemongrass',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential herb for Malaysian cuisine',
      usage: 'Laksa, curries, stews, marinades, aromatics',
      culturalContext:
        'Cannot make authentic Malaysian food without lemongrass',
    },
    {
      ingredient: 'galangal',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential root for Malaysian cuisine',
      usage: 'Laksa, curries, stews, marinades, aromatics',
      culturalContext: 'Essential for authentic Malaysian flavor',
    },
    {
      ingredient: 'turmeric',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential spice for Malaysian cuisine',
      usage: 'Laksa, curries, stews, marinades, main dishes',
      culturalContext: 'Essential for authentic Malaysian color and flavor',
    },
    {
      ingredient: 'coriander',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential herb for Malaysian cuisine',
      usage: 'Laksa, garnishes, marinades, main dishes, salads',
      culturalContext: 'Cannot make authentic Malaysian food without coriander',
    },
    {
      ingredient: 'cumin',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential spice for Malaysian cuisine',
      usage: 'Laksa, curries, stews, marinades, main dishes',
      culturalContext: 'Essential for authentic Malaysian flavor',
    },
    {
      ingredient: 'candlenuts',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential nut for Malaysian cuisine',
      usage: 'Laksa, curries, stews, marinades, main dishes',
      culturalContext: 'Essential for authentic Malaysian richness',
    },
    {
      ingredient: 'palm sugar',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential sweetener for Malaysian cuisine',
      usage: 'Laksa, curries, desserts, marinades, main dishes',
      culturalContext: 'Essential for authentic Malaysian sweetness',
    },
    {
      ingredient: 'tamarind',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Popular Malaysian ingredient',
      usage: 'Laksa, curries, stews, marinades, main dishes',
      culturalContext: 'Important in Malaysian cuisine',
    },
    {
      ingredient: 'shrimp paste',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Popular Malaysian ingredient',
      usage: 'Laksa, curries, stews, marinades, main dishes',
      culturalContext: 'Important in Malaysian cuisine',
    },
    {
      ingredient: 'fish',
      category: 'proteins',
      priority: 'recommended',
      reason: 'Popular Malaysian protein',
      usage: 'Laksa, main dishes, soups, side dishes, traditional',
      culturalContext: 'Important in Malaysian cuisine',
    },
  ],
};
