import { CuisineStaplesData } from '../../cuisine-staples/types';

export const singaporean: CuisineStaplesData = {
  cuisine: 'Singaporean',
  description:
    'Essential ingredients for authentic Singaporean cooking with Hainanese chicken rice and chili crab',
  subStyles: [
    'Singapore',
    'Chinatown',
    'Little India',
    'Traditional Singaporean',
    'Modern Singaporean',
  ],
  staples: [
    {
      ingredient: 'rice',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Staple grain for Singaporean meals',
      usage: 'Hainanese chicken rice, main dishes, side dishes, everyday meals',
      culturalContext: 'Foundation of Singaporean meals',
    },
    {
      ingredient: 'chicken',
      category: 'proteins',
      priority: 'essential',
      reason: 'Essential protein for Singaporean cuisine',
      usage: 'Hainanese chicken rice, main dishes, soups, side dishes',
      culturalContext: 'Chicken is the soul of Singaporean cuisine',
    },
    {
      ingredient: 'onion',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Base ingredient for Singaporean cooking',
      usage: 'Hainanese chicken rice, stews, main dishes, aromatics',
      culturalContext: 'Foundation of Singaporean flavor building',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Singaporean cooking',
      usage: 'Hainanese chicken rice, marinades, sauces, main dishes',
      culturalContext: 'Foundation of Singaporean flavor building',
    },
    {
      ingredient: 'ginger',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Singaporean dishes',
      usage: 'Hainanese chicken rice, marinades, teas, health benefits',
      culturalContext:
        'Medicinal and culinary importance in Singaporean culture',
    },
    {
      ingredient: 'chili peppers',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential heat for Singaporean cuisine',
      usage: 'Chili crab, stews, marinades, sauces',
      culturalContext: 'Singaporean cuisine is known for its heat',
    },
    {
      ingredient: 'lemongrass',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential herb for Singaporean cuisine',
      usage: 'Curries, stews, marinades, aromatics',
      culturalContext:
        'Cannot make authentic Singaporean food without lemongrass',
    },
    {
      ingredient: 'galangal',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential root for Singaporean cuisine',
      usage: 'Curries, stews, marinades, aromatics',
      culturalContext: 'Essential for authentic Singaporean flavor',
    },
    {
      ingredient: 'turmeric',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential spice for Singaporean cuisine',
      usage: 'Curries, stews, marinades, main dishes',
      culturalContext: 'Essential for authentic Singaporean color and flavor',
    },
    {
      ingredient: 'coriander',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential herb for Singaporean cuisine',
      usage: 'Garnishes, marinades, main dishes, salads',
      culturalContext:
        'Cannot make authentic Singaporean food without coriander',
    },
    {
      ingredient: 'cumin',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential spice for Singaporean cuisine',
      usage: 'Curries, stews, marinades, main dishes',
      culturalContext: 'Essential for authentic Singaporean flavor',
    },
    {
      ingredient: 'candlenuts',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential nut for Singaporean cuisine',
      usage: 'Curries, stews, marinades, main dishes',
      culturalContext: 'Essential for authentic Singaporean richness',
    },
    {
      ingredient: 'palm sugar',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential sweetener for Singaporean cuisine',
      usage: 'Curries, desserts, marinades, main dishes',
      culturalContext: 'Essential for authentic Singaporean sweetness',
    },
    {
      ingredient: 'tamarind',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Popular Singaporean ingredient',
      usage: 'Curries, stews, marinades, main dishes',
      culturalContext: 'Important in Singaporean cuisine',
    },
    {
      ingredient: 'shrimp paste',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Popular Singaporean ingredient',
      usage: 'Curries, stews, marinades, main dishes',
      culturalContext: 'Important in Singaporean cuisine',
    },
    {
      ingredient: 'fish',
      category: 'proteins',
      priority: 'recommended',
      reason: 'Popular Singaporean protein',
      usage: 'Main dishes, soups, side dishes, traditional',
      culturalContext: 'Important in Singaporean cuisine',
    },
  ],
};
