import { CuisineStaplesData } from '../types';

export const thai: CuisineStaplesData = {
  cuisine: 'Thai',
  description:
    'Essential ingredients for authentic Thai cooking with balanced flavors',
  subStyles: [
    'Central Thai',
    'Northern Thai',
    'Southern Thai',
    'Isaan',
    'Royal Thai',
  ],
  staples: [
    {
      ingredient: 'fish sauce',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Fundamental umami flavor in Thai cuisine',
      usage: 'Curries, stir-fries, dipping sauces, marinades',
      culturalContext: 'The salt of Thai cooking - cannot be substituted',
    },
    {
      ingredient: 'lime',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential acid for Thai flavor balance',
      usage: 'Curries, stir-fries, salads, finishing',
      culturalContext: 'Essential for authentic Thai sour flavor',
    },
    {
      ingredient: 'lemongrass',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Distinctive Thai herb and flavor',
      usage: 'Curries, soups, marinades, tea',
      culturalContext: 'Signature Thai flavor that cannot be replicated',
    },
    {
      ingredient: 'galangal',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential Thai root for authentic flavor',
      usage: 'Curries, soups, marinades',
      culturalContext: 'Cannot make authentic Thai curry without galangal',
    },
    {
      ingredient: 'kaffir lime leaves',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Distinctive Thai citrus flavor',
      usage: 'Curries, soups, stir-fries, garnishes',
      culturalContext: 'Essential for authentic Thai aroma',
    },
    {
      ingredient: 'Thai basil',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential herb for Thai cooking',
      usage: 'Curries, stir-fries, garnishes',
      culturalContext:
        'Different from regular basil - essential for Thai dishes',
    },
    {
      ingredient: 'cilantro',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential herb for Thai cuisine',
      usage: 'Garnishes, curries, salads',
      culturalContext: 'Essential for authentic Thai flavor profile',
    },
    {
      ingredient: 'chili peppers',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential heat for Thai cuisine',
      usage: 'Curries, stir-fries, salads, pastes',
      culturalContext: 'Thai cuisine is known for its heat',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Thai cooking',
      usage: 'Curries, stir-fries, pastes, marinades',
      culturalContext: 'Foundation of Thai flavor building',
    },
    {
      ingredient: 'shallots',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Thai dishes',
      usage: 'Curries, stir-fries, pastes, garnishes',
      culturalContext: 'More important than onions in Thai cooking',
    },
    {
      ingredient: 'palm sugar',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Authentic sweetener for Thai cuisine',
      usage: 'Curries, stir-fries, desserts, balance',
      culturalContext: 'Essential for authentic Thai sweetness',
    },
    {
      ingredient: 'tamarind',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential sour flavor for Thai cuisine',
      usage: 'Curries, stir-fries, soups, balance',
      culturalContext: 'Essential for authentic Thai sour flavor',
    },
    {
      ingredient: 'coconut milk',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Creamy base for Thai curries',
      usage: 'Curries, soups, desserts, beverages',
      culturalContext: 'Essential for authentic Thai curry texture',
    },
    {
      ingredient: 'rice',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Staple grain for Thai meals',
      usage: 'Steamed rice, fried rice, sticky rice',
      culturalContext: 'Foundation of Thai meals',
    },
    {
      ingredient: 'rice noodles',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential for Thai noodle dishes',
      usage: 'Pad Thai, noodle soups, stir-fries',
      culturalContext: 'Essential for authentic Thai noodle dishes',
    },
    {
      ingredient: 'shrimp paste',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Essential umami for Thai cooking',
      usage: 'Curries, stir-fries, pastes, marinades',
      culturalContext: 'Essential for authentic Thai umami flavor',
    },
    {
      ingredient: 'mushrooms',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Popular protein in Thai cuisine',
      usage: 'Stir-fries, curries, soups, salads',
      culturalContext: 'Important protein source in Thai cooking',
    },
  ],
};
