import { CuisineStaplesData } from '../../cuisine-staples/types';

export const vietnamese: CuisineStaplesData = {
  cuisine: 'Vietnamese',
  description:
    'Essential ingredients for authentic Vietnamese cooking with fresh herbs',
  subStyles: [
    'Northern Vietnamese',
    'Central Vietnamese',
    'Southern Vietnamese',
    'Saigon',
    'Hanoi',
  ],
  staples: [
    {
      ingredient: 'fish sauce',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Fundamental umami flavor in Vietnamese cuisine',
      usage: 'Pho, stir-fries, dipping sauces, marinades',
      culturalContext: 'The salt of Vietnamese cooking - cannot be substituted',
    },
    {
      ingredient: 'lime',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential acid for Vietnamese flavor balance',
      usage: 'Pho, salads, dipping sauces, finishing',
      culturalContext: 'Essential for authentic Vietnamese sour flavor',
    },
    {
      ingredient: 'cilantro',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential herb for Vietnamese cuisine',
      usage: 'Garnishes, pho, salads, marinades',
      culturalContext: 'Cannot make authentic Vietnamese food without cilantro',
    },
    {
      ingredient: 'mint',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential herb for Vietnamese dishes',
      usage: 'Pho, salads, spring rolls, garnishes',
      culturalContext: 'Essential for authentic Vietnamese herb profile',
    },
    {
      ingredient: 'basil',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential herb for Vietnamese cooking',
      usage: 'Pho, salads, spring rolls, garnishes',
      culturalContext: 'Essential for authentic Vietnamese flavor',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Vietnamese cooking',
      usage: 'Marinades, stir-fries, pastes, sauces',
      culturalContext: 'Foundation of Vietnamese flavor building',
    },
    {
      ingredient: 'shallots',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Vietnamese dishes',
      usage: 'Stir-fries, marinades, garnishes, pastes',
      culturalContext: 'More important than onions in Vietnamese cooking',
    },
    {
      ingredient: 'ginger',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Vietnamese cooking',
      usage: 'Pho, marinades, stir-fries, health benefits',
      culturalContext: 'Essential for authentic Vietnamese flavor',
    },
    {
      ingredient: 'chili peppers',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential heat for Vietnamese cuisine',
      usage: 'Pho, stir-fries, salads, dipping sauces',
      culturalContext: 'Vietnamese cuisine is known for its heat',
    },
    {
      ingredient: 'rice',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Staple grain for Vietnamese meals',
      usage: 'Steamed rice, fried rice, rice paper',
      culturalContext: 'Foundation of Vietnamese meals',
    },
    {
      ingredient: 'rice noodles',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential for Vietnamese noodle dishes',
      usage: 'Pho, bun, spring rolls, salads',
      culturalContext: 'Essential for authentic Vietnamese noodle dishes',
    },
    {
      ingredient: 'rice paper',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential for Vietnamese spring rolls',
      usage: 'Spring rolls, fresh rolls, appetizers',
      culturalContext: 'Essential for authentic Vietnamese spring rolls',
    },
    {
      ingredient: 'coconut milk',
      category: 'pantry_staples',
      priority: 'recommended',
      reason: 'Creamy base for Vietnamese curries',
      usage: 'Curries, desserts, beverages, soups',
      culturalContext: 'Important in Southern Vietnamese cuisine',
    },
    {
      ingredient: 'palm sugar',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Authentic sweetener for Vietnamese cuisine',
      usage: 'Marinades, sauces, desserts, balance',
      culturalContext: 'Essential for authentic Vietnamese sweetness',
    },
    {
      ingredient: 'star anise',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Essential spice for Vietnamese pho',
      usage: 'Pho broth, braised dishes, marinades',
      culturalContext: 'Essential for authentic Vietnamese pho',
    },
    {
      ingredient: 'cinnamon',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Essential spice for Vietnamese pho',
      usage: 'Pho broth, braised dishes, marinades',
      culturalContext: 'Essential for authentic Vietnamese pho',
    },
    {
      ingredient: 'bean sprouts',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Popular Vietnamese vegetable',
      usage: 'Pho, salads, spring rolls, stir-fries',
      culturalContext: 'Essential for authentic Vietnamese pho',
    },
  ],
};
