import { CuisineStaplesData } from '../types';

export const argentinian: CuisineStaplesData = {
  cuisine: 'Argentinian',
  description:
    'Essential ingredients for authentic Argentinian cooking with asado and empanadas',
  subStyles: [
    'Buenos Aires',
    'Córdoba',
    'Mendoza',
    'Traditional Argentinian',
    'Modern Argentinian',
  ],
  staples: [
    {
      ingredient: 'beef',
      category: 'proteins',
      priority: 'essential',
      reason: 'Essential protein for Argentinian cuisine',
      usage: 'Asado, main dishes, stews, side dishes',
      culturalContext: 'Beef is the soul of Argentinian cuisine',
    },
    {
      ingredient: 'onion',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Base ingredient for Argentinian cooking',
      usage: 'Asado, stews, main dishes, aromatics',
      culturalContext: 'Foundation of Argentinian flavor building',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Argentinian cooking',
      usage: 'Asado, marinades, sauces, main dishes',
      culturalContext: 'Foundation of Argentinian flavor building',
    },
    {
      ingredient: 'tomatoes',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential ingredient for Argentinian dishes',
      usage: 'Asado, stews, main dishes, sauces',
      culturalContext: 'Essential for authentic Argentinian dishes',
    },
    {
      ingredient: 'potatoes',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential vegetable for Argentinian cuisine',
      usage: 'Asado, main dishes, side dishes, soups',
      culturalContext: 'Potatoes are essential for Argentinian asado',
    },
    {
      ingredient: 'flour',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential for Argentinian baking and cooking',
      usage: 'Empanadas, bread, pastries, dumplings',
      culturalContext: 'Argentinian flour is essential for authentic baking',
    },
    {
      ingredient: 'eggs',
      category: 'proteins',
      priority: 'essential',
      reason: 'Essential protein for Argentinian cuisine',
      usage: 'Empanadas, baking, main dishes, desserts',
      culturalContext: 'Essential for Argentinian empanadas and baking',
    },
    {
      ingredient: 'butter',
      category: 'dairy_cold',
      priority: 'essential',
      reason: 'Essential cooking fat for Argentinian cuisine',
      usage: 'Cooking, baking, sauces, finishing',
      culturalContext: 'Essential for authentic Argentinian richness',
    },
    {
      ingredient: 'olive oil',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential cooking oil for Argentinian cuisine',
      usage: 'Cooking, dressings, marinades, finishing',
      culturalContext: 'Essential for authentic Argentinian cooking',
    },
    {
      ingredient: 'herbs',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential ingredients for Argentinian cuisine',
      usage: 'Asado, garnishes, marinades, main dishes, aromatics',
      culturalContext: 'Cannot make authentic Argentinian food without herbs',
    },
    {
      ingredient: 'spices',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential seasonings for Argentinian cuisine',
      usage: 'Asado, marinades, stews, main dishes, everything',
      culturalContext: 'Essential for authentic Argentinian flavor',
    },
    {
      ingredient: 'wine',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential beverage for Argentinian cuisine',
      usage: 'Cooking, marinades, sauces, drinking',
      culturalContext: 'Argentinian wine is world-famous',
    },
    {
      ingredient: 'vegetables',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Popular Argentinian ingredients',
      usage: 'Stews, stir-fries, main dishes, side dishes',
      culturalContext: 'Important in Argentinian cuisine',
    },
    {
      ingredient: 'cheese',
      category: 'dairy_cold',
      priority: 'recommended',
      reason: 'Popular Argentinian ingredient',
      usage: 'Empanadas, main dishes, snacks, side dishes',
      culturalContext: 'Important in Argentinian cuisine',
    },
    {
      ingredient: 'fish',
      category: 'proteins',
      priority: 'recommended',
      reason: 'Popular Argentinian protein',
      usage: 'Main dishes, soups, side dishes, traditional',
      culturalContext: 'Important in Argentinian cuisine',
    },
    {
      ingredient: 'chicken',
      category: 'proteins',
      priority: 'recommended',
      reason: 'Popular Argentinian protein',
      usage: 'Main dishes, stews, soups, side dishes',
      culturalContext: 'Important in Argentinian cuisine',
    },
  ],
};
