import { CuisineStaplesData } from '../types';

export const chilean: CuisineStaplesData = {
  cuisine: 'Chilean',
  description:
    'Essential ingredients for authentic Chilean cooking with ceviche and Chilean wine',
  subStyles: [
    'Santiago',
    'Valparaíso',
    'Concepción',
    'Traditional Chilean',
    'Modern Chilean',
  ],
  staples: [
    {
      ingredient: 'fish',
      category: 'proteins',
      priority: 'essential',
      reason: 'Essential protein for Chilean cuisine',
      usage: 'Ceviche, main dishes, soups, side dishes',
      culturalContext: 'Fish is the soul of Chilean cuisine',
    },
    {
      ingredient: 'onion',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Base ingredient for Chilean cooking',
      usage: 'Ceviche, stews, main dishes, aromatics',
      culturalContext: 'Foundation of Chilean flavor building',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Chilean cooking',
      usage: 'Ceviche, marinades, sauces, main dishes',
      culturalContext: 'Foundation of Chilean flavor building',
    },
    {
      ingredient: 'tomatoes',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential ingredient for Chilean dishes',
      usage: 'Ceviche, stews, main dishes, sauces',
      culturalContext: 'Essential for authentic Chilean dishes',
    },
    {
      ingredient: 'lemon',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential acid for Chilean cuisine',
      usage: 'Ceviche, dressings, marinades, finishing',
      culturalContext: 'Essential for authentic Chilean ceviche',
    },
    {
      ingredient: 'lime',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential acid for Chilean cuisine',
      usage: 'Ceviche, dressings, marinades, finishing',
      culturalContext: 'Essential for authentic Chilean ceviche',
    },
    {
      ingredient: 'olive oil',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential cooking oil for Chilean cuisine',
      usage: 'Ceviche, cooking, dressings, marinades, finishing',
      culturalContext: 'Essential for authentic Chilean cooking',
    },
    {
      ingredient: 'potatoes',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential vegetable for Chilean cuisine',
      usage: 'Ceviche, main dishes, side dishes, soups',
      culturalContext: 'Potatoes are essential for Chilean ceviche',
    },
    {
      ingredient: 'herbs',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential ingredients for Chilean cuisine',
      usage: 'Ceviche, garnishes, marinades, main dishes, aromatics',
      culturalContext: 'Cannot make authentic Chilean food without herbs',
    },
    {
      ingredient: 'spices',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential seasonings for Chilean cuisine',
      usage: 'Ceviche, marinades, stews, main dishes, everything',
      culturalContext: 'Essential for authentic Chilean flavor',
    },
    {
      ingredient: 'wine',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential beverage for Chilean cuisine',
      usage: 'Cooking, marinades, sauces, drinking',
      culturalContext: 'Chilean wine is world-famous',
    },
    {
      ingredient: 'vegetables',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential ingredients for Chilean cuisine',
      usage: 'Ceviche, stews, stir-fries, main dishes, side dishes',
      culturalContext: 'Essential for authentic Chilean dishes',
    },
    {
      ingredient: 'cheese',
      category: 'dairy_cold',
      priority: 'recommended',
      reason: 'Popular Chilean ingredient',
      usage: 'Main dishes, snacks, side dishes, traditional',
      culturalContext: 'Important in Chilean cuisine',
    },
    {
      ingredient: 'meat',
      category: 'proteins',
      priority: 'recommended',
      reason: 'Popular Chilean protein',
      usage: 'Main dishes, stews, soups, side dishes',
      culturalContext: 'Important in Chilean cuisine',
    },
    {
      ingredient: 'chicken',
      category: 'proteins',
      priority: 'recommended',
      reason: 'Popular Chilean protein',
      usage: 'Main dishes, stews, soups, side dishes',
      culturalContext: 'Important in Chilean cuisine',
    },
    {
      ingredient: 'rice',
      category: 'pantry_staples',
      priority: 'recommended',
      reason: 'Popular Chilean grain',
      usage: 'Main dishes, side dishes, everyday meals',
      culturalContext: 'Important in Chilean cuisine',
    },
  ],
};
