import { CuisineStaplesData } from '../types';

export const colombian: CuisineStaplesData = {
  cuisine: 'colombian',
  description:
    "Colombian cuisine reflects the country's diverse geography and cultural heritage, featuring hearty stews, tropical fruits, and coastal seafood.",
  staples: [
    {
      ingredient: 'rice',
      category: 'grains',
      priority: 'essential',
      reason: 'Base for most Colombian meals',
      usage: 'Arroz con pollo, paella, side dishes',
    },
    {
      ingredient: 'beans',
      category: 'legumes',
      priority: 'essential',
      reason: 'Staple protein source',
      usage: 'Frijoles, bandeja paisa, soups',
    },
    {
      ingredient: 'plantains',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Versatile cooking ingredient',
      usage: 'Fried, boiled, in soups and stews',
    },
    {
      ingredient: 'corn',
      category: 'grains',
      priority: 'essential',
      reason: 'Traditional staple grain',
      usage: 'Arepas, tamales, soups',
    },
    {
      ingredient: 'potatoes',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Highland staple',
      usage: 'Papas criollas, soups, side dishes',
    },
    {
      ingredient: 'onions',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Base for sofrito',
      usage: 'Sofrito, soups, stews',
    },
    {
      ingredient: 'garlic',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Essential flavor base',
      usage: 'Sofrito, marinades, seasoning',
    },
    {
      ingredient: 'tomatoes',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Base for sauces and stews',
      usage: 'Hogao, soups, stews',
    },
    {
      ingredient: 'cilantro',
      category: 'herbs',
      priority: 'essential',
      reason: 'Signature Colombian herb',
      usage: 'Garnish, seasoning, soups',
    },
    {
      ingredient: 'cumin',
      category: 'spices',
      priority: 'essential',
      reason: 'Essential spice blend',
      usage: 'Seasoning, marinades, stews',
    },
    {
      ingredient: 'paprika',
      category: 'spices',
      priority: 'essential',
      reason: 'Color and flavor',
      usage: 'Seasoning, marinades, rice dishes',
    },
    {
      ingredient: 'chicken',
      category: 'protein',
      priority: 'essential',
      reason: 'Primary protein source',
      usage: 'Arroz con pollo, soups, stews',
    },
    {
      ingredient: 'beef',
      category: 'protein',
      priority: 'essential',
      reason: 'Traditional protein',
      usage: 'Bandeja paisa, stews, grilled',
    },
    {
      ingredient: 'pork',
      category: 'protein',
      priority: 'essential',
      reason: 'Popular protein choice',
      usage: 'Chicharrón, stews, grilled',
    },
    {
      ingredient: 'fish',
      category: 'protein',
      priority: 'recommended',
      reason: 'Coastal cuisine staple',
      usage: 'Ceviche, fried fish, soups',
    },
    {
      ingredient: 'shrimp',
      category: 'protein',
      priority: 'recommended',
      reason: 'Coastal delicacy',
      usage: 'Ceviche, rice dishes, soups',
    },
    {
      ingredient: 'avocado',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Creamy texture and flavor',
      usage: 'Salads, side dishes, garnish',
    },
    {
      ingredient: 'lime',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Acidity and freshness',
      usage: 'Ceviche, marinades, drinks',
    },
    {
      ingredient: 'coconut',
      category: 'vegetables',
      priority: 'recommended',
      reason: 'Tropical flavor',
      usage: 'Rice dishes, desserts, drinks',
    },
    {
      ingredient: 'cassava',
      category: 'vegetables',
      priority: 'recommended',
      reason: 'Traditional root vegetable',
      usage: 'Bread, side dishes, soups',
    },
    {
      ingredient: 'sugar',
      category: 'sweeteners',
      priority: 'essential',
      reason: 'Sweetening agent',
      usage: 'Desserts, drinks, marinades',
    },
    {
      ingredient: 'salt',
      category: 'seasonings',
      priority: 'essential',
      reason: 'Basic seasoning',
      usage: 'All cooking, preservation',
    },
    {
      ingredient: 'black pepper',
      category: 'spices',
      priority: 'essential',
      reason: 'Basic seasoning',
      usage: 'All cooking, marinades',
    },
    {
      ingredient: 'oregano',
      category: 'herbs',
      priority: 'recommended',
      reason: 'Aromatic herb',
      usage: 'Soups, stews, marinades',
    },
    {
      ingredient: 'bay leaves',
      category: 'herbs',
      priority: 'recommended',
      reason: 'Aromatic seasoning',
      usage: 'Soups, stews, rice dishes',
    },
  ],
};
