import { CuisineStaplesData } from '../types';

export const ecuadorian: CuisineStaplesData = {
  cuisine: 'ecuadorian',
  description:
    'Ecuadorian cuisine varies by region from coastal seafood to highland potatoes, featuring diverse ingredients and Spanish influences.',
  staples: [
    {
      ingredient: 'rice',
      category: 'grains',
      priority: 'essential',
      reason: 'Staple grain nationwide',
      usage: 'Side dishes, rice dishes, soups',
    },
    {
      ingredient: 'potatoes',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Highland staple, many varieties',
      usage: 'Side dishes, soups, stews',
    },
    {
      ingredient: 'corn',
      category: 'grains',
      priority: 'essential',
      reason: 'Traditional grain',
      usage: 'Tamales, soups, side dishes',
    },
    {
      ingredient: 'beans',
      category: 'legumes',
      priority: 'essential',
      reason: 'Protein source',
      usage: 'Soups, side dishes, stews',
    },
    {
      ingredient: 'plantains',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Versatile cooking ingredient',
      usage: 'Fried, boiled, in soups and stews',
    },
    {
      ingredient: 'onions',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Base for sofrito',
      usage: 'Sofrito, seasoning, marinades',
    },
    {
      ingredient: 'garlic',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Essential flavor base',
      usage: 'Sofrito, marinades, seasoning',
    },
    {
      ingredient: 'tomatoes',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Base for sauces',
      usage: 'Sauces, stews, salads',
    },
    {
      ingredient: 'bell peppers',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Color and flavor',
      usage: 'Sofrito, salads, stuffed peppers',
    },
    {
      ingredient: 'cilantro',
      category: 'herbs',
      priority: 'essential',
      reason: 'Signature herb',
      usage: 'Garnish, seasoning, marinades',
    },
    {
      ingredient: 'cumin',
      category: 'spices',
      priority: 'essential',
      reason: 'Essential spice',
      usage: 'Seasoning, marinades, stews',
    },
    {
      ingredient: 'paprika',
      category: 'spices',
      priority: 'essential',
      reason: 'Color and flavor',
      usage: 'Seasoning, marinades',
    },
    {
      ingredient: 'chicken',
      category: 'protein',
      priority: 'essential',
      reason: 'Primary protein',
      usage: 'Grilled, stews, soups',
    },
    {
      ingredient: 'beef',
      category: 'protein',
      priority: 'essential',
      reason: 'Traditional protein',
      usage: 'Grilled, stews, soups',
    },
    {
      ingredient: 'pork',
      category: 'protein',
      priority: 'essential',
      reason: 'Popular protein',
      usage: 'Grilled, stews, sausages',
    },
    {
      ingredient: 'fish',
      category: 'protein',
      priority: 'essential',
      reason: 'Coastal cuisine staple',
      usage: 'Ceviche, fried fish, soups',
    },
    {
      ingredient: 'shrimp',
      category: 'protein',
      priority: 'essential',
      reason: 'Coastal delicacy',
      usage: 'Ceviche, rice dishes, soups',
    },
    {
      ingredient: 'crab',
      category: 'protein',
      priority: 'recommended',
      reason: 'Coastal specialty',
      usage: 'Ceviche, soups, rice dishes',
    },
    {
      ingredient: 'avocado',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Creamy texture',
      usage: 'Salads, side dishes, garnish',
    },
    {
      ingredient: 'lime',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Acidity and freshness',
      usage: 'Ceviche, marinades, drinks',
    },
    {
      ingredient: 'coconut',
      category: 'vegetables',
      priority: 'recommended',
      reason: 'Tropical flavor',
      usage: 'Rice dishes, desserts, drinks',
    },
    {
      ingredient: 'cassava',
      category: 'vegetables',
      priority: 'recommended',
      reason: 'Traditional root',
      usage: 'Bread, side dishes, soups',
    },
    {
      ingredient: 'cheese',
      category: 'dairy',
      priority: 'essential',
      reason: 'Dairy tradition',
      usage: 'Salads, side dishes, desserts',
    },
    {
      ingredient: 'eggs',
      category: 'dairy',
      priority: 'essential',
      reason: 'Versatile ingredient',
      usage: 'Breakfast, baking, side dishes',
    },
    {
      ingredient: 'milk',
      category: 'dairy',
      priority: 'essential',
      reason: 'Dairy base',
      usage: 'Sauces, desserts, drinks',
    },
    {
      ingredient: 'sugar',
      category: 'sweeteners',
      priority: 'essential',
      reason: 'Sweetening',
      usage: 'Desserts, drinks, marinades',
    },
    {
      ingredient: 'salt',
      category: 'seasonings',
      priority: 'essential',
      reason: 'Basic seasoning',
      usage: 'All cooking',
    },
    {
      ingredient: 'black pepper',
      category: 'spices',
      priority: 'essential',
      reason: 'Basic seasoning',
      usage: 'All cooking',
    },
    {
      ingredient: 'oregano',
      category: 'herbs',
      priority: 'recommended',
      reason: 'Aromatic herb',
      usage: 'Soups, stews, marinades',
    },
    {
      ingredient: 'bay leaves',
      category: 'herbs',
      priority: 'recommended',
      reason: 'Aromatic seasoning',
      usage: 'Soups, stews, rice dishes',
    },
  ],
};
