import { CuisineStaplesData } from '../types';

export const paraguayan: CuisineStaplesData = {
  cuisine: 'paraguayan',
  description:
    'Paraguayan cuisine features corn-based dishes, tropical fruits, and indigenous ingredients with Spanish and Guarani influences.',
  staples: [
    {
      ingredient: 'corn',
      category: 'grains',
      priority: 'essential',
      reason: 'Traditional staple grain',
      usage: 'Sopa paraguaya, chipa, tamales',
    },
    {
      ingredient: 'cassava',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Traditional root vegetable',
      usage: 'Bread, side dishes, soups',
    },
    {
      ingredient: 'rice',
      category: 'grains',
      priority: 'essential',
      reason: 'Staple grain',
      usage: 'Side dishes, rice dishes',
    },
    {
      ingredient: 'beans',
      category: 'legumes',
      priority: 'essential',
      reason: 'Protein source',
      usage: 'Soups, side dishes, stews',
    },
    {
      ingredient: 'onions',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Base for sofrito',
      usage: 'Sofrito, seasoning, marinades',
    },
    {
      ingredient: 'garlic',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Essential flavor base',
      usage: 'Sofrito, marinades, seasoning',
    },
    {
      ingredient: 'tomatoes',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Base for sauces',
      usage: 'Sauces, stews, salads',
    },
    {
      ingredient: 'bell peppers',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Color and flavor',
      usage: 'Sofrito, salads, stuffed peppers',
    },
    {
      ingredient: 'cilantro',
      category: 'herbs',
      priority: 'essential',
      reason: 'Signature herb',
      usage: 'Garnish, seasoning, marinades',
    },
    {
      ingredient: 'cumin',
      category: 'spices',
      priority: 'essential',
      reason: 'Essential spice',
      usage: 'Seasoning, marinades, stews',
    },
    {
      ingredient: 'paprika',
      category: 'spices',
      priority: 'essential',
      reason: 'Color and flavor',
      usage: 'Seasoning, marinades',
    },
    {
      ingredient: 'chicken',
      category: 'protein',
      priority: 'essential',
      reason: 'Primary protein',
      usage: 'Grilled, stews, soups',
    },
    {
      ingredient: 'beef',
      category: 'protein',
      priority: 'essential',
      reason: 'Traditional protein',
      usage: 'Grilled, stews, soups',
    },
    {
      ingredient: 'pork',
      category: 'protein',
      priority: 'essential',
      reason: 'Popular protein',
      usage: 'Grilled, stews, sausages',
    },
    {
      ingredient: 'fish',
      category: 'protein',
      priority: 'recommended',
      reason: 'River fish',
      usage: 'Grilled, stews, soups',
    },
    {
      ingredient: 'cheese',
      category: 'dairy',
      priority: 'essential',
      reason: 'Dairy tradition',
      usage: 'Sopa paraguaya, chipa, salads',
    },
    {
      ingredient: 'eggs',
      category: 'dairy',
      priority: 'essential',
      reason: 'Versatile ingredient',
      usage: 'Sopa paraguaya, chipa, breakfast',
    },
    {
      ingredient: 'milk',
      category: 'dairy',
      priority: 'essential',
      reason: 'Dairy base',
      usage: 'Sauces, desserts, drinks',
    },
    {
      ingredient: 'avocado',
      category: 'vegetables',
      priority: 'recommended',
      reason: 'Creamy texture',
      usage: 'Salads, side dishes, garnish',
    },
    {
      ingredient: 'lime',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Acidity and freshness',
      usage: 'Marinades, drinks, ceviche',
    },
    {
      ingredient: 'sugar',
      category: 'sweeteners',
      priority: 'essential',
      reason: 'Sweetening',
      usage: 'Desserts, drinks, marinades',
    },
    {
      ingredient: 'salt',
      category: 'seasonings',
      priority: 'essential',
      reason: 'Basic seasoning',
      usage: 'All cooking',
    },
    {
      ingredient: 'black pepper',
      category: 'spices',
      priority: 'essential',
      reason: 'Basic seasoning',
      usage: 'All cooking',
    },
    {
      ingredient: 'oregano',
      category: 'herbs',
      priority: 'recommended',
      reason: 'Aromatic herb',
      usage: 'Soups, stews, marinades',
    },
    {
      ingredient: 'bay leaves',
      category: 'herbs',
      priority: 'recommended',
      reason: 'Aromatic seasoning',
      usage: 'Soups, stews, rice dishes',
    },
  ],
};
