import { CuisineStaplesData } from '../types';

export const uruguayan: CuisineStaplesData = {
  cuisine: 'uruguayan',
  description:
    'Uruguayan cuisine is heavily influenced by Italian and Spanish traditions, featuring grilled meats, pasta, and Mediterranean flavors.',
  staples: [
    {
      ingredient: 'beef',
      category: 'protein',
      priority: 'essential',
      reason: 'National obsession with beef',
      usage: 'Asado, churrasco, milanesas',
    },
    {
      ingredient: 'rice',
      category: 'grains',
      priority: 'essential',
      reason: 'Staple grain',
      usage: 'Side dishes, paella, risotto',
    },
    {
      ingredient: 'pasta',
      category: 'grains',
      priority: 'essential',
      reason: 'Italian influence',
      usage: 'Spaghetti, ravioli, gnocchi',
    },
    {
      ingredient: 'potatoes',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Versatile vegetable',
      usage: 'Side dishes, gnocchi, salads',
    },
    {
      ingredient: 'onions',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Base for sofrito',
      usage: 'Sofrito, salads, marinades',
    },
    {
      ingredient: 'garlic',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Essential flavor base',
      usage: 'Sofrito, marinades, seasoning',
    },
    {
      ingredient: 'tomatoes',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Base for sauces',
      usage: 'Sauces, salads, stews',
    },
    {
      ingredient: 'bell peppers',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Color and flavor',
      usage: 'Sofrito, salads, stuffed peppers',
    },
    {
      ingredient: 'olive oil',
      category: 'fats',
      priority: 'essential',
      reason: 'Mediterranean influence',
      usage: 'Cooking, dressings, marinades',
    },
    {
      ingredient: 'oregano',
      category: 'herbs',
      priority: 'essential',
      reason: 'Mediterranean herb',
      usage: 'Seasoning, marinades, sauces',
    },
    {
      ingredient: 'basil',
      category: 'herbs',
      priority: 'recommended',
      reason: 'Italian influence',
      usage: 'Pasta sauces, salads, marinades',
    },
    {
      ingredient: 'parsley',
      category: 'herbs',
      priority: 'recommended',
      reason: 'Fresh herb garnish',
      usage: 'Garnish, seasoning, marinades',
    },
    {
      ingredient: 'chicken',
      category: 'protein',
      priority: 'essential',
      reason: 'Alternative protein',
      usage: 'Grilled, stews, milanesas',
    },
    {
      ingredient: 'pork',
      category: 'protein',
      priority: 'essential',
      reason: 'Popular protein',
      usage: 'Churrasco, stews, grilled',
    },
    {
      ingredient: 'fish',
      category: 'protein',
      priority: 'recommended',
      reason: 'Coastal cuisine',
      usage: 'Grilled, ceviche, stews',
    },
    {
      ingredient: 'cheese',
      category: 'dairy',
      priority: 'essential',
      reason: 'Dairy tradition',
      usage: 'Pasta, salads, sandwiches',
    },
    {
      ingredient: 'eggs',
      category: 'dairy',
      priority: 'essential',
      reason: 'Versatile ingredient',
      usage: 'Milanesas, pasta, breakfast',
    },
    {
      ingredient: 'milk',
      category: 'dairy',
      priority: 'essential',
      reason: 'Dairy base',
      usage: 'Sauces, desserts, drinks',
    },
    {
      ingredient: 'wine',
      category: 'beverages',
      priority: 'recommended',
      reason: 'Wine culture',
      usage: 'Cooking, marinades, drinking',
    },
    {
      ingredient: 'salt',
      category: 'seasonings',
      priority: 'essential',
      reason: 'Basic seasoning',
      usage: 'All cooking',
    },
    {
      ingredient: 'black pepper',
      category: 'spices',
      priority: 'essential',
      reason: 'Basic seasoning',
      usage: 'All cooking',
    },
    {
      ingredient: 'paprika',
      category: 'spices',
      priority: 'recommended',
      reason: 'Color and flavor',
      usage: 'Seasoning, marinades',
    },
    {
      ingredient: 'bay leaves',
      category: 'herbs',
      priority: 'recommended',
      reason: 'Aromatic seasoning',
      usage: 'Soups, stews, rice dishes',
    },
    {
      ingredient: 'thyme',
      category: 'herbs',
      priority: 'recommended',
      reason: 'Aromatic herb',
      usage: 'Soups, stews, marinades',
    },
  ],
};
