import { CuisineStaplesData } from '../types';

export const venezuelan: CuisineStaplesData = {
  cuisine: 'venezuelan',
  description:
    'Venezuelan cuisine is characterized by its arepas, tropical fruits, and coastal influences, with a strong emphasis on corn-based dishes.',
  staples: [
    {
      ingredient: 'corn',
      category: 'grains',
      priority: 'essential',
      reason: 'Base for arepas and traditional dishes',
      usage: 'Arepas, cachapas, tamales',
    },
    {
      ingredient: 'rice',
      category: 'grains',
      priority: 'essential',
      reason: 'Staple grain',
      usage: 'Side dishes, rice dishes',
    },
    {
      ingredient: 'black beans',
      category: 'legumes',
      priority: 'essential',
      reason: 'Traditional protein source',
      usage: 'Caraotas, side dishes, soups',
    },
    {
      ingredient: 'plantains',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Versatile cooking ingredient',
      usage: 'Fried, boiled, in stews',
    },
    {
      ingredient: 'onions',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Base for sofrito',
      usage: 'Sofrito, seasoning, marinades',
    },
    {
      ingredient: 'garlic',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Essential flavor base',
      usage: 'Sofrito, marinades, seasoning',
    },
    {
      ingredient: 'tomatoes',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Base for sauces',
      usage: 'Sauces, stews, salads',
    },
    {
      ingredient: 'bell peppers',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Color and flavor',
      usage: 'Sofrito, salads, stuffed peppers',
    },
    {
      ingredient: 'cilantro',
      category: 'herbs',
      priority: 'essential',
      reason: 'Signature herb',
      usage: 'Garnish, seasoning, marinades',
    },
    {
      ingredient: 'cumin',
      category: 'spices',
      priority: 'essential',
      reason: 'Essential spice',
      usage: 'Seasoning, marinades, stews',
    },
    {
      ingredient: 'paprika',
      category: 'spices',
      priority: 'essential',
      reason: 'Color and flavor',
      usage: 'Seasoning, marinades',
    },
    {
      ingredient: 'chicken',
      category: 'protein',
      priority: 'essential',
      reason: 'Primary protein',
      usage: 'Grilled, stews, arepa fillings',
    },
    {
      ingredient: 'beef',
      category: 'protein',
      priority: 'essential',
      reason: 'Traditional protein',
      usage: 'Carne mechada, stews, grilled',
    },
    {
      ingredient: 'pork',
      category: 'protein',
      priority: 'essential',
      reason: 'Popular protein',
      usage: 'Chicharrón, stews, grilled',
    },
    {
      ingredient: 'fish',
      category: 'protein',
      priority: 'recommended',
      reason: 'Coastal cuisine',
      usage: 'Fried fish, ceviche, stews',
    },
    {
      ingredient: 'shrimp',
      category: 'protein',
      priority: 'recommended',
      reason: 'Coastal delicacy',
      usage: 'Ceviche, rice dishes, arepa fillings',
    },
    {
      ingredient: 'avocado',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Creamy texture',
      usage: 'Salads, side dishes, garnish',
    },
    {
      ingredient: 'lime',
      category: 'vegetables',
      priority: 'essential',
      reason: 'Acidity and freshness',
      usage: 'Ceviche, marinades, drinks',
    },
    {
      ingredient: 'coconut',
      category: 'vegetables',
      priority: 'recommended',
      reason: 'Tropical flavor',
      usage: 'Desserts, drinks, rice dishes',
    },
    {
      ingredient: 'cassava',
      category: 'vegetables',
      priority: 'recommended',
      reason: 'Traditional root',
      usage: 'Bread, side dishes, soups',
    },
    {
      ingredient: 'sugar',
      category: 'sweeteners',
      priority: 'essential',
      reason: 'Sweetening',
      usage: 'Desserts, drinks, marinades',
    },
    {
      ingredient: 'salt',
      category: 'seasonings',
      priority: 'essential',
      reason: 'Basic seasoning',
      usage: 'All cooking',
    },
    {
      ingredient: 'black pepper',
      category: 'spices',
      priority: 'essential',
      reason: 'Basic seasoning',
      usage: 'All cooking',
    },
    {
      ingredient: 'oregano',
      category: 'herbs',
      priority: 'recommended',
      reason: 'Aromatic herb',
      usage: 'Soups, stews, marinades',
    },
    {
      ingredient: 'bay leaves',
      category: 'herbs',
      priority: 'recommended',
      reason: 'Aromatic seasoning',
      usage: 'Soups, stews, rice dishes',
    },
  ],
};
