import { CuisineStaplesData } from '../../cuisine-staples/types';

export const belgian: CuisineStaplesData = {
  cuisine: 'Belgian',
  description:
    'Essential ingredients for authentic Belgian cooking with moules-frites and waffles',
  subStyles: [
    'Brussels',
    'Antwerp',
    'Ghent',
    'Traditional Belgian',
    'Modern Belgian',
  ],
  staples: [
    {
      ingredient: 'mussels',
      category: 'proteins',
      priority: 'essential',
      reason: 'Essential protein for Belgian cuisine',
      usage: 'Moules-frites, main dishes, stews, side dishes',
      culturalContext: 'Mussels are the soul of Belgian cuisine',
    },
    {
      ingredient: 'potatoes',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential vegetable for Belgian cuisine',
      usage: 'Moules-frites, main dishes, side dishes, soups',
      culturalContext: 'Potatoes are essential for Belgian moules-frites',
    },
    {
      ingredient: 'onion',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Base ingredient for Belgian cooking',
      usage: 'Moules-frites, stews, main dishes, aromatics',
      culturalContext: 'Foundation of Belgian flavor building',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Belgian cooking',
      usage: 'Moules-frites, marinades, sauces, main dishes',
      culturalContext: 'Foundation of Belgian flavor building',
    },
    {
      ingredient: 'white wine',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential liquid for Belgian cuisine',
      usage: 'Moules-frites, cooking, marinades, sauces',
      culturalContext: 'Essential for authentic Belgian moules-frites',
    },
    {
      ingredient: 'butter',
      category: 'dairy_cold',
      priority: 'essential',
      reason: 'Essential cooking fat for Belgian cuisine',
      usage: 'Cooking, baking, sauces, finishing',
      culturalContext: 'Essential for authentic Belgian richness',
    },
    {
      ingredient: 'flour',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential for Belgian baking and cooking',
      usage: 'Waffles, bread, pastries, dumplings',
      culturalContext: 'Belgian flour is essential for authentic baking',
    },
    {
      ingredient: 'eggs',
      category: 'proteins',
      priority: 'essential',
      reason: 'Essential protein for Belgian cuisine',
      usage: 'Waffles, baking, main dishes, desserts',
      culturalContext: 'Essential for Belgian waffles and baking',
    },
    {
      ingredient: 'sugar',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential sweetener for Belgian cuisine',
      usage: 'Waffles, desserts, baking, main dishes',
      culturalContext: 'Essential for Belgian waffles and desserts',
    },
    {
      ingredient: 'milk',
      category: 'dairy_cold',
      priority: 'essential',
      reason: 'Essential dairy for Belgian cuisine',
      usage: 'Waffles, desserts, beverages, main dishes',
      culturalContext: 'Essential for Belgian waffles and desserts',
    },
    {
      ingredient: 'chocolate',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential ingredient for Belgian cuisine',
      usage: 'Desserts, beverages, main dishes, side dishes',
      culturalContext: 'Belgian chocolate is world-famous',
    },
    {
      ingredient: 'beer',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential beverage for Belgian cuisine',
      usage: 'Cooking, marinades, sauces, drinking',
      culturalContext: 'Belgian beer is world-famous',
    },
    {
      ingredient: 'herbs',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Popular Belgian ingredients',
      usage: 'Garnishes, marinades, main dishes, aromatics',
      culturalContext: 'Important in Belgian cuisine',
    },
    {
      ingredient: 'spices',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Popular Belgian ingredients',
      usage: 'Marinades, stews, main dishes, everything',
      culturalContext: 'Important in Belgian cuisine',
    },
    {
      ingredient: 'vegetables',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Popular Belgian ingredients',
      usage: 'Stews, stir-fries, main dishes, side dishes',
      culturalContext: 'Important in Belgian cuisine',
    },
    {
      ingredient: 'cheese',
      category: 'dairy_cold',
      priority: 'recommended',
      reason: 'Popular Belgian ingredient',
      usage: 'Main dishes, snacks, side dishes, traditional',
      culturalContext: 'Important in Belgian cuisine',
    },
  ],
};
