import { CuisineStaplesData } from '../../cuisine-staples/types';

export const french: CuisineStaplesData = {
  cuisine: 'French',
  description:
    'Foundational French pantry and aromatics for classic techniques',
  subStyles: ['Provence', 'Burgundy', 'Normandy', 'Lyonnaise', 'Parisian'],
  staples: [
    {
      ingredient: 'butter',
      category: 'dairy_cold',
      priority: 'essential',
      reason: 'Primary cooking fat',
      usage: 'Sauces, sautés, baking',
    },
    {
      ingredient: 'olive oil',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Cooking and finishing',
      usage: 'Provençal dishes, dressings',
    },
    {
      ingredient: 'onion',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Mirepoix base',
      usage: 'Soups, sauces, stews',
    },
    {
      ingredient: 'carrot',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Mirepoix base',
      usage: 'Soups, sauces, stews',
    },
    {
      ingredient: 'celery',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Mirepoix base',
      usage: 'Soups, sauces, stews',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Aromatic',
      usage: 'Sauces, sautés',
    },
    {
      ingredient: 'thyme',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Bouquet garni',
      usage: 'Stocks, stews',
    },
    {
      ingredient: 'bay leaves',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Bouquet garni',
      usage: 'Stocks, stews',
    },
    {
      ingredient: 'white wine',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Deglazing and sauces',
      usage: 'Beurre blanc, braises',
    },
    {
      ingredient: 'cream',
      category: 'dairy_cold',
      priority: 'recommended',
      reason: 'Richness for sauces',
      usage: 'Sauces, soups, desserts',
    },
    {
      ingredient: 'flour',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Roux and baking',
      usage: 'Sauces, breads, pastries',
    },
    {
      ingredient: 'eggs',
      category: 'proteins',
      priority: 'essential',
      reason: 'Binding and structure',
      usage: 'Custards, baking',
    },
    {
      ingredient: 'herbes de Provence',
      category: 'flavor_builders',
      priority: 'optional',
      reason: 'Herbal blend',
      usage: 'Roasts, vegetables',
    },
    {
      ingredient: 'dijon mustard',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Sharp acidity',
      usage: 'Dressings, sauces',
    },
    {
      ingredient: 'shallots',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Finer onion flavor',
      usage: 'Sauces, vinaigrettes',
    },
  ],
};
