import { CuisineStaplesData } from '../types';

export const italian: CuisineStaplesData = {
  cuisine: 'Italian',
  description: 'Core Italian pantry and fresh items for classic dishes',
  subStyles: ['Northern', 'Central', 'Southern', 'Tuscan', 'Roman', 'Sicilian'],
  staples: [
    {
      ingredient: 'olive oil',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Primary cooking and finishing fat',
      usage: 'Sauces, sautés, dressings',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Base aromatic',
      usage: 'Sauces, sautés, roasts',
    },
    {
      ingredient: 'onion',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Base aromatic',
      usage: 'Soffritto, sauces, stews',
    },
    {
      ingredient: 'tomatoes',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Sauce and base',
      usage: 'Passata, sugo, ragù',
    },
    {
      ingredient: 'tomato paste',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Concentrated tomato flavor',
      usage: 'Sauces, braises',
    },
    {
      ingredient: 'basil',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Signature herb',
      usage: 'Pasta, pizza, salads',
    },
    {
      ingredient: 'oregano',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Classic herb',
      usage: 'Sauces, pizza',
    },
    {
      ingredient: 'parmesan',
      category: 'dairy_cold',
      priority: 'essential',
      reason: 'Umami and finishing',
      usage: 'Pasta, risotto',
    },
    {
      ingredient: 'mozzarella',
      category: 'dairy_cold',
      priority: 'recommended',
      reason: 'Cheese staple',
      usage: 'Pizza, caprese',
    },
    {
      ingredient: 'pasta',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Core carbohydrate',
      usage: 'Main dishes',
    },
    {
      ingredient: 'risotto rice',
      category: 'pantry_staples',
      priority: 'recommended',
      reason: 'Regional staple',
      usage: 'Risotto',
    },
    {
      ingredient: 'balsamic vinegar',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Acidity and sweetness',
      usage: 'Dressings, glazes',
    },
    {
      ingredient: 'red wine',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Deglazing and sauces',
      usage: 'Ragù, braises',
    },
    {
      ingredient: 'anchovies',
      category: 'flavor_builders',
      priority: 'optional',
      reason: 'Umami booster',
      usage: 'Sauces, dressings',
    },
    {
      ingredient: 'capers',
      category: 'flavor_builders',
      priority: 'optional',
      reason: 'Briny pop',
      usage: 'Puttanesca, piccata',
    },
    {
      ingredient: 'bread',
      category: 'pantry_staples',
      priority: 'recommended',
      reason: 'Traditional staple',
      usage: 'Bruschetta, sides',
    },
  ],
};
