import { CuisineStaplesData } from '../../cuisine-staples/types';

export const portuguese: CuisineStaplesData = {
  cuisine: 'Portuguese',
  description:
    'Essential ingredients for authentic Portuguese cooking with bacalhau and pastéis de nata',
  subStyles: [
    'Lisbon',
    'Porto',
    'Algarve',
    'Traditional Portuguese',
    'Modern Portuguese',
  ],
  staples: [
    {
      ingredient: 'cod',
      category: 'proteins',
      priority: 'essential',
      reason: 'Essential protein for Portuguese cuisine',
      usage: 'Bacalhau, main dishes, stews, side dishes',
      culturalContext: 'Cod is the soul of Portuguese cuisine',
    },
    {
      ingredient: 'olive oil',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential cooking oil for Portuguese cuisine',
      usage: 'Cooking, dressings, marinades, finishing',
      culturalContext: 'Essential for authentic Portuguese cooking',
    },
    {
      ingredient: 'onion',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Base ingredient for Portuguese cooking',
      usage: 'Bacalhau, stews, main dishes, aromatics',
      culturalContext: 'Foundation of Portuguese flavor building',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Portuguese cooking',
      usage: 'Bacalhau, marinades, sauces, main dishes',
      culturalContext: 'Foundation of Portuguese flavor building',
    },
    {
      ingredient: 'tomatoes',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential ingredient for Portuguese dishes',
      usage: 'Bacalhau, stews, main dishes, sauces',
      culturalContext: 'Essential for authentic Portuguese dishes',
    },
    {
      ingredient: 'potatoes',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential vegetable for Portuguese cuisine',
      usage: 'Bacalhau, main dishes, side dishes, soups',
      culturalContext: 'Potatoes are essential for Portuguese bacalhau',
    },
    {
      ingredient: 'eggs',
      category: 'proteins',
      priority: 'essential',
      reason: 'Essential protein for Portuguese cuisine',
      usage: 'Pastéis de nata, baking, main dishes, desserts',
      culturalContext: 'Essential for Portuguese pastries and desserts',
    },
    {
      ingredient: 'flour',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential for Portuguese baking and cooking',
      usage: 'Pastéis de nata, bread, pastries, dumplings',
      culturalContext: 'Portuguese flour is essential for authentic baking',
    },
    {
      ingredient: 'sugar',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential sweetener for Portuguese cuisine',
      usage: 'Pastéis de nata, desserts, baking, main dishes',
      culturalContext: 'Essential for Portuguese pastries and desserts',
    },
    {
      ingredient: 'milk',
      category: 'dairy_cold',
      priority: 'essential',
      reason: 'Essential dairy for Portuguese cuisine',
      usage: 'Pastéis de nata, desserts, beverages, main dishes',
      culturalContext: 'Essential for Portuguese pastries and desserts',
    },
    {
      ingredient: 'butter',
      category: 'dairy_cold',
      priority: 'essential',
      reason: 'Essential cooking fat for Portuguese cuisine',
      usage: 'Cooking, baking, sauces, finishing',
      culturalContext: 'Essential for authentic Portuguese richness',
    },
    {
      ingredient: 'bay leaves',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential herb for Portuguese cooking',
      usage: 'Bacalhau, stews, marinades, main dishes',
      culturalContext:
        'Cannot make authentic Portuguese bacalhau without bay leaves',
    },
    {
      ingredient: 'wine',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Popular Portuguese ingredient',
      usage: 'Cooking, marinades, sauces, drinking',
      culturalContext: 'Portuguese wine is important in the cuisine',
    },
    {
      ingredient: 'herbs',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Popular Portuguese ingredients',
      usage: 'Garnishes, marinades, main dishes, aromatics',
      culturalContext: 'Important in Portuguese cuisine',
    },
    {
      ingredient: 'spices',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Popular Portuguese ingredients',
      usage: 'Marinades, stews, main dishes, everything',
      culturalContext: 'Important in Portuguese cuisine',
    },
    {
      ingredient: 'vegetables',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Popular Portuguese ingredients',
      usage: 'Stews, stir-fries, main dishes, side dishes',
      culturalContext: 'Important in Portuguese cuisine',
    },
  ],
};
