import { CuisineStaplesData } from '../../cuisine-staples/types';

export const swiss: CuisineStaplesData = {
  cuisine: 'Swiss',
  description:
    'Essential ingredients for authentic Swiss cooking with fondue and raclette',
  subStyles: ['Zurich', 'Geneva', 'Bern', 'Traditional Swiss', 'Modern Swiss'],
  staples: [
    {
      ingredient: 'cheese',
      category: 'dairy_cold',
      priority: 'essential',
      reason: 'Essential dairy for Swiss cuisine',
      usage: 'Fondue, raclette, main dishes, snacks, side dishes',
      culturalContext: 'Cheese is the soul of Swiss cuisine',
    },
    {
      ingredient: 'bread',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential staple for Swiss cuisine',
      usage: 'Fondue, raclette, main dishes, side dishes, snacks',
      culturalContext: 'Essential for Swiss fondue and raclette',
    },
    {
      ingredient: 'potatoes',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential vegetable for Swiss cuisine',
      usage: 'Raclette, main dishes, side dishes, soups',
      culturalContext: 'Potatoes are essential for Swiss raclette',
    },
    {
      ingredient: 'onion',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Base ingredient for Swiss cooking',
      usage: 'Fondue, raclette, stews, main dishes, aromatics',
      culturalContext: 'Foundation of Swiss flavor building',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Essential aromatic for Swiss cooking',
      usage: 'Fondue, raclette, marinades, sauces, main dishes',
      culturalContext: 'Foundation of Swiss flavor building',
    },
    {
      ingredient: 'white wine',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Essential liquid for Swiss cuisine',
      usage: 'Fondue, cooking, marinades, sauces',
      culturalContext: 'Essential for authentic Swiss fondue',
    },
    {
      ingredient: 'butter',
      category: 'dairy_cold',
      priority: 'essential',
      reason: 'Essential cooking fat for Swiss cuisine',
      usage: 'Cooking, baking, sauces, finishing',
      culturalContext: 'Essential for authentic Swiss richness',
    },
    {
      ingredient: 'flour',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Essential for Swiss baking and cooking',
      usage: 'Bread, pastries, dumplings, thickening',
      culturalContext: 'Swiss flour is essential for authentic baking',
    },
    {
      ingredient: 'eggs',
      category: 'proteins',
      priority: 'essential',
      reason: 'Essential protein for Swiss cuisine',
      usage: 'Baking, main dishes, desserts, side dishes',
      culturalContext: 'Essential for Swiss baking and main dishes',
    },
    {
      ingredient: 'milk',
      category: 'dairy_cold',
      priority: 'essential',
      reason: 'Essential dairy for Swiss cuisine',
      usage: 'Fondue, desserts, beverages, main dishes',
      culturalContext: 'Essential for Swiss fondue and desserts',
    },
    {
      ingredient: 'cream',
      category: 'dairy_cold',
      priority: 'essential',
      reason: 'Essential dairy for Swiss cuisine',
      usage: 'Fondue, sauces, desserts, main dishes, beverages',
      culturalContext: 'Essential for Swiss fondue and cream sauces',
    },
    {
      ingredient: 'herbs',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Popular Swiss ingredients',
      usage: 'Garnishes, marinades, main dishes, aromatics',
      culturalContext: 'Important in Swiss cuisine',
    },
    {
      ingredient: 'spices',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Popular Swiss ingredients',
      usage: 'Marinades, stews, main dishes, everything',
      culturalContext: 'Important in Swiss cuisine',
    },
    {
      ingredient: 'vegetables',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Popular Swiss ingredients',
      usage: 'Stews, stir-fries, main dishes, side dishes',
      culturalContext: 'Important in Swiss cuisine',
    },
    {
      ingredient: 'meat',
      category: 'proteins',
      priority: 'recommended',
      reason: 'Popular Swiss protein',
      usage: 'Main dishes, stews, soups, side dishes',
      culturalContext: 'Important in Swiss cuisine',
    },
    {
      ingredient: 'wine',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Popular Swiss ingredient',
      usage: 'Cooking, marinades, sauces, drinking',
      culturalContext: 'Swiss wine is important in the cuisine',
    },
  ],
};
