/*
 * Chef Isabella's "Kitchen Reality" - Fresh Produce Category
 *
 * "The Perishables" - same storage needs, same shopping trip, same urgency to use
 * Everything that wilts or goes bad quickly
 */

export const FRESH_PRODUCE: string[] = [
  // 📅 Use this week (delicate - high priority)
  'Spinach',
  'Arugula',
  'Lettuce',
  'Mixed Greens',
  'Basil',
  'Cilantro',
  'Parsley',
  'Berries',
  'Strawberries',
  'Raspberries',
  'Blackberries',
  'Blueberries',
  'Avocados',
  'Bananas',
  'Mushrooms',
  'Asparagus',
  'Green Beans',
  'Zucchini',
  'Yellow Squash',
  'Eggplant',

  // 💪 Keeps longer (hardy vegetables & fruits)
  'Onions',
  'Yellow Onions',
  'Red Onions',
  'White Onions',
  'Garlic',
  'Carrots',
  'Celery',
  'Bell Peppers',
  'Red Bell Peppers',
  'Green Bell Peppers',
  'Potatoes',
  'Sweet Potatoes',
  'Broccoli',
  'Cauliflower',
  'Cabbage',
  'Kale',
  'Brussels Sprouts',
  'Cucumbers',
  'Tomatoes',
  'Cherry Tomatoes',
  'Apples',
  'Oranges',
  'Lemons',
  'Limes',
  'Ginger',
  'Beets',
  'Radishes',
  'Turnips',
  'Parsnips',
  'Butternut Squash',
  'Acorn Squash',

  // 🌿 Fresh herbs & aromatics
  'Fresh Rosemary',
  'Fresh Thyme',
  'Fresh Oregano',
  'Fresh Sage',
  'Fresh Mint',
  'Fresh Dill',
  'Chives',
  'Green Onions',
  'Scallions',
  'Jalapeños',
  'Serrano Peppers',
  'Habanero Peppers',
  'Poblano Peppers',
  'Lemongrass',
  'Fresh Ginger Root',
];
