/*
 * Chef Isabella's "Kitchen Reality" - Pantry Staples Category
 *
 * "The Reliable Backups" - long shelf life, backup ingredients, emergency cooking
 * Your "pantry cabinet" items
 */

export const PANTRY_STAPLES: string[] = [
  // 🥫 Canned goods (the reliable backups)
  'Canned Tomatoes',
  'Crushed Tomatoes',
  'Diced Tomatoes',
  'Whole Tomatoes',
  'Tomato Paste',
  'Tomato Sauce',
  'Marinara Sauce',
  'Pizza Sauce',
  'Canned Beans',
  'Black Beans',
  'Kidney Beans',
  'Pinto Beans',
  'Chickpeas',
  'White Beans',
  'Navy Beans',
  'Refried Beans',
  'Canned Corn',
  'Canned Peas',
  'Canned Carrots',
  'Canned Green Beans',
  'Canned Tuna',
  'Canned Salmon',
  'Canned Sardines',
  'Canned Chicken',
  'Chicken Broth',
  'Vegetable Broth',
  'Beef Broth',
  'Coconut Milk',
  'Canned Pumpkin',
  'Canned Sweet Potato',
  'Canned Peaches',
  'Canned Pears',

  // 🍯 Condiments & flavor enhancers
  'Ketchup',
  'Mustard',
  'Dijon Mustard',
  'Whole Grain Mustard',
  'Mayonnaise',
  'Soy Sauce',
  'Low Sodium Soy Sauce',
  'Tamari',
  'Sriracha',
  'Hot Sauce',
  'BBQ Sauce',
  'Teriyaki Sauce',
  'Hoisin Sauce',
  'Oyster Sauce',
  'Peanut Butter',
  'Almond Butter',
  'Sunflower Seed Butter',
  'Tahini',
  'Jam',
  'Strawberry Jam',
  'Grape Jelly',
  'Orange Marmalade',
  'Nutella',
  'Honey',
  'Maple Syrup',
  'Agave Nectar',
  'Brown Sugar',
  'White Sugar',
  'Powdered Sugar',
  'Vanilla Extract',

  // 📦 Dry goods & snacks
  'Crackers',
  'Saltines',
  'Graham Crackers',
  'Breadcrumbs',
  'Panko',
  'Cereal',
  'Granola',
  'Oatmeal',
  'Instant Oatmeal',
  'Popcorn',
  'Nuts',
  'Mixed Nuts',
  'Peanuts',
  'Almonds',
  'Walnuts',
  'Pecans',
  'Raisins',
  'Dried Cranberries',
  'Dates',
  'Dried Fruit',
  'Soup',
  'Chicken Noodle Soup',
  'Tomato Soup',
  'Vegetable Soup',
  'Pasta Sauce',
  'Alfredo Sauce',
  'Pesto',
  'Salsa',
  'Guacamole',
  'Olives',
  'Kalamata Olives',
  'Green Olives',
  'Pickles',
  'Capers',
];
