import { CuisineStaplesData } from '../../cuisine-staples/types';

export const cajun: CuisineStaplesData = {
  cuisine: 'Cajun',
  description: 'Louisiana Cajun staples with aromatic trinity and bold spices',
  subStyles: ['Acadiana', 'Rural Cajun'],
  staples: [
    {
      ingredient: 'onion',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Part of trinity',
      usage: 'Gumbo, jambalaya',
    },
    {
      ingredient: 'celery',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Part of trinity',
      usage: 'Gumbo, jambalaya',
    },
    {
      ingredient: 'green bell pepper',
      category: 'fresh_produce',
      priority: 'essential',
      reason: 'Part of trinity',
      usage: 'Gumbo, jambalaya',
    },
    {
      ingredient: 'garlic',
      category: 'fresh_produce',
      priority: 'recommended',
      reason: 'Aromatic',
      usage: 'Stews, sautés',
    },
    {
      ingredient: 'andouille sausage',
      category: 'proteins',
      priority: 'recommended',
      reason: 'Signature meat',
      usage: 'Gumbo, jambalaya',
    },
    {
      ingredient: 'cayenne pepper',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Heat',
      usage: 'Spice blends',
    },
    {
      ingredient: 'paprika',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Color and flavor',
      usage: 'Spice blends',
    },
    {
      ingredient: 'thyme',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Herb',
      usage: 'Stews',
    },
    {
      ingredient: 'bay leaves',
      category: 'flavor_builders',
      priority: 'recommended',
      reason: 'Aroma',
      usage: 'Stews',
    },
    {
      ingredient: 'file powder',
      category: 'flavor_builders',
      priority: 'optional',
      reason: 'Thickener and flavor',
      usage: 'Gumbo finish',
    },
    {
      ingredient: 'rice',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Base starch',
      usage: 'Jambalaya, sides',
    },
    {
      ingredient: 'flour',
      category: 'pantry_staples',
      priority: 'essential',
      reason: 'Roux',
      usage: 'Dark roux for gumbo',
    },
    {
      ingredient: 'oil',
      category: 'flavor_builders',
      priority: 'essential',
      reason: 'Roux fat',
      usage: 'Dark roux',
    },
  ],
};
